// Generated by ReScript, PLEASE EDIT WITH CARE

import * as McpMethod from "../protocol/McpMethod.mjs";
import * as McpLowLevelServerExperimentalTasksSupportMjs from "./McpLowLevelServerExperimentalTasksSupport.mjs";

function requestStreamRaw(tasks, method_, params) {
  return tasks.requestStream({
    method: McpMethod.requestToString(method_),
    params: params
  });
}

function requestStreamRawWithOptions(tasks, method_, params, options) {
  return tasks.requestStream({
    method: McpMethod.requestToString(method_),
    params: params
  }, options);
}

function listTasksWithOptions(prim0, prim1) {
  return McpLowLevelServerExperimentalTasksSupportMjs.listTasksWithOptions(prim0, prim1);
}

function createMessageStreamRaw(prim0, prim1) {
  return prim0.createMessageStream(prim1);
}

function createMessageStreamRawWithOptions(prim0, prim1, prim2) {
  return prim0.createMessageStream(prim1, prim2);
}

function elicitInputStreamRaw(prim0, prim1) {
  return prim0.elicitInputStream(prim1);
}

function elicitInputStreamRawWithOptions(prim0, prim1, prim2) {
  return prim0.elicitInputStream(prim1, prim2);
}

function getTask(prim0, prim1) {
  return prim0.getTask(prim1);
}

function getTaskWithOptions(prim0, prim1, prim2) {
  return prim0.getTask(prim1, prim2);
}

function getTaskResultRaw(prim0, prim1) {
  return prim0.getTaskResult(prim1);
}

function getTaskResultRawWithOptions(prim0, prim1, prim2) {
  return prim0.getTaskResult(prim1, prim2);
}

function listTasks(prim) {
  return prim.listTasks();
}

function listTasksWithCursor(prim0, prim1) {
  return prim0.listTasks(prim1);
}

function listTasksWithCursorAndOptions(prim0, prim1, prim2) {
  return prim0.listTasks(prim1, prim2);
}

function cancelTask(prim0, prim1) {
  return prim0.cancelTask(prim1);
}

function cancelTaskWithOptions(prim0, prim1, prim2) {
  return prim0.cancelTask(prim1, prim2);
}

export {
  requestStreamRaw,
  requestStreamRawWithOptions,
  createMessageStreamRaw,
  createMessageStreamRawWithOptions,
  elicitInputStreamRaw,
  elicitInputStreamRawWithOptions,
  getTask,
  getTaskWithOptions,
  getTaskResultRaw,
  getTaskResultRawWithOptions,
  listTasks,
  listTasksWithCursor,
  listTasksWithOptions,
  listTasksWithCursorAndOptions,
  cancelTask,
  cancelTaskWithOptions,
}
/* ./McpLowLevelServerExperimentalTasksSupport.mjs Not a pure module */
