// Generated by ReScript, PLEASE EDIT WITH CARE

import * as Primitive_option from "@rescript/runtime/lib/es6/Primitive_option.js";
import * as Server from "@modelcontextprotocol/sdk/server";

function make(prim) {
  return new Server.Server(prim);
}

function makeWithOptions(prim0, prim1) {
  return new Server.Server(prim0, prim1);
}

function connect(prim0, prim1) {
  return prim0.connect(prim1);
}

function close(prim) {
  return prim.close();
}

function ping(prim) {
  return prim.ping();
}

function registerCapabilities(prim0, prim1) {
  prim0.registerCapabilities(prim1);
}

function getClientCapabilities(prim) {
  return Primitive_option.fromNullable(prim.getClientCapabilities());
}

function getClientVersion(prim) {
  return Primitive_option.fromNullable(prim.getClientVersion());
}

function sendLoggingMessage(prim0, prim1) {
  return prim0.sendLoggingMessage(prim1);
}

function sendLoggingMessageWithSessionId(prim0, prim1, prim2) {
  return prim0.sendLoggingMessage(prim1, prim2);
}

function sendResourceUpdated(prim0, prim1) {
  return prim0.sendResourceUpdated(prim1);
}

function sendResourceListChanged(prim) {
  return prim.sendResourceListChanged();
}

function sendToolListChanged(prim) {
  return prim.sendToolListChanged();
}

function sendPromptListChanged(prim) {
  return prim.sendPromptListChanged();
}

function setRequestHandlerRaw(prim0, prim1, prim2) {
  prim0.setRequestHandler(prim1, prim2);
}

export {
  make,
  makeWithOptions,
  connect,
  close,
  ping,
  registerCapabilities,
  getClientCapabilities,
  getClientVersion,
  sendLoggingMessage,
  sendLoggingMessageWithSessionId,
  sendResourceUpdated,
  sendResourceListChanged,
  sendToolListChanged,
  sendPromptListChanged,
  setRequestHandlerRaw,
}
/* @modelcontextprotocol/sdk/server Not a pure module */
