// Generated by ReScript, PLEASE EDIT WITH CARE

import * as McpMethod from "../protocol/McpMethod.mjs";
import * as Primitive_option from "@rescript/runtime/lib/es6/Primitive_option.js";
import * as Server from "@modelcontextprotocol/server";

function experimentalTasks(server) {
  return server.experimental.tasks;
}

function setRequestHandlerRaw(server, method_, handler) {
  server.setRequestHandler(McpMethod.requestToString(method_), handler);
}

function make(prim) {
  return new Server.Server(prim);
}

function makeWithOptions(prim0, prim1) {
  return new Server.Server(prim0, prim1);
}

function connect(prim0, prim1) {
  return prim0.connect(prim1);
}

function close(prim) {
  return prim.close();
}

function ping(prim) {
  return prim.ping();
}

function registerCapabilities(prim0, prim1) {
  prim0.registerCapabilities(prim1);
}

function getCapabilities(prim) {
  return prim.getCapabilities();
}

function getClientCapabilities(prim) {
  return Primitive_option.fromNullable(prim.getClientCapabilities());
}

function getClientVersion(prim) {
  return Primitive_option.fromNullable(prim.getClientVersion());
}

function sendLoggingMessage(prim0, prim1) {
  return prim0.sendLoggingMessage(prim1);
}

function sendLoggingMessageWithSessionId(prim0, prim1, prim2) {
  return prim0.sendLoggingMessage(prim1, prim2);
}

function sendResourceUpdated(prim0, prim1) {
  return prim0.sendResourceUpdated(prim1);
}

function sendResourceListChanged(prim) {
  return prim.sendResourceListChanged();
}

function sendToolListChanged(prim) {
  return prim.sendToolListChanged();
}

function sendPromptListChanged(prim) {
  return prim.sendPromptListChanged();
}

function createMessage(prim0, prim1) {
  return prim0.createMessage(prim1);
}

function createMessageWithOptions(prim0, prim1, prim2) {
  return prim0.createMessage(prim1, prim2);
}

function createMessageRaw(prim0, prim1) {
  return prim0.createMessage(prim1);
}

function createMessageRawWithOptions(prim0, prim1, prim2) {
  return prim0.createMessage(prim1, prim2);
}

function elicitFormInput(prim0, prim1) {
  return prim0.elicitInput(prim1);
}

function elicitFormInputWithOptions(prim0, prim1, prim2) {
  return prim0.elicitInput(prim1, prim2);
}

function elicitUrlInput(prim0, prim1) {
  return prim0.elicitInput(prim1);
}

function elicitUrlInputWithOptions(prim0, prim1, prim2) {
  return prim0.elicitInput(prim1, prim2);
}

function elicitInputRaw(prim0, prim1) {
  return prim0.elicitInput(prim1);
}

function elicitInputRawWithOptions(prim0, prim1, prim2) {
  return prim0.elicitInput(prim1, prim2);
}

function listRoots(prim) {
  return prim.listRoots();
}

function listRootsWithParamsAndOptions(prim0, prim1, prim2) {
  return prim0.listRoots(prim1, prim2);
}

export {
  make,
  makeWithOptions,
  experimentalTasks,
  connect,
  close,
  ping,
  registerCapabilities,
  getCapabilities,
  getClientCapabilities,
  getClientVersion,
  sendLoggingMessage,
  sendLoggingMessageWithSessionId,
  sendResourceUpdated,
  sendResourceListChanged,
  sendToolListChanged,
  sendPromptListChanged,
  createMessage,
  createMessageWithOptions,
  createMessageRaw,
  createMessageRawWithOptions,
  elicitFormInput,
  elicitFormInputWithOptions,
  elicitUrlInput,
  elicitUrlInputWithOptions,
  elicitInputRaw,
  elicitInputRawWithOptions,
  listRoots,
  listRootsWithParamsAndOptions,
  setRequestHandlerRaw,
}
/* @modelcontextprotocol/server Not a pure module */
