// Generated by ReScript, PLEASE EDIT WITH CARE

import * as Primitive_option from "@rescript/runtime/lib/es6/Primitive_option.js";

function makeConfig(prim0, prim1, prim2, prim3, prim4) {
  let tmp = {};
  if (prim0 !== undefined) {
    tmp.title = prim0;
  }
  if (prim1 !== undefined) {
    tmp.description = prim1;
  }
  if (prim2 !== undefined) {
    tmp.argsSchema = Primitive_option.valFromOption(prim2);
  }
  if (prim3 !== undefined) {
    tmp._meta = Primitive_option.valFromOption(prim3);
  }
  return tmp;
}

function enable(prim) {
  prim.enable();
}

function disable(prim) {
  prim.disable();
}

function makeUpdates(prim0, prim1, prim2, prim3, prim4, prim5, prim6, prim7) {
  let tmp = {};
  if (prim0 !== undefined) {
    tmp.name = prim0;
  }
  if (prim1 !== undefined) {
    tmp.title = prim1;
  }
  if (prim2 !== undefined) {
    tmp.description = prim2;
  }
  if (prim3 !== undefined) {
    tmp.argsSchema = Primitive_option.valFromOption(prim3);
  }
  if (prim4 !== undefined) {
    tmp._meta = Primitive_option.valFromOption(prim4);
  }
  if (prim5 !== undefined) {
    tmp.callback = Primitive_option.valFromOption(prim5);
  }
  if (prim6 !== undefined) {
    tmp.enabled = prim6;
  }
  return tmp;
}

function makeUpdates0(prim0, prim1, prim2, prim3, prim4, prim5, prim6) {
  let tmp = {};
  if (prim0 !== undefined) {
    tmp.name = prim0;
  }
  if (prim1 !== undefined) {
    tmp.title = prim1;
  }
  if (prim2 !== undefined) {
    tmp.description = prim2;
  }
  if (prim3 !== undefined) {
    tmp._meta = Primitive_option.valFromOption(prim3);
  }
  if (prim4 !== undefined) {
    tmp.callback = Primitive_option.valFromOption(prim4);
  }
  if (prim5 !== undefined) {
    tmp.enabled = prim5;
  }
  return tmp;
}

function update(prim0, prim1) {
  prim0.update(prim1);
}

function update0(prim0, prim1) {
  prim0.update(prim1);
}

function remove(prim) {
  prim.remove();
}

export {
  makeConfig,
  enable,
  disable,
  makeUpdates,
  makeUpdates0,
  update,
  update0,
  remove,
}
/* No side effect */
