// Generated by ReScript, PLEASE EDIT WITH CARE

import * as Primitive_option from "@rescript/runtime/lib/es6/Primitive_option.js";
import * as Server from "@modelcontextprotocol/server";

function completionArguments(prim) {
  return prim.arguments();
}

function makeCallbacks(prim0, prim1, prim2) {
  let tmp = {
    list: prim0
  };
  if (prim1 !== undefined) {
    tmp.complete = Primitive_option.valFromOption(prim1);
  }
  return tmp;
}

function make(prim0, prim1) {
  return new Server.ResourceTemplate(prim0, prim1);
}

function makeWithUriTemplate(prim0, prim1) {
  return new Server.ResourceTemplate(prim0, prim1);
}

function uriTemplate(prim) {
  return prim.uriTemplate;
}

function listCallback(prim) {
  return Primitive_option.fromNullable(prim.listCallback);
}

function completeCallback(prim0, prim1) {
  return Primitive_option.fromNullable(prim0.completeCallback(prim1));
}

function makeUpdates(prim0, prim1, prim2, prim3, prim4, prim5, prim6) {
  let tmp = {};
  if (prim0 !== undefined) {
    tmp.name = prim0;
  }
  if (prim1 !== undefined) {
    tmp.title = prim1;
  }
  if (prim2 !== undefined) {
    tmp.template = Primitive_option.valFromOption(prim2);
  }
  if (prim3 !== undefined) {
    tmp.metadata = Primitive_option.valFromOption(prim3);
  }
  if (prim4 !== undefined) {
    tmp.callback = Primitive_option.valFromOption(prim4);
  }
  if (prim5 !== undefined) {
    tmp.enabled = prim5;
  }
  return tmp;
}

function enable(prim) {
  prim.enable();
}

function disable(prim) {
  prim.disable();
}

function update(prim0, prim1) {
  prim0.update(prim1);
}

function remove(prim) {
  prim.remove();
}

export {
  completionArguments,
  makeCallbacks,
  make,
  makeWithUriTemplate,
  uriTemplate,
  listCallback,
  completeCallback,
  makeUpdates,
  enable,
  disable,
  update,
  remove,
}
/* @modelcontextprotocol/server Not a pure module */
