// Generated by ReScript, PLEASE EDIT WITH CARE

import * as McpMethod from "../protocol/McpMethod.mjs";
import * as Stdlib_Option from "@rescript/runtime/lib/es6/Stdlib_Option.js";
import * as Primitive_option from "@rescript/runtime/lib/es6/Primitive_option.js";

function requestId(context) {
  return context.mcpReq.id;
}

function requestMethod(context) {
  return McpMethod.requestFromString(context.mcpReq.method);
}

function requestMeta(context) {
  return Primitive_option.fromNullable(context.mcpReq._meta);
}

function requestSignal(context) {
  return context.mcpReq.signal;
}

function sendRelatedRequestRaw(context, method_, params) {
  return context.mcpReq.send({
    method: McpMethod.requestToString(method_),
    params: params
  });
}

function sendRelatedRequestRawWithOptions(context, method_, params, options) {
  return context.mcpReq.send({
    method: McpMethod.requestToString(method_),
    params: params
  }, options);
}

function sendRelatedNotificationRaw(context, method_, params) {
  return context.mcpReq.notify({
    method: McpMethod.notificationToString(method_),
    params: params
  });
}

function log(context, level, data) {
  return context.mcpReq.log(level, data);
}

function logWithLogger(context, level, data, logger) {
  return context.mcpReq.log(level, data, logger);
}

function elicitInputRaw(context, params) {
  return context.mcpReq.elicitInput(params);
}

function elicitInputRawWithOptions(context, params, options) {
  return context.mcpReq.elicitInput(params, options);
}

function elicitFormInput(context, params) {
  return context.mcpReq.elicitInput(params);
}

function elicitFormInputWithOptions(context, params, options) {
  return context.mcpReq.elicitInput(params, options);
}

function elicitUrlInput(context, params) {
  return context.mcpReq.elicitInput(params);
}

function elicitUrlInputWithOptions(context, params, options) {
  return context.mcpReq.elicitInput(params, options);
}

function requestSamplingRaw(context, params) {
  return context.mcpReq.requestSampling(params);
}

function requestSamplingRawWithOptions(context, params, options) {
  return context.mcpReq.requestSampling(params, options);
}

function requestSampling(context, params) {
  return context.mcpReq.requestSampling(params);
}

function requestSamplingWithOptions(context, params, options) {
  return context.mcpReq.requestSampling(params, options);
}

function httpAuthInfo(context) {
  return Stdlib_Option.flatMap(Primitive_option.fromNullable(context.http), prim => Primitive_option.fromNullable(prim.authInfo));
}

function httpRequest(context) {
  return Stdlib_Option.flatMap(Primitive_option.fromNullable(context.http), prim => Primitive_option.fromNullable(prim.req));
}

function closeSSE(context) {
  return Stdlib_Option.flatMap(Primitive_option.fromNullable(context.http), prim => Primitive_option.fromNullable(prim.closeSSE));
}

function closeStandaloneSSE(context) {
  return Stdlib_Option.flatMap(Primitive_option.fromNullable(context.http), prim => Primitive_option.fromNullable(prim.closeStandaloneSSE));
}

function task(context) {
  return Primitive_option.fromNullable(context.task);
}

function sessionId(prim) {
  return Primitive_option.fromNullable(prim.sessionId);
}

export {
  sessionId,
  task,
  requestId,
  requestMethod,
  requestMeta,
  requestSignal,
  sendRelatedRequestRaw,
  sendRelatedRequestRawWithOptions,
  sendRelatedNotificationRaw,
  log,
  logWithLogger,
  elicitFormInput,
  elicitFormInputWithOptions,
  elicitUrlInput,
  elicitUrlInputWithOptions,
  elicitInputRaw,
  elicitInputRawWithOptions,
  requestSampling,
  requestSamplingWithOptions,
  requestSamplingRaw,
  requestSamplingRawWithOptions,
  httpAuthInfo,
  httpRequest,
  closeSSE,
  closeStandaloneSSE,
}
/* No side effect */
