// Generated by ReScript, PLEASE EDIT WITH CARE

import * as McpTaskTool from "./McpTaskTool.mjs";
import * as McpCallToolResultInternal from "../protocol/McpCallToolResultInternal.mjs";

function registerToolTask(tasks, name, config, handler) {
  return tasks.registerToolTask(name, config, McpTaskTool.makeRawHandler(handler.createTask, handler.getTask, async (args, ctx) => {
    let result = await handler.getTaskResult(args, ctx);
    return McpCallToolResultInternal.toRaw(result, config.outputSchema);
  }, undefined));
}

function registerToolTask0(tasks, name, config, handler) {
  return tasks.registerToolTask(name, config, McpTaskTool.makeRawHandler0(handler.createTask, handler.getTask, async ctx => {
    let result = await handler.getTaskResult(ctx);
    return McpCallToolResultInternal.toRaw(result, config.outputSchema);
  }, undefined));
}

function registerToolTaskRaw(prim0, prim1, prim2, prim3) {
  return prim0.registerToolTask(prim1, prim2, prim3);
}

function registerToolTaskRaw0(prim0, prim1, prim2, prim3) {
  return prim0.registerToolTask(prim1, prim2, prim3);
}

export {
  registerToolTask,
  registerToolTask0,
  registerToolTaskRaw,
  registerToolTaskRaw0,
}
/* McpCallToolResultInternal Not a pure module */
