// Generated by ReScript, PLEASE EDIT WITH CARE

import * as McpCallToolResultInternal from "../protocol/McpCallToolResultInternal.mjs";
import * as Server from "@modelcontextprotocol/server";

function experimentalTasks(server) {
  return server.experimental.tasks;
}

function registerTool(server, name, config, callback) {
  return server.registerTool(name, config, async (args, ctx) => {
    let result = await callback(args, ctx);
    return McpCallToolResultInternal.toRaw(result, config.outputSchema);
  });
}

function registerTool0(server, name, config, callback) {
  return server.registerTool(name, config, async ctx => {
    let result = await callback(ctx);
    return McpCallToolResultInternal.toRaw(result, config.outputSchema);
  });
}

function make(prim) {
  return new Server.McpServer(prim);
}

function makeWithOptions(prim0, prim1) {
  return new Server.McpServer(prim0, prim1);
}

function server(prim) {
  return prim.server;
}

function connect(prim0, prim1) {
  return prim0.connect(prim1);
}

function close(prim) {
  return prim.close();
}

function registerToolRaw(prim0, prim1, prim2, prim3) {
  return prim0.registerTool(prim1, prim2, prim3);
}

function registerToolRaw0(prim0, prim1, prim2, prim3) {
  return prim0.registerTool(prim1, prim2, prim3);
}

function registerPrompt(prim0, prim1, prim2, prim3) {
  return prim0.registerPrompt(prim1, prim2, prim3);
}

function registerPrompt0(prim0, prim1, prim2, prim3) {
  return prim0.registerPrompt(prim1, prim2, prim3);
}

function registerResource(prim0, prim1, prim2, prim3, prim4) {
  return prim0.registerResource(prim1, prim2, prim3, prim4);
}

function registerResourceTemplate(prim0, prim1, prim2, prim3, prim4) {
  return prim0.registerResource(prim1, prim2, prim3, prim4);
}

function isConnected(prim) {
  return prim.isConnected();
}

function sendLoggingMessage(prim0, prim1) {
  return prim0.sendLoggingMessage(prim1);
}

function sendLoggingMessageWithSessionId(prim0, prim1, prim2) {
  return prim0.sendLoggingMessage(prim1, prim2);
}

function sendResourceListChanged(prim) {
  prim.sendResourceListChanged();
}

function sendToolListChanged(prim) {
  prim.sendToolListChanged();
}

function sendPromptListChanged(prim) {
  prim.sendPromptListChanged();
}

export {
  make,
  makeWithOptions,
  experimentalTasks,
  server,
  connect,
  close,
  registerTool,
  registerTool0,
  registerToolRaw,
  registerToolRaw0,
  registerPrompt,
  registerPrompt0,
  registerResource,
  registerResourceTemplate,
  isConnected,
  sendLoggingMessage,
  sendLoggingMessageWithSessionId,
  sendResourceListChanged,
  sendToolListChanged,
  sendPromptListChanged,
}
/* McpCallToolResultInternal Not a pure module */
