// Generated by ReScript, PLEASE EDIT WITH CARE

import * as Stdlib_Option from "@rescript/runtime/lib/es6/Stdlib_Option.js";
import * as Primitive_option from "@rescript/runtime/lib/es6/Primitive_option.js";
import * as McpProtocolVersion from "../core/McpProtocolVersion.mjs";

function make(capabilities, instructions, jsonSchemaValidator, supportedProtocolVersions, enforceStrictCapabilities, debouncedNotificationMethods, tasks, param) {
  let supportedProtocolVersions$1 = Stdlib_Option.map(supportedProtocolVersions, versions => versions.map(McpProtocolVersion.toString));
  let tmp = {};
  if (capabilities !== undefined) {
    tmp.capabilities = Primitive_option.valFromOption(capabilities);
  }
  if (instructions !== undefined) {
    tmp.instructions = instructions;
  }
  if (jsonSchemaValidator !== undefined) {
    tmp.jsonSchemaValidator = Primitive_option.valFromOption(jsonSchemaValidator);
  }
  if (supportedProtocolVersions$1 !== undefined) {
    tmp.supportedProtocolVersions = Primitive_option.valFromOption(supportedProtocolVersions$1);
  }
  if (enforceStrictCapabilities !== undefined) {
    tmp.enforceStrictCapabilities = enforceStrictCapabilities;
  }
  if (debouncedNotificationMethods !== undefined) {
    tmp.debouncedNotificationMethods = Primitive_option.valFromOption(debouncedNotificationMethods);
  }
  if (tasks !== undefined) {
    tmp.tasks = Primitive_option.valFromOption(tasks);
  }
  return tmp;
}

export {
  make,
}
/* No side effect */
