// Generated by ReScript, PLEASE EDIT WITH CARE

import * as Mcp from "@modelcontextprotocol/sdk/server/mcp";

function make(prim) {
  return new Mcp.McpServer(prim);
}

function makeWithOptions(prim0, prim1) {
  return new Mcp.McpServer(prim0, prim1);
}

function server(prim) {
  return prim.server;
}

function connect(prim0, prim1) {
  return prim0.connect(prim1);
}

function close(prim) {
  return prim.close();
}

function isConnected(prim) {
  return prim.isConnected();
}

function sendLoggingMessage(prim0, prim1) {
  return prim0.sendLoggingMessage(prim1);
}

function sendLoggingMessageWithSessionId(prim0, prim1, prim2) {
  return prim0.sendLoggingMessage(prim1, prim2);
}

function sendResourceListChanged(prim) {
  prim.sendResourceListChanged();
}

function sendToolListChanged(prim) {
  prim.sendToolListChanged();
}

function sendPromptListChanged(prim) {
  prim.sendPromptListChanged();
}

export {
  make,
  makeWithOptions,
  server,
  connect,
  close,
  isConnected,
  sendLoggingMessage,
  sendLoggingMessageWithSessionId,
  sendResourceListChanged,
  sendToolListChanged,
  sendPromptListChanged,
}
/* @modelcontextprotocol/sdk/server/mcp Not a pure module */
