// Generated by ReScript, PLEASE EDIT WITH CARE

import * as Primitive_option from "@rescript/runtime/lib/es6/Primitive_option.js";

function makeExecution(prim0, prim1) {
  let tmp = {};
  if (prim0 !== undefined) {
    tmp.taskSupport = Primitive_option.valFromOption(prim0);
  }
  return tmp;
}

function makeConfig(prim0, prim1, prim2, prim3, prim4, prim5, prim6, prim7) {
  let tmp = {
    outputSchema: prim3
  };
  if (prim0 !== undefined) {
    tmp.title = prim0;
  }
  if (prim1 !== undefined) {
    tmp.description = prim1;
  }
  if (prim2 !== undefined) {
    tmp.inputSchema = Primitive_option.valFromOption(prim2);
  }
  if (prim4 !== undefined) {
    tmp.annotations = Primitive_option.valFromOption(prim4);
  }
  if (prim5 !== undefined) {
    tmp.execution = Primitive_option.valFromOption(prim5);
  }
  if (prim6 !== undefined) {
    tmp._meta = Primitive_option.valFromOption(prim6);
  }
  return tmp;
}

function makeRawConfig(prim0, prim1, prim2, prim3, prim4, prim5, prim6) {
  let tmp = {};
  if (prim0 !== undefined) {
    tmp.title = prim0;
  }
  if (prim1 !== undefined) {
    tmp.description = prim1;
  }
  if (prim2 !== undefined) {
    tmp.inputSchema = Primitive_option.valFromOption(prim2);
  }
  if (prim3 !== undefined) {
    tmp.annotations = Primitive_option.valFromOption(prim3);
  }
  if (prim4 !== undefined) {
    tmp.execution = Primitive_option.valFromOption(prim4);
  }
  if (prim5 !== undefined) {
    tmp._meta = Primitive_option.valFromOption(prim5);
  }
  return tmp;
}

function makeHandler(prim0, prim1, prim2, prim3) {
  return {
    createTask: prim0,
    getTask: prim1,
    getTaskResult: prim2
  };
}

function makeRawHandler(prim0, prim1, prim2, prim3) {
  return {
    createTask: prim0,
    getTask: prim1,
    getTaskResult: prim2
  };
}

function makeHandler0(prim0, prim1, prim2, prim3) {
  return {
    createTask: prim0,
    getTask: prim1,
    getTaskResult: prim2
  };
}

function makeRawHandler0(prim0, prim1, prim2, prim3) {
  return {
    createTask: prim0,
    getTask: prim1,
    getTaskResult: prim2
  };
}

export {
  makeExecution,
  makeConfig,
  makeRawConfig,
  makeHandler,
  makeRawHandler,
  makeHandler0,
  makeRawHandler0,
}
/* No side effect */
