// Generated by ReScript, PLEASE EDIT WITH CARE

import * as Stdlib_Option from "@rescript/runtime/lib/es6/Stdlib_Option.js";
import * as Primitive_option from "@rescript/runtime/lib/es6/Primitive_option.js";
import * as McpCallToolResultInternal from "../protocol/McpCallToolResultInternal.mjs";

function makeUpdates(name, title, description, paramsSchema, outputSchema, annotations, _meta, callback, enabled, param) {
  let callback$1 = Stdlib_Option.map(callback, callback => (async (args, ctx) => {
    let result = await callback(args, ctx);
    return McpCallToolResultInternal.toRaw(result, outputSchema);
  }));
  let tmp = {
    outputSchema: outputSchema
  };
  if (name !== undefined) {
    tmp.name = name;
  }
  if (title !== undefined) {
    tmp.title = title;
  }
  if (description !== undefined) {
    tmp.description = description;
  }
  if (paramsSchema !== undefined) {
    tmp.paramsSchema = Primitive_option.valFromOption(paramsSchema);
  }
  if (annotations !== undefined) {
    tmp.annotations = Primitive_option.valFromOption(annotations);
  }
  if (_meta !== undefined) {
    tmp._meta = Primitive_option.valFromOption(_meta);
  }
  if (callback$1 !== undefined) {
    tmp.callback = Primitive_option.valFromOption(callback$1);
  }
  if (enabled !== undefined) {
    tmp.enabled = enabled;
  }
  return tmp;
}

function makeUpdates0(name, title, description, outputSchema, annotations, _meta, callback, enabled, param) {
  let callback$1 = Stdlib_Option.map(callback, callback => (async ctx => {
    let result = await callback(ctx);
    return McpCallToolResultInternal.toRaw(result, outputSchema);
  }));
  let tmp = {
    outputSchema: outputSchema
  };
  if (name !== undefined) {
    tmp.name = name;
  }
  if (title !== undefined) {
    tmp.title = title;
  }
  if (description !== undefined) {
    tmp.description = description;
  }
  if (annotations !== undefined) {
    tmp.annotations = Primitive_option.valFromOption(annotations);
  }
  if (_meta !== undefined) {
    tmp._meta = Primitive_option.valFromOption(_meta);
  }
  if (callback$1 !== undefined) {
    tmp.callback = Primitive_option.valFromOption(callback$1);
  }
  if (enabled !== undefined) {
    tmp.enabled = enabled;
  }
  return tmp;
}

function makeConfig(prim0, prim1, prim2, prim3, prim4, prim5, prim6) {
  let tmp = {
    outputSchema: prim3
  };
  if (prim0 !== undefined) {
    tmp.title = prim0;
  }
  if (prim1 !== undefined) {
    tmp.description = prim1;
  }
  if (prim2 !== undefined) {
    tmp.inputSchema = Primitive_option.valFromOption(prim2);
  }
  if (prim4 !== undefined) {
    tmp.annotations = Primitive_option.valFromOption(prim4);
  }
  if (prim5 !== undefined) {
    tmp._meta = Primitive_option.valFromOption(prim5);
  }
  return tmp;
}

function makeRawConfig(prim0, prim1, prim2, prim3, prim4, prim5) {
  let tmp = {};
  if (prim0 !== undefined) {
    tmp.title = prim0;
  }
  if (prim1 !== undefined) {
    tmp.description = prim1;
  }
  if (prim2 !== undefined) {
    tmp.inputSchema = Primitive_option.valFromOption(prim2);
  }
  if (prim3 !== undefined) {
    tmp.annotations = Primitive_option.valFromOption(prim3);
  }
  if (prim4 !== undefined) {
    tmp._meta = Primitive_option.valFromOption(prim4);
  }
  return tmp;
}

function enable(prim) {
  prim.enable();
}

function disable(prim) {
  prim.disable();
}

function makeRawUpdates(prim0, prim1, prim2, prim3, prim4, prim5, prim6, prim7, prim8) {
  let tmp = {};
  if (prim0 !== undefined) {
    tmp.name = prim0;
  }
  if (prim1 !== undefined) {
    tmp.title = prim1;
  }
  if (prim2 !== undefined) {
    tmp.description = prim2;
  }
  if (prim3 !== undefined) {
    tmp.paramsSchema = Primitive_option.valFromOption(prim3);
  }
  if (prim4 !== undefined) {
    tmp.annotations = Primitive_option.valFromOption(prim4);
  }
  if (prim5 !== undefined) {
    tmp._meta = Primitive_option.valFromOption(prim5);
  }
  if (prim6 !== undefined) {
    tmp.callback = Primitive_option.valFromOption(prim6);
  }
  if (prim7 !== undefined) {
    tmp.enabled = prim7;
  }
  return tmp;
}

function makeRawUpdates0(prim0, prim1, prim2, prim3, prim4, prim5, prim6, prim7) {
  let tmp = {};
  if (prim0 !== undefined) {
    tmp.name = prim0;
  }
  if (prim1 !== undefined) {
    tmp.title = prim1;
  }
  if (prim2 !== undefined) {
    tmp.description = prim2;
  }
  if (prim3 !== undefined) {
    tmp.annotations = Primitive_option.valFromOption(prim3);
  }
  if (prim4 !== undefined) {
    tmp._meta = Primitive_option.valFromOption(prim4);
  }
  if (prim5 !== undefined) {
    tmp.callback = Primitive_option.valFromOption(prim5);
  }
  if (prim6 !== undefined) {
    tmp.enabled = prim6;
  }
  return tmp;
}

function update(prim0, prim1) {
  prim0.update(prim1);
}

function updateRaw(prim0, prim1) {
  prim0.update(prim1);
}

function update0(prim0, prim1) {
  prim0.update(prim1);
}

function updateRaw0(prim0, prim1) {
  prim0.update(prim1);
}

function remove(prim) {
  prim.remove();
}

export {
  makeConfig,
  makeRawConfig,
  enable,
  disable,
  makeUpdates,
  makeRawUpdates,
  makeUpdates0,
  makeRawUpdates0,
  update,
  updateRaw,
  update0,
  updateRaw0,
  remove,
}
/* McpCallToolResultInternal Not a pure module */
