// Generated by ReScript, PLEASE EDIT WITH CARE

import * as McpWebStandardStreamableHttpServerTransportOptions from "./McpWebStandardStreamableHttpServerTransportOptions.mjs";

let make = McpWebStandardStreamableHttpServerTransportOptions.make;

export {
  make,
}
/* No side effect */
