// Generated by ReScript, PLEASE EDIT WITH CARE

import * as StreamableHttp from "@modelcontextprotocol/sdk/server/streamableHttp";

function make(prim) {
  return new StreamableHttp.StreamableHTTPServerTransport();
}

function makeWithOptions(prim) {
  return new StreamableHttp.StreamableHTTPServerTransport(prim);
}

function handleRequest(prim0, prim1, prim2) {
  return prim0.handleRequest(prim1, prim2);
}

function handleRequestWithParsedBody(prim0, prim1, prim2, prim3) {
  return prim0.handleRequest(prim1, prim2, prim3);
}

function closeSSEStream(prim0, prim1) {
  prim0.closeSSEStream(prim1);
}

function closeStandaloneSSEStream(prim) {
  prim.closeStandaloneSSEStream();
}

export {
  make,
  makeWithOptions,
  handleRequest,
  handleRequestWithParsedBody,
  closeSSEStream,
  closeStandaloneSSEStream,
}
/* @modelcontextprotocol/sdk/server/streamableHttp Not a pure module */
