// Generated by ReScript, PLEASE EDIT WITH CARE

import * as Node from "@modelcontextprotocol/node";

function make(prim) {
  return new Node.NodeStreamableHTTPServerTransport();
}

function makeWithOptions(prim) {
  return new Node.NodeStreamableHTTPServerTransport(prim);
}

function handleRequest(prim0, prim1, prim2) {
  return prim0.handleRequest(prim1, prim2);
}

function handleRequestWithParsedBody(prim0, prim1, prim2, prim3) {
  return prim0.handleRequest(prim1, prim2, prim3);
}

function closeSSEStream(prim0, prim1) {
  prim0.closeSSEStream(prim1);
}

function closeStandaloneSSEStream(prim) {
  prim.closeStandaloneSSEStream();
}

export {
  make,
  makeWithOptions,
  handleRequest,
  handleRequestWithParsedBody,
  closeSSEStream,
  closeStandaloneSSEStream,
}
/* @modelcontextprotocol/node Not a pure module */
