// Generated by ReScript, PLEASE EDIT WITH CARE

import * as Primitive_option from "@rescript/runtime/lib/es6/Primitive_option.js";

function make(prim0, prim1, prim2, prim3, prim4, prim5) {
  let tmp = {};
  if (prim0 !== undefined) {
    tmp.authProvider = Primitive_option.valFromOption(prim0);
  }
  if (prim1 !== undefined) {
    tmp.requestInit = Primitive_option.valFromOption(prim1);
  }
  if (prim2 !== undefined) {
    tmp.fetch = Primitive_option.valFromOption(prim2);
  }
  if (prim3 !== undefined) {
    tmp.reconnectionOptions = Primitive_option.valFromOption(prim3);
  }
  if (prim4 !== undefined) {
    tmp.sessionId = prim4;
  }
  return tmp;
}

export {
  make,
}
/* No side effect */
