// Generated by ReScript, PLEASE EDIT WITH CARE

import * as Stdlib_Option from "@rescript/runtime/lib/es6/Stdlib_Option.js";
import * as Primitive_option from "@rescript/runtime/lib/es6/Primitive_option.js";
import * as McpProtocolVersion from "../core/McpProtocolVersion.mjs";

function make(authProvider, requestInit, fetch, reconnectionOptions, reconnectionScheduler, sessionId, protocolVersion, param) {
  let protocolVersion$1 = Stdlib_Option.map(protocolVersion, McpProtocolVersion.toString);
  let tmp = {};
  if (authProvider !== undefined) {
    tmp.authProvider = Primitive_option.valFromOption(authProvider);
  }
  if (requestInit !== undefined) {
    tmp.requestInit = Primitive_option.valFromOption(requestInit);
  }
  if (fetch !== undefined) {
    tmp.fetch = Primitive_option.valFromOption(fetch);
  }
  if (reconnectionOptions !== undefined) {
    tmp.reconnectionOptions = Primitive_option.valFromOption(reconnectionOptions);
  }
  if (reconnectionScheduler !== undefined) {
    tmp.reconnectionScheduler = Primitive_option.valFromOption(reconnectionScheduler);
  }
  if (sessionId !== undefined) {
    tmp.sessionId = sessionId;
  }
  if (protocolVersion$1 !== undefined) {
    tmp.protocolVersion = protocolVersion$1;
  }
  return tmp;
}

export {
  make,
}
/* No side effect */
