// Generated by ReScript, PLEASE EDIT WITH CARE

import * as Primitive_option from "@rescript/runtime/lib/es6/Primitive_option.js";
import * as StreamableHttp from "@modelcontextprotocol/sdk/client/streamableHttp";

function make(prim) {
  return new StreamableHttp.StreamableHTTPClientTransport(prim);
}

function makeWithOptions(prim0, prim1) {
  return new StreamableHttp.StreamableHTTPClientTransport(prim0, prim1);
}

function finishAuth(prim0, prim1) {
  return prim0.finishAuth(prim1);
}

function terminateSession(prim) {
  return prim.terminateSession();
}

function setProtocolVersion(prim0, prim1) {
  prim0.setProtocolVersion(prim1);
}

function protocolVersion(prim) {
  return Primitive_option.fromNullable(prim.protocolVersion);
}

export {
  make,
  makeWithOptions,
  finishAuth,
  terminateSession,
  setProtocolVersion,
  protocolVersion,
}
/* @modelcontextprotocol/sdk/client/streamableHttp Not a pure module */
