// Generated by ReScript, PLEASE EDIT WITH CARE

import * as Stdlib_Option from "@rescript/runtime/lib/es6/Stdlib_Option.js";
import * as Primitive_option from "@rescript/runtime/lib/es6/Primitive_option.js";
import * as McpProtocolVersion from "../core/McpProtocolVersion.mjs";
import * as Client from "@modelcontextprotocol/client";

function setProtocolVersion(transport, version) {
  transport.setProtocolVersion(McpProtocolVersion.toString(version));
}

function protocolVersion(transport) {
  return Stdlib_Option.map(Primitive_option.fromNullable(transport.protocolVersion), McpProtocolVersion.fromString);
}

function make(prim) {
  return new Client.StreamableHTTPClientTransport(prim);
}

function makeWithOptions(prim0, prim1) {
  return new Client.StreamableHTTPClientTransport(prim0, prim1);
}

function finishAuth(prim0, prim1) {
  return prim0.finishAuth(prim1);
}

function terminateSession(prim) {
  return prim.terminateSession();
}

export {
  make,
  makeWithOptions,
  finishAuth,
  terminateSession,
  setProtocolVersion,
  protocolVersion,
}
/* @modelcontextprotocol/client Not a pure module */
