// Generated by ReScript, PLEASE EDIT WITH CARE


function make(prim0, prim1, prim2, prim3) {
  return {
    maxReconnectionDelay: prim0,
    initialReconnectionDelay: prim1,
    reconnectionDelayGrowFactor: prim2,
    maxRetries: prim3
  };
}

export {
  make,
}
/* No side effect */
