// Generated by ReScript, PLEASE EDIT WITH CARE

import * as Primitive_option from "@rescript/runtime/lib/es6/Primitive_option.js";
import * as StdioJs from "@modelcontextprotocol/sdk/client/stdio.js";

function make(prim) {
  return new StdioJs.StdioClientTransport(prim);
}

let defaultInheritedEnvVars = StdioJs.DEFAULT_INHERITED_ENV_VARS;

function getDefaultEnvironment(prim) {
  return StdioJs.getDefaultEnvironment();
}

function stderr(prim) {
  return Primitive_option.fromNullable(prim.stderr);
}

function pid(prim) {
  return Primitive_option.fromNullable(prim.pid);
}

export {
  make,
  defaultInheritedEnvVars,
  getDefaultEnvironment,
  stderr,
  pid,
}
/* defaultInheritedEnvVars Not a pure module */
