// Generated by ReScript, PLEASE EDIT WITH CARE

import * as McpProtocolVersion from "../core/McpProtocolVersion.mjs";
import * as Client from "@modelcontextprotocol/client";

function setProtocolVersion(transport, version) {
  transport.setProtocolVersion(McpProtocolVersion.toString(version));
}

function make(prim) {
  return new Client.SSEClientTransport(prim);
}

function makeWithOptions(prim0, prim1) {
  return new Client.SSEClientTransport(prim0, prim1);
}

function finishAuth(prim0, prim1) {
  return prim0.finishAuth(prim1);
}

export {
  make,
  makeWithOptions,
  finishAuth,
  setProtocolVersion,
}
/* @modelcontextprotocol/client Not a pure module */
