// Generated by ReScript, PLEASE EDIT WITH CARE

import * as StdioJs from "@modelcontextprotocol/sdk/server/stdio.js";

function make(prim) {
  return new StdioJs.StdioServerTransport();
}

function makeWithStreams(prim0, prim1) {
  return new StdioJs.StdioServerTransport(prim0, prim1);
}

export {
  make,
  makeWithStreams,
}
/* @modelcontextprotocol/sdk/server/stdio.js Not a pure module */
