// Generated by ReScript, PLEASE EDIT WITH CARE

import * as Primitive_option from "@rescript/runtime/lib/es6/Primitive_option.js";

function make(prim0, prim1, prim2, prim3, prim4) {
  let tmp = {
    command: prim0
  };
  if (prim1 !== undefined) {
    tmp.args = Primitive_option.valFromOption(prim1);
  }
  if (prim2 !== undefined) {
    tmp.env = Primitive_option.valFromOption(prim2);
  }
  if (prim3 !== undefined) {
    tmp.stderr = Primitive_option.valFromOption(prim3);
  }
  if (prim4 !== undefined) {
    tmp.cwd = prim4;
  }
  return tmp;
}

export {
  make,
}
/* No side effect */
