// Generated by ReScript, PLEASE EDIT WITH CARE

import * as Primitive_option from "@rescript/runtime/lib/es6/Primitive_option.js";
import * as Stdio from "@modelcontextprotocol/sdk/client/stdio";

function make(prim) {
  return new Stdio.StdioClientTransport(prim);
}

let defaultInheritedEnvVars = Stdio.DEFAULT_INHERITED_ENV_VARS;

function getDefaultEnvironment(prim) {
  return Stdio.getDefaultEnvironment();
}

function stderr(prim) {
  return Primitive_option.fromNullable(prim.stderr);
}

function pid(prim) {
  return Primitive_option.fromNullable(prim.pid);
}

export {
  make,
  defaultInheritedEnvVars,
  getDefaultEnvironment,
  stderr,
  pid,
}
/* defaultInheritedEnvVars Not a pure module */
