// Generated by ReScript, PLEASE EDIT WITH CARE

import * as Server from "@modelcontextprotocol/server";

function make(prim) {
  return new Server.StdioServerTransport();
}

function makeWithStreams(prim0, prim1) {
  return new Server.StdioServerTransport(prim0, prim1);
}

export {
  make,
  makeWithStreams,
}
/* @modelcontextprotocol/server Not a pure module */
