// Generated by ReScript, PLEASE EDIT WITH CARE

import * as Stdio from "@modelcontextprotocol/sdk/server/stdio";

function make(prim) {
  return new Stdio.StdioServerTransport();
}

function makeWithStreams(prim0, prim1) {
  return new Stdio.StdioServerTransport(prim0, prim1);
}

export {
  make,
  makeWithStreams,
}
/* @modelcontextprotocol/sdk/server/stdio Not a pure module */
