// Generated by ReScript, PLEASE EDIT WITH CARE

import * as WebsocketJs from "@modelcontextprotocol/sdk/client/websocket.js";

function make(prim) {
  return new WebsocketJs.WebSocketClientTransport(prim);
}

export {
  make,
}
/* @modelcontextprotocol/sdk/client/websocket.js Not a pure module */
