// Generated by ReScript, PLEASE EDIT WITH CARE

import * as WebStandardStreamableHttp from "@modelcontextprotocol/sdk/server/webStandardStreamableHttp";

function make(prim) {
  return new WebStandardStreamableHttp.WebStandardStreamableHTTPServerTransport();
}

function makeWithOptions(prim) {
  return new WebStandardStreamableHttp.WebStandardStreamableHTTPServerTransport(prim);
}

function handleRequest(prim0, prim1) {
  return prim0.handleRequest(prim1);
}

function handleRequestWithOptions(prim0, prim1, prim2) {
  return prim0.handleRequest(prim1, prim2);
}

function closeSSEStream(prim0, prim1) {
  prim0.closeSSEStream(prim1);
}

function closeStandaloneSSEStream(prim) {
  prim.closeStandaloneSSEStream();
}

export {
  make,
  makeWithOptions,
  handleRequest,
  handleRequestWithOptions,
  closeSSEStream,
  closeStandaloneSSEStream,
}
/* @modelcontextprotocol/sdk/server/webStandardStreamableHttp Not a pure module */
