// Generated by ReScript, PLEASE EDIT WITH CARE

import * as Websocket from "@modelcontextprotocol/sdk/client/websocket";

function make(prim) {
  return new Websocket.WebSocketClientTransport(prim);
}

export {
  make,
}
/* @modelcontextprotocol/sdk/client/websocket Not a pure module */
