// Generated by ReScript, PLEASE EDIT WITH CARE

import * as Primitive_option from "@rescript/runtime/lib/es6/Primitive_option.js";

function make(prim0, prim1, prim2, prim3, prim4, prim5, prim6, prim7, prim8, prim9) {
  let tmp = {};
  if (prim0 !== undefined) {
    tmp.sessionIdGenerator = Primitive_option.valFromOption(prim0);
  }
  if (prim1 !== undefined) {
    tmp.onsessioninitialized = Primitive_option.valFromOption(prim1);
  }
  if (prim2 !== undefined) {
    tmp.onsessionclosed = Primitive_option.valFromOption(prim2);
  }
  if (prim3 !== undefined) {
    tmp.enableJsonResponse = prim3;
  }
  if (prim4 !== undefined) {
    tmp.eventStore = Primitive_option.valFromOption(prim4);
  }
  if (prim5 !== undefined) {
    tmp.allowedHosts = Primitive_option.valFromOption(prim5);
  }
  if (prim6 !== undefined) {
    tmp.allowedOrigins = Primitive_option.valFromOption(prim6);
  }
  if (prim7 !== undefined) {
    tmp.enableDnsRebindingProtection = prim7;
  }
  if (prim8 !== undefined) {
    tmp.retryInterval = prim8;
  }
  return tmp;
}

export {
  make,
}
/* No side effect */
