// Generated by ReScript, PLEASE EDIT WITH CARE

import * as Primitive_option from "@rescript/runtime/lib/es6/Primitive_option.js";

function make(prim0, prim1, prim2) {
  let tmp = {};
  if (prim0 !== undefined) {
    tmp.parsedBody = Primitive_option.valFromOption(prim0);
  }
  if (prim1 !== undefined) {
    tmp.authInfo = Primitive_option.valFromOption(prim1);
  }
  return tmp;
}

export {
  make,
}
/* No side effect */
