// Generated by ReScript, PLEASE EDIT WITH CARE

import * as Stdlib_Option from "@rescript/runtime/lib/es6/Stdlib_Option.js";
import * as Primitive_option from "@rescript/runtime/lib/es6/Primitive_option.js";
import * as McpProtocolVersion from "../core/McpProtocolVersion.mjs";

function make(sessionIdGenerator, onsessioninitialized, onsessionclosed, enableJsonResponse, eventStore, allowedHosts, allowedOrigins, enableDnsRebindingProtection, retryInterval, supportedProtocolVersions, param) {
  let supportedProtocolVersions$1 = Stdlib_Option.map(supportedProtocolVersions, versions => versions.map(McpProtocolVersion.toString));
  let tmp = {};
  if (sessionIdGenerator !== undefined) {
    tmp.sessionIdGenerator = Primitive_option.valFromOption(sessionIdGenerator);
  }
  if (onsessioninitialized !== undefined) {
    tmp.onsessioninitialized = Primitive_option.valFromOption(onsessioninitialized);
  }
  if (onsessionclosed !== undefined) {
    tmp.onsessionclosed = Primitive_option.valFromOption(onsessionclosed);
  }
  if (enableJsonResponse !== undefined) {
    tmp.enableJsonResponse = enableJsonResponse;
  }
  if (eventStore !== undefined) {
    tmp.eventStore = Primitive_option.valFromOption(eventStore);
  }
  if (allowedHosts !== undefined) {
    tmp.allowedHosts = Primitive_option.valFromOption(allowedHosts);
  }
  if (allowedOrigins !== undefined) {
    tmp.allowedOrigins = Primitive_option.valFromOption(allowedOrigins);
  }
  if (enableDnsRebindingProtection !== undefined) {
    tmp.enableDnsRebindingProtection = enableDnsRebindingProtection;
  }
  if (retryInterval !== undefined) {
    tmp.retryInterval = retryInterval;
  }
  if (supportedProtocolVersions$1 !== undefined) {
    tmp.supportedProtocolVersions = Primitive_option.valFromOption(supportedProtocolVersions$1);
  }
  return tmp;
}

export {
  make,
}
/* No side effect */
