// Generated by ReScript, PLEASE EDIT WITH CARE

import * as Primitive_option from "@rescript/runtime/lib/es6/Primitive_option.js";

function make(prim0, prim1, prim2, prim3) {
  let tmp = {};
  if (prim0 !== undefined) {
    tmp.audience = Primitive_option.valFromOption(prim0);
  }
  if (prim1 !== undefined) {
    tmp.priority = prim1;
  }
  if (prim2 !== undefined) {
    tmp.lastModified = prim2;
  }
  return tmp;
}

function audience(prim) {
  return Primitive_option.fromNullable(prim.audience);
}

function priority(prim) {
  return Primitive_option.fromNullable(prim.priority);
}

function lastModified(prim) {
  return Primitive_option.fromNullable(prim.lastModified);
}

export {
  make,
  audience,
  priority,
  lastModified,
}
/* No side effect */
