// Generated by ReScript, PLEASE EDIT WITH CARE

import * as Stdlib_Option from "@rescript/runtime/lib/es6/Stdlib_Option.js";
import * as Primitive_option from "@rescript/runtime/lib/es6/Primitive_option.js";
import * as McpCallToolResult from "./McpCallToolResult.mjs";
import * as McpStandardSchemaInternal from "./McpStandardSchemaInternal.mjs";

function toRaw(result, outputSchema) {
  let structuredContent = Stdlib_Option.map(Primitive_option.fromNullable(result.structuredContent), value => McpStandardSchemaInternal.objectFromValueOrThrow(outputSchema, value));
  let content = result.content;
  let isError = result.isError;
  let tmp = {
    content: content
  };
  if (structuredContent !== undefined) {
    tmp.structuredContent = Primitive_option.valFromOption(structuredContent);
  }
  let tmp$1 = (isError == null) ? undefined : Primitive_option.some(isError);
  if (tmp$1 !== undefined) {
    tmp.isError = tmp$1;
  }
  return tmp;
}

function fromRaw(result, outputSchema) {
  let structuredContent = Stdlib_Option.map(McpCallToolResult.structuredContentRaw(result), raw => McpStandardSchemaInternal.valueFromObjectOrThrow(outputSchema, raw));
  let isError = McpCallToolResult.isErrorRaw(result);
  return McpCallToolResult.make(McpCallToolResult.contentRaw(result), structuredContent, isError, undefined);
}

export {
  toRaw,
  fromRaw,
}
/* McpStandardSchemaInternal Not a pure module */
