// Generated by ReScript, PLEASE EDIT WITH CARE

import * as Primitive_option from "@rescript/runtime/lib/es6/Primitive_option.js";

function makeCompletion(prim0, prim1, prim2, prim3) {
  let tmp = {
    values: prim0
  };
  if (prim1 !== undefined) {
    tmp.total = prim1;
  }
  if (prim2 !== undefined) {
    tmp.hasMore = prim2;
  }
  return tmp;
}

function make(prim0, prim1, prim2) {
  let tmp = {
    completion: prim0
  };
  if (prim1 !== undefined) {
    tmp._meta = Primitive_option.valFromOption(prim1);
  }
  return tmp;
}

function completion(prim) {
  return prim.completion;
}

function meta(prim) {
  return Primitive_option.fromNullable(prim._meta);
}

function values(prim) {
  return prim.values;
}

function total(prim) {
  return Primitive_option.fromNullable(prim.total);
}

function hasMore(prim) {
  return Primitive_option.fromNullable(prim.hasMore);
}

export {
  makeCompletion,
  make,
  completion,
  meta,
  values,
  total,
  hasMore,
}
/* No side effect */
