// Generated by ReScript, PLEASE EDIT WITH CARE

import * as Primitive_option from "@rescript/runtime/lib/es6/Primitive_option.js";

function stopReason(result) {
  let value = result.stopReason;
  if (value == null) {
    return;
  }
  switch (value) {
    case "endTurn" :
      return "endTurn";
    case "maxTokens" :
      return "maxTokens";
    case "stopSequence" :
      return "stopSequence";
    default:
      return {
        NAME: "other",
        VAL: value
      };
  }
}

function make(model, role, content, stopReason, _meta, param) {
  let stopReason$1 = stopReason !== undefined ? (
      typeof stopReason === "object" ? stopReason.VAL : (
          stopReason === "stopSequence" ? "stopSequence" : (
              stopReason === "endTurn" ? "endTurn" : "maxTokens"
            )
        )
    ) : undefined;
  let tmp = {
    model: model,
    role: role,
    content: content
  };
  if (stopReason$1 !== undefined) {
    tmp.stopReason = stopReason$1;
  }
  if (_meta !== undefined) {
    tmp._meta = Primitive_option.valFromOption(_meta);
  }
  return tmp;
}

function model(prim) {
  return prim.model;
}

function role(prim) {
  return prim.role;
}

function content(prim) {
  return prim.content;
}

function meta(prim) {
  return Primitive_option.fromNullable(prim._meta);
}

export {
  make,
  model,
  role,
  content,
  stopReason,
  meta,
}
/* No side effect */
