// Generated by ReScript, PLEASE EDIT WITH CARE

import * as Primitive_option from "@rescript/runtime/lib/es6/Primitive_option.js";

function promptReference(name) {
  return {
    type: "ref/prompt",
    name: name
  };
}

function resourceReference(uri) {
  return {
    type: "ref/resource",
    uri: uri
  };
}

function makeArgument(prim0, prim1, prim2) {
  return {
    name: prim0,
    value: prim1
  };
}

function makeContext(prim0, prim1) {
  let tmp = {};
  if (prim0 !== undefined) {
    tmp.arguments = Primitive_option.valFromOption(prim0);
  }
  return tmp;
}

function makeWithPrompt(prim0, prim1, prim2, prim3, prim4) {
  let tmp = {
    ref: prim0,
    argument: prim1
  };
  if (prim2 !== undefined) {
    tmp.context = Primitive_option.valFromOption(prim2);
  }
  if (prim3 !== undefined) {
    tmp._meta = Primitive_option.valFromOption(prim3);
  }
  return tmp;
}

function makeWithResource(prim0, prim1, prim2, prim3, prim4) {
  let tmp = {
    ref: prim0,
    argument: prim1
  };
  if (prim2 !== undefined) {
    tmp.context = Primitive_option.valFromOption(prim2);
  }
  if (prim3 !== undefined) {
    tmp._meta = Primitive_option.valFromOption(prim3);
  }
  return tmp;
}

function meta(prim) {
  return Primitive_option.fromNullable(prim._meta);
}

function argumentValue(prim) {
  return prim.argument;
}

function contextValue(prim) {
  return Primitive_option.fromNullable(prim.context);
}

function argumentName(prim) {
  return prim.name;
}

function argumentCurrentValue(prim) {
  return prim.value;
}

function contextArguments(prim) {
  return Primitive_option.fromNullable(prim.arguments);
}

export {
  promptReference,
  resourceReference,
  makeArgument,
  makeContext,
  makeWithPrompt,
  makeWithResource,
  meta,
  argumentValue,
  contextValue,
  argumentName,
  argumentCurrentValue,
  contextArguments,
}
/* No side effect */
