// Generated by ReScript, PLEASE EDIT WITH CARE

import * as Stdlib_Option from "@rescript/runtime/lib/es6/Stdlib_Option.js";
import * as Primitive_option from "@rescript/runtime/lib/es6/Primitive_option.js";
import * as McpJsonValueInterop from "./McpJsonValueInterop.mjs";

function make(content, structuredContent, isError, param) {
  return {
    content: content,
    structuredContent: structuredContent,
    isError: isError
  };
}

function makeRaw(content, structuredContent, isError, param) {
  let structuredContent$1 = Stdlib_Option.map(structuredContent, McpJsonValueInterop.dictToUnknown);
  let tmp = {
    content: content
  };
  if (structuredContent$1 !== undefined) {
    tmp.structuredContent = Primitive_option.valFromOption(structuredContent$1);
  }
  if (isError !== undefined) {
    tmp.isError = isError;
  }
  return tmp;
}

function content(result) {
  return result.content;
}

function structuredContent(result) {
  return result.structuredContent;
}

function isError(result) {
  return result.isError;
}

function structuredContentRaw(result) {
  return Stdlib_Option.map(Primitive_option.fromNullable(result.structuredContent), McpJsonValueInterop.dictFromUnknownExn);
}

function contentRaw(prim) {
  return prim.content;
}

function isErrorRaw(prim) {
  return Primitive_option.fromNullable(prim.isError);
}

export {
  make,
  makeRaw,
  content,
  structuredContent,
  isError,
  contentRaw,
  structuredContentRaw,
  isErrorRaw,
}
/* No side effect */
