// Generated by ReScript, PLEASE EDIT WITH CARE

import * as Stdlib_Option from "@rescript/runtime/lib/es6/Stdlib_Option.js";
import * as Primitive_option from "@rescript/runtime/lib/es6/Primitive_option.js";
import * as McpJsonValueInterop from "./McpJsonValueInterop.mjs";

function make(name, argumentValues, task, _meta, param) {
  let argumentValues$1 = Stdlib_Option.map(argumentValues, McpJsonValueInterop.dictToUnknown);
  let tmp = {
    name: name
  };
  if (argumentValues$1 !== undefined) {
    tmp.arguments = Primitive_option.valFromOption(argumentValues$1);
  }
  if (task !== undefined) {
    tmp.task = Primitive_option.valFromOption(task);
  }
  if (_meta !== undefined) {
    tmp._meta = Primitive_option.valFromOption(_meta);
  }
  return tmp;
}

function argumentValues(params) {
  return Stdlib_Option.map(Primitive_option.fromNullable(params.arguments), McpJsonValueInterop.dictFromUnknownExn);
}

function name(prim) {
  return prim.name;
}

function task(prim) {
  return Primitive_option.fromNullable(prim.task);
}

function meta(prim) {
  return Primitive_option.fromNullable(prim._meta);
}

export {
  make,
  name,
  argumentValues,
  task,
  meta,
}
/* No side effect */
