// Generated by ReScript, PLEASE EDIT WITH CARE

import * as Stdlib_JsError from "@rescript/runtime/lib/es6/Stdlib_JsError.js";
import * as Primitive_option from "@rescript/runtime/lib/es6/Primitive_option.js";

function text(text$1) {
  return {
    type: "text",
    text: text$1
  };
}

function image(data, mimeType) {
  return {
    type: "image",
    data: data,
    mimeType: mimeType
  };
}

function audio(data, mimeType) {
  return {
    type: "audio",
    data: data,
    mimeType: mimeType
  };
}

function resourceLink(uri, name, description, mimeType, size) {
  let tmp = {
    type: "resource_link",
    uri: uri,
    name: name
  };
  if (description !== undefined) {
    tmp.description = description;
  }
  if (mimeType !== undefined) {
    tmp.mimeType = mimeType;
  }
  if (size !== undefined) {
    tmp.size = size;
  }
  return tmp;
}

function resource(resource$1) {
  return {
    type: "resource",
    resource: resource$1
  };
}

function kind(block) {
  let value = block.type;
  switch (value) {
    case "audio" :
      return "audio";
    case "image" :
      return "image";
    case "resource" :
      return "resource";
    case "resource_link" :
      return "resourceLink";
    case "text" :
      return "text";
    default:
      return Stdlib_JsError.throwWithMessage("Unsupported MCP content block type: " + value);
  }
}

function textValue(prim) {
  return Primitive_option.fromNullable(prim.text);
}

function data(prim) {
  return Primitive_option.fromNullable(prim.data);
}

function mimeType(prim) {
  return Primitive_option.fromNullable(prim.mimeType);
}

function uri(prim) {
  return Primitive_option.fromNullable(prim.uri);
}

function name(prim) {
  return Primitive_option.fromNullable(prim.name);
}

function description(prim) {
  return Primitive_option.fromNullable(prim.description);
}

function size(prim) {
  return Primitive_option.fromNullable(prim.size);
}

function resourceValue(prim) {
  return Primitive_option.fromNullable(prim.resource);
}

export {
  text,
  image,
  audio,
  resourceLink,
  resource,
  kind,
  textValue,
  data,
  mimeType,
  uri,
  name,
  description,
  size,
  resourceValue,
}
/* No side effect */
