// Generated by ReScript, PLEASE EDIT WITH CARE


function make(prim0, prim1) {
  return {
    task: prim0
  };
}

function task(prim) {
  return prim.task;
}

export {
  make,
  task,
}
/* No side effect */
