// Generated by ReScript, PLEASE EDIT WITH CARE

import * as McpTask from "../shared/McpTask.mjs";
import * as McpTaskStatus from "../shared/McpTaskStatus.mjs";
import * as Primitive_option from "@rescript/runtime/lib/es6/Primitive_option.js";

function make(taskId, status, ttl, createdAt, lastUpdatedAt, pollInterval, statusMessage, param) {
  let tmp = {
    taskId: taskId,
    status: McpTaskStatus.toString(status),
    createdAt: createdAt,
    lastUpdatedAt: lastUpdatedAt
  };
  if (ttl !== undefined) {
    tmp.ttl = ttl;
  }
  if (pollInterval !== undefined) {
    tmp.pollInterval = pollInterval;
  }
  if (statusMessage !== undefined) {
    tmp.statusMessage = statusMessage;
  }
  return tmp;
}

function ofTask(task) {
  let ttl = McpTask.ttl(task);
  let pollInterval = McpTask.pollInterval(task);
  let statusMessage = McpTask.statusMessage(task);
  return make(McpTask.taskId(task), McpTask.status(task), ttl, McpTask.createdAt(task), McpTask.lastUpdatedAt(task), pollInterval, statusMessage, undefined);
}

function status(result) {
  return McpTaskStatus.fromString(result.status);
}

function taskId(prim) {
  return prim.taskId;
}

function ttl(prim) {
  return Primitive_option.fromNullable(prim.ttl);
}

function createdAt(prim) {
  return prim.createdAt;
}

function lastUpdatedAt(prim) {
  return prim.lastUpdatedAt;
}

function pollInterval(prim) {
  return Primitive_option.fromNullable(prim.pollInterval);
}

function statusMessage(prim) {
  return Primitive_option.fromNullable(prim.statusMessage);
}

export {
  make,
  ofTask,
  taskId,
  status,
  ttl,
  createdAt,
  lastUpdatedAt,
  pollInterval,
  statusMessage,
}
/* McpTask Not a pure module */
