// Generated by ReScript, PLEASE EDIT WITH CARE

import * as Stdlib_JsError from "@rescript/runtime/lib/es6/Stdlib_JsError.js";
import * as Primitive_option from "@rescript/runtime/lib/es6/Primitive_option.js";

function includeContext(params) {
  let value = params.includeContext;
  if (value == null) {
    return;
  }
  switch (value) {
    case "allServers" :
      return "allServers";
    case "none" :
      return "none";
    case "thisServer" :
      return "thisServer";
    default:
      return Stdlib_JsError.throwWithMessage("Unsupported MCP includeContext value: " + value);
  }
}

function make(messages, maxTokens, modelPreferences, systemPrompt, includeContext, temperature, stopSequences, metadata, _meta, param) {
  let includeContext$1 = includeContext !== undefined ? (
      includeContext === "allServers" ? "allServers" : (
          includeContext === "thisServer" ? "thisServer" : "none"
        )
    ) : undefined;
  let tmp = {
    messages: messages,
    maxTokens: maxTokens
  };
  if (modelPreferences !== undefined) {
    tmp.modelPreferences = Primitive_option.valFromOption(modelPreferences);
  }
  if (systemPrompt !== undefined) {
    tmp.systemPrompt = systemPrompt;
  }
  if (includeContext$1 !== undefined) {
    tmp.includeContext = includeContext$1;
  }
  if (temperature !== undefined) {
    tmp.temperature = temperature;
  }
  if (stopSequences !== undefined) {
    tmp.stopSequences = Primitive_option.valFromOption(stopSequences);
  }
  if (metadata !== undefined) {
    tmp.metadata = Primitive_option.valFromOption(metadata);
  }
  if (_meta !== undefined) {
    tmp._meta = Primitive_option.valFromOption(_meta);
  }
  return tmp;
}

function messages(prim) {
  return prim.messages;
}

function maxTokens(prim) {
  return prim.maxTokens;
}

function modelPreferences(prim) {
  return Primitive_option.fromNullable(prim.modelPreferences);
}

function systemPrompt(prim) {
  return Primitive_option.fromNullable(prim.systemPrompt);
}

function temperature(prim) {
  return Primitive_option.fromNullable(prim.temperature);
}

function stopSequences(prim) {
  return Primitive_option.fromNullable(prim.stopSequences);
}

function metadata(prim) {
  return Primitive_option.fromNullable(prim.metadata);
}

function meta(prim) {
  return Primitive_option.fromNullable(prim._meta);
}

export {
  make,
  messages,
  maxTokens,
  modelPreferences,
  systemPrompt,
  includeContext,
  temperature,
  stopSequences,
  metadata,
  meta,
}
/* No side effect */
