// Generated by ReScript, PLEASE EDIT WITH CARE

import * as Stdlib_JsError from "@rescript/runtime/lib/es6/Stdlib_JsError.js";
import * as Primitive_option from "@rescript/runtime/lib/es6/Primitive_option.js";

function action(result) {
  let value = result.action;
  switch (value) {
    case "accept" :
      return "accept";
    case "cancel" :
      return "cancel";
    case "decline" :
      return "decline";
    default:
      return Stdlib_JsError.throwWithMessage("Unsupported MCP elicitation action: " + value);
  }
}

function make(action, content, _meta, param) {
  let actionString = action === "accept" ? "accept" : (
      action === "cancel" ? "cancel" : "decline"
    );
  let tmp = {
    action: actionString
  };
  if (content !== undefined) {
    tmp.content = Primitive_option.valFromOption(content);
  }
  if (_meta !== undefined) {
    tmp._meta = Primitive_option.valFromOption(_meta);
  }
  return tmp;
}

function content(prim) {
  return Primitive_option.fromNullable(prim.content);
}

function meta(prim) {
  return Primitive_option.fromNullable(prim._meta);
}

export {
  make,
  action,
  content,
  meta,
}
/* No side effect */
