// Generated by ReScript, PLEASE EDIT WITH CARE

import * as Primitive_option from "@rescript/runtime/lib/es6/Primitive_option.js";

function make(message, elicitationId, url, _meta, param) {
  let tmp = {
    mode: "url",
    message: message,
    elicitationId: elicitationId,
    url: url
  };
  if (_meta !== undefined) {
    tmp._meta = Primitive_option.valFromOption(_meta);
  }
  return tmp;
}

function message(prim) {
  return prim.message;
}

function elicitationId(prim) {
  return prim.elicitationId;
}

function url(prim) {
  return prim.url;
}

function meta(prim) {
  return Primitive_option.fromNullable(prim._meta);
}

export {
  make,
  message,
  elicitationId,
  url,
  meta,
}
/* No side effect */
