// Generated by ReScript, PLEASE EDIT WITH CARE

import * as Primitive_option from "@rescript/runtime/lib/es6/Primitive_option.js";

function make(prim0, prim1) {
  let tmp = {};
  if (prim0 !== undefined) {
    tmp._meta = Primitive_option.valFromOption(prim0);
  }
  return tmp;
}

function meta(prim) {
  return Primitive_option.fromNullable(prim._meta);
}

export {
  make,
  meta,
}
/* No side effect */
