// Generated by ReScript, PLEASE EDIT WITH CARE

import * as Primitive_option from "@rescript/runtime/lib/es6/Primitive_option.js";

function make(prim0, prim1, prim2, prim3) {
  let tmp = {
    message: prim0,
    requestedSchema: prim1
  };
  if (prim2 !== undefined) {
    tmp._meta = Primitive_option.valFromOption(prim2);
  }
  return tmp;
}

function message(prim) {
  return prim.message;
}

function requestedSchema(prim) {
  return prim.requestedSchema;
}

function meta(prim) {
  return Primitive_option.fromNullable(prim._meta);
}

export {
  make,
  message,
  requestedSchema,
  meta,
}
/* No side effect */
