// Generated by ReScript, PLEASE EDIT WITH CARE

import * as Primitive_option from "@rescript/runtime/lib/es6/Primitive_option.js";

function make(prim0, prim1, prim2, prim3) {
  let tmp = {
    name: prim0
  };
  if (prim1 !== undefined) {
    tmp.arguments = Primitive_option.valFromOption(prim1);
  }
  if (prim2 !== undefined) {
    tmp._meta = Primitive_option.valFromOption(prim2);
  }
  return tmp;
}

function name(prim) {
  return prim.name;
}

function argumentValues(prim) {
  return Primitive_option.fromNullable(prim.arguments);
}

function meta(prim) {
  return Primitive_option.fromNullable(prim._meta);
}

export {
  make,
  name,
  argumentValues,
  meta,
}
/* No side effect */
