// Generated by ReScript, PLEASE EDIT WITH CARE

import * as Primitive_option from "@rescript/runtime/lib/es6/Primitive_option.js";

function make(prim0, prim1, prim2) {
  let tmp = {
    messages: prim0
  };
  if (prim1 !== undefined) {
    tmp.description = prim1;
  }
  return tmp;
}

function messages(prim) {
  return prim.messages;
}

function description(prim) {
  return Primitive_option.fromNullable(prim.description);
}

export {
  make,
  messages,
  description,
}
/* No side effect */
