// Generated by ReScript, PLEASE EDIT WITH CARE

import * as Primitive_option from "@rescript/runtime/lib/es6/Primitive_option.js";

function make(prim0, prim1, prim2, prim3, prim4) {
  let tmp = {
    src: prim0
  };
  if (prim1 !== undefined) {
    tmp.mimeType = prim1;
  }
  if (prim2 !== undefined) {
    tmp.sizes = Primitive_option.valFromOption(prim2);
  }
  if (prim3 !== undefined) {
    tmp.theme = Primitive_option.valFromOption(prim3);
  }
  return tmp;
}

function src(prim) {
  return prim.src;
}

function mimeType(prim) {
  return Primitive_option.fromNullable(prim.mimeType);
}

function sizes(prim) {
  return Primitive_option.fromNullable(prim.sizes);
}

function theme(prim) {
  return Primitive_option.fromNullable(prim.theme);
}

export {
  make,
  src,
  mimeType,
  sizes,
  theme,
}
/* No side effect */
