// Generated by ReScript, PLEASE EDIT WITH CARE


function bool(value) {
  return {
    TAG: "Bool",
    _0: value
  };
}

function int(value) {
  return {
    TAG: "Int",
    _0: value
  };
}

function float(value) {
  return {
    TAG: "Float",
    _0: value
  };
}

function string(value) {
  return {
    TAG: "String",
    _0: value
  };
}

function array(value) {
  return {
    TAG: "Array",
    _0: value
  };
}

function object(value) {
  return {
    TAG: "Object",
    _0: value
  };
}

function toJSON(value) {
  if (typeof value !== "object") {
    return null;
  }
  switch (value.TAG) {
    case "Array" :
      return value._0.map(toJSON);
    case "Object" :
      let result = {};
      Object.entries(value._0).forEach(param => {
        result[param[0]] = toJSON(param[1]);
      });
      return result;
    default:
      return value._0;
  }
}

export {
  bool,
  int,
  float,
  string,
  array,
  object,
  toJSON,
}
/* No side effect */
