// Generated by ReScript, PLEASE EDIT WITH CARE

import * as Stdlib_JsError from "@rescript/runtime/lib/es6/Stdlib_JsError.js";

function invalidJsonValue(kind) {
  return Stdlib_JsError.throwWithMessage(`Unsupported MCP JSON value at runtime: ` + kind);
}

function fromUnknownExn(raw) {
  let match = typeof raw;
  if (match === "symbol") {
    return invalidJsonValue("symbol");
  }
  if (match === "boolean") {
    return {
      TAG: "Bool",
      _0: raw
    };
  }
  if (match === "string") {
    return {
      TAG: "String",
      _0: raw
    };
  }
  if (match === "function") {
    return invalidJsonValue("function");
  }
  if (match !== "object") {
    if (match === "undefined") {
      return invalidJsonValue("undefined");
    } else if (match === "number") {
      if (Math.floor(raw) === raw && raw >= -2147483648.0 && raw <= 2147483647.0) {
        return {
          TAG: "Int",
          _0: raw
        };
      } else {
        return {
          TAG: "Float",
          _0: raw
        };
      }
    } else {
      return invalidJsonValue("bigint");
    }
  }
  if (raw == null) {
    return "Null";
  }
  if (Array.isArray(raw)) {
    return {
      TAG: "Array",
      _0: raw.map(fromUnknownExn)
    };
  }
  let result = {};
  Object.entries(raw).forEach(param => {
    result[param[0]] = fromUnknownExn(param[1]);
  });
  return {
    TAG: "Object",
    _0: result
  };
}

function dictFromUnknownExn(raw) {
  let result = {};
  Object.entries(raw).forEach(param => {
    result[param[0]] = fromUnknownExn(param[1]);
  });
  return result;
}

function toUnknown(value) {
  if (typeof value !== "object") {
    return null;
  }
  switch (value.TAG) {
    case "Array" :
      return value._0.map(toUnknown);
    case "Object" :
      return dictToUnknownObject(value._0);
    default:
      return value._0;
  }
}

function dictToUnknownObject(entries) {
  let result = {};
  Object.entries(entries).forEach(param => {
    result[param[0]] = toUnknown(param[1]);
  });
  return result;
}

function dictToUnknown(entries) {
  let result = {};
  Object.entries(entries).forEach(param => {
    result[param[0]] = toUnknown(param[1]);
  });
  return result;
}

export {
  invalidJsonValue,
  fromUnknownExn,
  dictFromUnknownExn,
  toUnknown,
  dictToUnknownObject,
  dictToUnknown,
}
/* No side effect */
