// Generated by ReScript, PLEASE EDIT WITH CARE

import * as Primitive_option from "@rescript/runtime/lib/es6/Primitive_option.js";

function make(prim0, prim1, prim2) {
  let tmp = {
    tasks: prim0
  };
  if (prim1 !== undefined) {
    tmp.nextCursor = prim1;
  }
  return tmp;
}

function tasks(prim) {
  return prim.tasks;
}

function nextCursor(prim) {
  return Primitive_option.fromNullable(prim.nextCursor);
}

export {
  make,
  tasks,
  nextCursor,
}
/* No side effect */
