// Generated by ReScript, PLEASE EDIT WITH CARE

import * as Primitive_option from "@rescript/runtime/lib/es6/Primitive_option.js";

function makeAnnotations(prim0, prim1, prim2, prim3, prim4, prim5) {
  let tmp = {};
  if (prim0 !== undefined) {
    tmp.title = prim0;
  }
  if (prim1 !== undefined) {
    tmp.readOnlyHint = prim1;
  }
  if (prim2 !== undefined) {
    tmp.destructiveHint = prim2;
  }
  if (prim3 !== undefined) {
    tmp.idempotentHint = prim3;
  }
  if (prim4 !== undefined) {
    tmp.openWorldHint = prim4;
  }
  return tmp;
}

function makeExecution(prim0, prim1) {
  let tmp = {};
  if (prim0 !== undefined) {
    tmp.taskSupport = Primitive_option.valFromOption(prim0);
  }
  return tmp;
}

function makeTool(prim0, prim1, prim2, prim3, prim4, prim5, prim6, prim7, prim8, prim9) {
  let tmp = {
    name: prim0,
    inputSchema: prim1
  };
  if (prim2 !== undefined) {
    tmp.description = prim2;
  }
  if (prim3 !== undefined) {
    tmp.outputSchema = Primitive_option.valFromOption(prim3);
  }
  if (prim4 !== undefined) {
    tmp.annotations = Primitive_option.valFromOption(prim4);
  }
  if (prim5 !== undefined) {
    tmp.execution = Primitive_option.valFromOption(prim5);
  }
  if (prim6 !== undefined) {
    tmp._meta = Primitive_option.valFromOption(prim6);
  }
  if (prim7 !== undefined) {
    tmp.icons = Primitive_option.valFromOption(prim7);
  }
  if (prim8 !== undefined) {
    tmp.title = prim8;
  }
  return tmp;
}

function make(prim0, prim1, prim2, prim3) {
  let tmp = {
    tools: prim0
  };
  if (prim1 !== undefined) {
    tmp.nextCursor = prim1;
  }
  if (prim2 !== undefined) {
    tmp._meta = Primitive_option.valFromOption(prim2);
  }
  return tmp;
}

function tools(prim) {
  return prim.tools;
}

function nextCursor(prim) {
  return Primitive_option.fromNullable(prim.nextCursor);
}

function meta(prim) {
  return Primitive_option.fromNullable(prim._meta);
}

function name(prim) {
  return prim.name;
}

function inputSchema(prim) {
  return prim.inputSchema;
}

function description(prim) {
  return Primitive_option.fromNullable(prim.description);
}

function outputSchema(prim) {
  return Primitive_option.fromNullable(prim.outputSchema);
}

function toolAnnotations(prim) {
  return Primitive_option.fromNullable(prim.annotations);
}

function toolExecution(prim) {
  return Primitive_option.fromNullable(prim.execution);
}

function toolMeta(prim) {
  return Primitive_option.fromNullable(prim._meta);
}

function icons(prim) {
  return Primitive_option.fromNullable(prim.icons);
}

function title(prim) {
  return Primitive_option.fromNullable(prim.title);
}

function annotationTitle(prim) {
  return Primitive_option.fromNullable(prim.title);
}

function readOnlyHint(prim) {
  return Primitive_option.fromNullable(prim.readOnlyHint);
}

function destructiveHint(prim) {
  return Primitive_option.fromNullable(prim.destructiveHint);
}

function idempotentHint(prim) {
  return Primitive_option.fromNullable(prim.idempotentHint);
}

function openWorldHint(prim) {
  return Primitive_option.fromNullable(prim.openWorldHint);
}

function taskSupport(prim) {
  return Primitive_option.fromNullable(prim.taskSupport);
}

export {
  makeAnnotations,
  makeExecution,
  makeTool,
  make,
  tools,
  nextCursor,
  meta,
  name,
  inputSchema,
  description,
  outputSchema,
  toolAnnotations,
  toolExecution,
  toolMeta,
  icons,
  title,
  annotationTitle,
  readOnlyHint,
  destructiveHint,
  idempotentHint,
  openWorldHint,
  taskSupport,
}
/* No side effect */
