// Generated by ReScript, PLEASE EDIT WITH CARE

import * as Primitive_option from "@rescript/runtime/lib/es6/Primitive_option.js";

function makeResourceTemplate(prim0, prim1, prim2, prim3, prim4, prim5, prim6, prim7, prim8) {
  let tmp = {
    uriTemplate: prim0,
    name: prim1
  };
  if (prim2 !== undefined) {
    tmp.title = prim2;
  }
  if (prim3 !== undefined) {
    tmp.description = prim3;
  }
  if (prim4 !== undefined) {
    tmp.mimeType = prim4;
  }
  if (prim5 !== undefined) {
    tmp.annotations = Primitive_option.valFromOption(prim5);
  }
  if (prim6 !== undefined) {
    tmp._meta = Primitive_option.valFromOption(prim6);
  }
  if (prim7 !== undefined) {
    tmp.icons = Primitive_option.valFromOption(prim7);
  }
  return tmp;
}

function make(prim0, prim1, prim2, prim3) {
  let tmp = {
    resourceTemplates: prim0
  };
  if (prim1 !== undefined) {
    tmp.nextCursor = prim1;
  }
  if (prim2 !== undefined) {
    tmp._meta = Primitive_option.valFromOption(prim2);
  }
  return tmp;
}

function resourceTemplates(prim) {
  return prim.resourceTemplates;
}

function nextCursor(prim) {
  return Primitive_option.fromNullable(prim.nextCursor);
}

function meta(prim) {
  return Primitive_option.fromNullable(prim._meta);
}

function uriTemplate(prim) {
  return prim.uriTemplate;
}

function name(prim) {
  return prim.name;
}

function title(prim) {
  return Primitive_option.fromNullable(prim.title);
}

function description(prim) {
  return Primitive_option.fromNullable(prim.description);
}

function mimeType(prim) {
  return Primitive_option.fromNullable(prim.mimeType);
}

function annotations(prim) {
  return Primitive_option.fromNullable(prim.annotations);
}

function resourceTemplateMeta(prim) {
  return Primitive_option.fromNullable(prim._meta);
}

function icons(prim) {
  return Primitive_option.fromNullable(prim.icons);
}

export {
  makeResourceTemplate,
  make,
  resourceTemplates,
  nextCursor,
  meta,
  uriTemplate,
  name,
  title,
  description,
  mimeType,
  annotations,
  resourceTemplateMeta,
  icons,
}
/* No side effect */
