// Generated by ReScript, PLEASE EDIT WITH CARE

import * as Primitive_option from "@rescript/runtime/lib/es6/Primitive_option.js";

function make(prim0, prim1, prim2, prim3, prim4) {
  let tmp = {
    level: prim0,
    data: prim1
  };
  if (prim2 !== undefined) {
    tmp.logger = prim2;
  }
  if (prim3 !== undefined) {
    tmp._meta = Primitive_option.valFromOption(prim3);
  }
  return tmp;
}

function level(prim) {
  return prim.level;
}

function data(prim) {
  return prim.data;
}

function logger(prim) {
  return Primitive_option.fromNullable(prim.logger);
}

function meta(prim) {
  return Primitive_option.fromNullable(prim._meta);
}

export {
  make,
  level,
  data,
  logger,
  meta,
}
/* No side effect */
