// Generated by ReScript, PLEASE EDIT WITH CARE

import * as Primitive_option from "@rescript/runtime/lib/es6/Primitive_option.js";

function makePromptArgument(prim0, prim1, prim2, prim3) {
  let tmp = {
    name: prim0
  };
  if (prim1 !== undefined) {
    tmp.description = prim1;
  }
  if (prim2 !== undefined) {
    tmp.required = prim2;
  }
  return tmp;
}

function makePrompt(prim0, prim1, prim2, prim3, prim4, prim5, prim6) {
  let tmp = {
    name: prim0
  };
  if (prim1 !== undefined) {
    tmp.title = prim1;
  }
  if (prim2 !== undefined) {
    tmp.description = prim2;
  }
  if (prim3 !== undefined) {
    tmp.arguments = Primitive_option.valFromOption(prim3);
  }
  if (prim4 !== undefined) {
    tmp._meta = Primitive_option.valFromOption(prim4);
  }
  if (prim5 !== undefined) {
    tmp.icons = Primitive_option.valFromOption(prim5);
  }
  return tmp;
}

function make(prim0, prim1, prim2, prim3) {
  let tmp = {
    prompts: prim0
  };
  if (prim1 !== undefined) {
    tmp.nextCursor = prim1;
  }
  if (prim2 !== undefined) {
    tmp._meta = Primitive_option.valFromOption(prim2);
  }
  return tmp;
}

function prompts(prim) {
  return prim.prompts;
}

function nextCursor(prim) {
  return Primitive_option.fromNullable(prim.nextCursor);
}

function meta(prim) {
  return Primitive_option.fromNullable(prim._meta);
}

function promptName(prim) {
  return prim.name;
}

function promptTitle(prim) {
  return Primitive_option.fromNullable(prim.title);
}

function promptDescription(prim) {
  return Primitive_option.fromNullable(prim.description);
}

function promptArguments(prim) {
  return Primitive_option.fromNullable(prim.arguments);
}

function promptMeta(prim) {
  return Primitive_option.fromNullable(prim._meta);
}

function promptIcons(prim) {
  return Primitive_option.fromNullable(prim.icons);
}

function argumentName(prim) {
  return prim.name;
}

function argumentDescription(prim) {
  return Primitive_option.fromNullable(prim.description);
}

function argumentRequired(prim) {
  return Primitive_option.fromNullable(prim.required);
}

export {
  makePromptArgument,
  makePrompt,
  make,
  prompts,
  nextCursor,
  meta,
  promptName,
  promptTitle,
  promptDescription,
  promptArguments,
  promptMeta,
  promptIcons,
  argumentName,
  argumentDescription,
  argumentRequired,
}
/* No side effect */
