// Generated by ReScript, PLEASE EDIT WITH CARE

import * as Primitive_option from "@rescript/runtime/lib/es6/Primitive_option.js";

function makeRoot(prim0, prim1, prim2, prim3) {
  let tmp = {
    uri: prim0
  };
  if (prim1 !== undefined) {
    tmp.name = prim1;
  }
  if (prim2 !== undefined) {
    tmp._meta = Primitive_option.valFromOption(prim2);
  }
  return tmp;
}

function make(prim0, prim1, prim2) {
  let tmp = {
    roots: prim0
  };
  if (prim1 !== undefined) {
    tmp._meta = Primitive_option.valFromOption(prim1);
  }
  return tmp;
}

function roots(prim) {
  return prim.roots;
}

function meta(prim) {
  return Primitive_option.fromNullable(prim._meta);
}

function uri(prim) {
  return prim.uri;
}

function name(prim) {
  return Primitive_option.fromNullable(prim.name);
}

function rootMeta(prim) {
  return Primitive_option.fromNullable(prim._meta);
}

export {
  makeRoot,
  make,
  roots,
  meta,
  uri,
  name,
  rootMeta,
}
/* No side effect */
