// Generated by ReScript, PLEASE EDIT WITH CARE

import * as Primitive_option from "@rescript/runtime/lib/es6/Primitive_option.js";

function makeResource(prim0, prim1, prim2, prim3, prim4, prim5, prim6, prim7, prim8, prim9) {
  let tmp = {
    uri: prim0,
    name: prim1
  };
  if (prim2 !== undefined) {
    tmp.title = prim2;
  }
  if (prim3 !== undefined) {
    tmp.description = prim3;
  }
  if (prim4 !== undefined) {
    tmp.mimeType = prim4;
  }
  if (prim5 !== undefined) {
    tmp.size = prim5;
  }
  if (prim6 !== undefined) {
    tmp.annotations = Primitive_option.valFromOption(prim6);
  }
  if (prim7 !== undefined) {
    tmp._meta = Primitive_option.valFromOption(prim7);
  }
  if (prim8 !== undefined) {
    tmp.icons = Primitive_option.valFromOption(prim8);
  }
  return tmp;
}

function make(prim0, prim1, prim2, prim3) {
  let tmp = {
    resources: prim0
  };
  if (prim1 !== undefined) {
    tmp.nextCursor = prim1;
  }
  if (prim2 !== undefined) {
    tmp._meta = Primitive_option.valFromOption(prim2);
  }
  return tmp;
}

function resources(prim) {
  return prim.resources;
}

function nextCursor(prim) {
  return Primitive_option.fromNullable(prim.nextCursor);
}

function meta(prim) {
  return Primitive_option.fromNullable(prim._meta);
}

function uri(prim) {
  return prim.uri;
}

function name(prim) {
  return prim.name;
}

function title(prim) {
  return Primitive_option.fromNullable(prim.title);
}

function description(prim) {
  return Primitive_option.fromNullable(prim.description);
}

function mimeType(prim) {
  return Primitive_option.fromNullable(prim.mimeType);
}

function size(prim) {
  return Primitive_option.fromNullable(prim.size);
}

function annotations(prim) {
  return Primitive_option.fromNullable(prim.annotations);
}

function resourceMeta(prim) {
  return Primitive_option.fromNullable(prim._meta);
}

function icons(prim) {
  return Primitive_option.fromNullable(prim.icons);
}

export {
  makeResource,
  make,
  resources,
  nextCursor,
  meta,
  uri,
  name,
  title,
  description,
  mimeType,
  size,
  annotations,
  resourceMeta,
  icons,
}
/* No side effect */
