// Generated by ReScript, PLEASE EDIT WITH CARE

import * as Primitive_option from "@rescript/runtime/lib/es6/Primitive_option.js";

function makeHint(prim0, prim1) {
  let tmp = {};
  if (prim0 !== undefined) {
    tmp.name = prim0;
  }
  return tmp;
}

function make(prim0, prim1, prim2, prim3, prim4) {
  let tmp = {};
  if (prim0 !== undefined) {
    tmp.hints = Primitive_option.valFromOption(prim0);
  }
  if (prim1 !== undefined) {
    tmp.costPriority = prim1;
  }
  if (prim2 !== undefined) {
    tmp.speedPriority = prim2;
  }
  if (prim3 !== undefined) {
    tmp.intelligencePriority = prim3;
  }
  return tmp;
}

function hints(prim) {
  return Primitive_option.fromNullable(prim.hints);
}

function costPriority(prim) {
  return Primitive_option.fromNullable(prim.costPriority);
}

function speedPriority(prim) {
  return Primitive_option.fromNullable(prim.speedPriority);
}

function intelligencePriority(prim) {
  return Primitive_option.fromNullable(prim.intelligencePriority);
}

function hintName(prim) {
  return Primitive_option.fromNullable(prim.name);
}

export {
  makeHint,
  make,
  hints,
  costPriority,
  speedPriority,
  intelligencePriority,
  hintName,
}
/* No side effect */
