// Generated by ReScript, PLEASE EDIT WITH CARE

import * as Stdlib_JsError from "@rescript/runtime/lib/es6/Stdlib_JsError.js";

function requestToString(method_) {
  if (method_ === "resourcesTemplatesList") {
    return "resources/templates/list";
  } else if (method_ === "promptsList") {
    return "prompts/list";
  } else if (method_ === "elicitationCreate") {
    return "elicitation/create";
  } else if (method_ === "tasksResult") {
    return "tasks/result";
  } else if (method_ === "resourcesSubscribe") {
    return "resources/subscribe";
  } else if (method_ === "resourcesUnsubscribe") {
    return "resources/unsubscribe";
  } else if (method_ === "samplingCreateMessage") {
    return "sampling/createMessage";
  } else if (method_ === "promptsGet") {
    return "prompts/get";
  } else if (method_ === "toolsCall") {
    return "tools/call";
  } else if (method_ === "loggingSetLevel") {
    return "logging/setLevel";
  } else if (method_ === "toolsList") {
    return "tools/list";
  } else if (method_ === "resourcesList") {
    return "resources/list";
  } else if (method_ === "tasksCancel") {
    return "tasks/cancel";
  } else if (method_ === "resourcesRead") {
    return "resources/read";
  } else if (method_ === "completionComplete") {
    return "completion/complete";
  } else if (method_ === "rootsList") {
    return "roots/list";
  } else if (method_ === "tasksGet") {
    return "tasks/get";
  } else if (method_ === "tasksList") {
    return "tasks/list";
  } else {
    return "ping";
  }
}

function requestFromString(value) {
  switch (value) {
    case "completion/complete" :
      return "completionComplete";
    case "elicitation/create" :
      return "elicitationCreate";
    case "logging/setLevel" :
      return "loggingSetLevel";
    case "ping" :
      return "ping";
    case "prompts/get" :
      return "promptsGet";
    case "prompts/list" :
      return "promptsList";
    case "resources/list" :
      return "resourcesList";
    case "resources/read" :
      return "resourcesRead";
    case "resources/subscribe" :
      return "resourcesSubscribe";
    case "resources/templates/list" :
      return "resourcesTemplatesList";
    case "resources/unsubscribe" :
      return "resourcesUnsubscribe";
    case "roots/list" :
      return "rootsList";
    case "sampling/createMessage" :
      return "samplingCreateMessage";
    case "tasks/cancel" :
      return "tasksCancel";
    case "tasks/get" :
      return "tasksGet";
    case "tasks/list" :
      return "tasksList";
    case "tasks/result" :
      return "tasksResult";
    case "tools/call" :
      return "toolsCall";
    case "tools/list" :
      return "toolsList";
    default:
      return Stdlib_JsError.throwWithMessage("Unsupported MCP request method: " + value);
  }
}

function notificationToString(method_) {
  if (method_ === "resourcesListChanged") {
    return "notifications/resources/list_changed";
  } else if (method_ === "rootsListChanged") {
    return "notifications/roots/list_changed";
  } else if (method_ === "resourcesUpdated") {
    return "notifications/resources/updated";
  } else if (method_ === "tasksStatus") {
    return "notifications/tasks/status";
  } else if (method_ === "promptsListChanged") {
    return "notifications/prompts/list_changed";
  } else if (method_ === "progress") {
    return "notifications/progress";
  } else if (method_ === "message") {
    return "notifications/message";
  } else if (method_ === "cancelled") {
    return "notifications/cancelled";
  } else if (method_ === "toolsListChanged") {
    return "notifications/tools/list_changed";
  } else if (method_ === "initialized") {
    return "notifications/initialized";
  } else {
    return "notifications/elicitation/complete";
  }
}

function notificationFromString(value) {
  switch (value) {
    case "notifications/cancelled" :
      return "cancelled";
    case "notifications/elicitation/complete" :
      return "elicitationComplete";
    case "notifications/initialized" :
      return "initialized";
    case "notifications/message" :
      return "message";
    case "notifications/progress" :
      return "progress";
    case "notifications/prompts/list_changed" :
      return "promptsListChanged";
    case "notifications/resources/list_changed" :
      return "resourcesListChanged";
    case "notifications/resources/updated" :
      return "resourcesUpdated";
    case "notifications/roots/list_changed" :
      return "rootsListChanged";
    case "notifications/tasks/status" :
      return "tasksStatus";
    case "notifications/tools/list_changed" :
      return "toolsListChanged";
    default:
      return Stdlib_JsError.throwWithMessage("Unsupported MCP notification method: " + value);
  }
}

export {
  requestToString,
  requestFromString,
  notificationToString,
  notificationFromString,
}
/* No side effect */
