// Generated by ReScript, PLEASE EDIT WITH CARE

import * as McpContentBlock from "./McpContentBlock.mjs";

function text(role, text$1) {
  return {
    role: role,
    content: McpContentBlock.text(text$1)
  };
}

function make(prim0, prim1) {
  return {
    role: prim0,
    content: prim1
  };
}

function role(prim) {
  return prim.role;
}

function content(prim) {
  return prim.content;
}

export {
  make,
  text,
  role,
  content,
}
/* No side effect */
