// Generated by ReScript, PLEASE EDIT WITH CARE

import * as Stdlib_JsError from "@rescript/runtime/lib/es6/Stdlib_JsError.js";
import * as Primitive_option from "@rescript/runtime/lib/es6/Primitive_option.js";

function kind(contents) {
  let match = contents.text;
  let match$1 = contents.blob;
  if (match == null) {
    if (match$1 == null) {
      return Stdlib_JsError.throwWithMessage("Unsupported MCP resource contents shape");
    } else {
      return "blob";
    }
  } else if (match$1 == null) {
    return "text";
  } else {
    return Stdlib_JsError.throwWithMessage("Unsupported MCP resource contents shape");
  }
}

function text(prim0, prim1, prim2, prim3) {
  let tmp = {
    uri: prim0,
    text: prim1
  };
  if (prim2 !== undefined) {
    tmp.mimeType = prim2;
  }
  return tmp;
}

function blob(prim0, prim1, prim2, prim3) {
  let tmp = {
    uri: prim0,
    blob: prim1
  };
  if (prim2 !== undefined) {
    tmp.mimeType = prim2;
  }
  return tmp;
}

function uri(prim) {
  return prim.uri;
}

function textValue(prim) {
  return Primitive_option.fromNullable(prim.text);
}

function blobValue(prim) {
  return Primitive_option.fromNullable(prim.blob);
}

function mimeType(prim) {
  return Primitive_option.fromNullable(prim.mimeType);
}

export {
  text,
  blob,
  kind,
  uri,
  textValue,
  blobValue,
  mimeType,
}
/* No side effect */
