// Generated by ReScript, PLEASE EDIT WITH CARE


function make(contents) {
  return {
    contents: contents
  };
}

function contents(prim) {
  return prim.contents;
}

export {
  make,
  contents,
}
/* No side effect */
