// Generated by ReScript, PLEASE EDIT WITH CARE

import * as Primitive_option from "@rescript/runtime/lib/es6/Primitive_option.js";

function make(prim0, prim1, prim2) {
  let tmp = {
    uri: prim0
  };
  if (prim1 !== undefined) {
    tmp._meta = Primitive_option.valFromOption(prim1);
  }
  return tmp;
}

function uri(prim) {
  return prim.uri;
}

function meta(prim) {
  return Primitive_option.fromNullable(prim._meta);
}

export {
  make,
  uri,
  meta,
}
/* No side effect */
