// Generated by ReScript, PLEASE EDIT WITH CARE

import * as Belt_Array from "@rescript/runtime/lib/es6/Belt_Array.js";
import * as S$RescriptSchema from "rescript-schema/src/S.mjs";
import * as S_CoreMjs from "rescript-schema/src/S_Core.mjs";

function jsonString(prim) {
  return prim;
}

let jsonNull = null;

function set(schema, key, value) {
  schema[key] = value;
}

function addDescription(jsonSchema, schema) {
  let description = S$RescriptSchema.description(schema);
  if (description !== undefined) {
    return set(jsonSchema, "description", description);
  }
}

function addStringRefinements(jsonSchema, schema) {
  Belt_Array.forEach(S$RescriptSchema.$$String.refinements(schema), refinement => {
    let match = refinement.kind;
    if (typeof match !== "object") {
      switch (match) {
        case "Email" :
          return set(jsonSchema, "format", "email");
        case "Uuid" :
          return set(jsonSchema, "format", "uuid");
        case "Cuid" :
          return set(jsonSchema, "pattern", "^c[a-z0-9]+$");
        case "Url" :
          return set(jsonSchema, "format", "uri");
        case "Datetime" :
          return set(jsonSchema, "format", "date-time");
      }
    } else {
      switch (match.TAG) {
        case "Min" :
          return set(jsonSchema, "minLength", match.length);
        case "Max" :
          return set(jsonSchema, "maxLength", match.length);
        case "Length" :
          let length = match.length;
          set(jsonSchema, "minLength", length);
          return set(jsonSchema, "maxLength", length);
        case "Pattern" :
          return set(jsonSchema, "pattern", match.re.source);
      }
    }
  });
}

function addIntRefinements(jsonSchema, schema) {
  Belt_Array.forEach(S$RescriptSchema.Int.refinements(schema), refinement => {
    let match = refinement.kind;
    if (typeof match === "object") {
      if (match.TAG === "Min") {
        return set(jsonSchema, "minimum", match.value);
      } else {
        return set(jsonSchema, "maximum", match.value);
      }
    }
    set(jsonSchema, "minimum", 0);
    set(jsonSchema, "maximum", 65535);
  });
}

function addFloatRefinements(jsonSchema, schema) {
  Belt_Array.forEach(S$RescriptSchema.Float.refinements(schema), refinement => {
    let match = refinement.kind;
    if (match.TAG === "Min") {
      return set(jsonSchema, "minimum", match.value);
    } else {
      return set(jsonSchema, "maximum", match.value);
    }
  });
}

function addArrayRefinements(jsonSchema, schema) {
  Belt_Array.forEach(S$RescriptSchema.$$Array.refinements(schema), refinement => {
    let match = refinement.kind;
    switch (match.TAG) {
      case "Min" :
        return set(jsonSchema, "minItems", match.length);
      case "Max" :
        return set(jsonSchema, "maxItems", match.length);
      case "Length" :
        let length = match.length;
        set(jsonSchema, "minItems", length);
        return set(jsonSchema, "maxItems", length);
    }
  });
}

function isOptionalSchema(schema) {
  let match = schema.t;
  if (typeof match !== "object") {
    return false;
  } else {
    return match.TAG === "option";
  }
}

function jsonValueOfLiteral(literal) {
  switch (literal.kind) {
    case "String" :
    case "Number" :
    case "Boolean" :
      return literal.value;
    case "Array" :
      return Belt_Array.map(literal.items, jsonValueOfLiteral);
    case "Dict" :
      let objectSchema = {};
      Belt_Array.forEach(Object.entries(literal.items), param => {
        objectSchema[param[0]] = jsonValueOfLiteral(param[1]);
      });
      return objectSchema;
    default:
      return jsonNull;
  }
}

function jsonSchemaOfLiteral(literal) {
  let schema = {};
  switch (literal.kind) {
    case "String" :
      set(schema, "type", "string");
      set(schema, "const", literal.value);
      break;
    case "Number" :
      let value = literal.value;
      set(schema, "type", Number.isInteger(value) ? "integer" : "number");
      set(schema, "const", value);
      break;
    case "Boolean" :
      set(schema, "type", "boolean");
      set(schema, "const", literal.value);
      break;
    case "Array" :
    case "Dict" :
      set(schema, "const", jsonValueOfLiteral(literal));
      break;
    case "Null" :
      set(schema, "type", "null");
      set(schema, "const", jsonNull);
      break;
  }
  return schema;
}

function nullJsonSchema() {
  let schema = {};
  set(schema, "type", "null");
  return schema;
}

function jsonSchemaOfUnknownSchema(schema) {
  let jsonSchema = {};
  let literal = schema.t;
  if (typeof literal !== "object") {
    switch (literal) {
      case "never" :
        set(jsonSchema, "not", {});
        break;
      case "unknown" :
        break;
      case "string" :
        set(jsonSchema, "type", "string");
        addStringRefinements(jsonSchema, schema);
        break;
      case "int32" :
        set(jsonSchema, "type", "integer");
        addIntRefinements(jsonSchema, schema);
        break;
      case "number" :
        set(jsonSchema, "type", "number");
        addFloatRefinements(jsonSchema, schema);
        break;
      case "bigint" :
        set(jsonSchema, "type", "integer");
        break;
      case "boolean" :
        set(jsonSchema, "type", "boolean");
        break;
    }
  } else {
    switch (literal.TAG) {
      case "literal" :
        let literal$1 = literal._0;
        if (S$RescriptSchema.Literal.isJsonable(literal$1)) {
          Belt_Array.forEach(Object.entries(jsonSchemaOfLiteral(literal$1)), param => {
            jsonSchema[param[0]] = param[1];
          });
        }
        break;
      case "option" :
        Belt_Array.forEach(Object.entries(jsonSchemaOfUnknownSchema(literal._0)), param => {
          jsonSchema[param[0]] = param[1];
        });
        break;
      case "null" :
        set(jsonSchema, "anyOf", [
          jsonSchemaOfUnknownSchema(literal._0),
          nullJsonSchema()
        ]);
        break;
      case "array" :
        set(jsonSchema, "type", "array");
        set(jsonSchema, "items", jsonSchemaOfUnknownSchema(literal._0));
        addArrayRefinements(jsonSchema, schema);
        break;
      case "object" :
        let properties = {};
        let requiredFields = Belt_Array.keepMap(Object.entries(literal.fields), param => {
          let item = param[1];
          let fieldName = param[0];
          properties[fieldName] = jsonSchemaOfUnknownSchema(item.schema);
          if (isOptionalSchema(item.schema)) {
            return;
          } else {
            return fieldName;
          }
        });
        set(jsonSchema, "type", "object");
        set(jsonSchema, "properties", properties);
        if (requiredFields.length !== 0) {
          set(jsonSchema, "required", Belt_Array.map(requiredFields, jsonString));
        }
        if (literal.unknownKeys !== "Strip") {
          set(jsonSchema, "additionalProperties", false);
        }
        break;
      case "tuple" :
        let items = literal.items;
        set(jsonSchema, "type", "array");
        set(jsonSchema, "items", Belt_Array.map(items, item => jsonSchemaOfUnknownSchema(item.schema)));
        let length = items.length;
        set(jsonSchema, "minItems", length);
        set(jsonSchema, "maxItems", length);
        break;
      case "union" :
        set(jsonSchema, "anyOf", Belt_Array.map(literal._0, jsonSchemaOfUnknownSchema));
        break;
      case "dict" :
        set(jsonSchema, "type", "object");
        set(jsonSchema, "additionalProperties", jsonSchemaOfUnknownSchema(literal._0));
        break;
      case "JSON" :
        break;
    }
  }
  addDescription(jsonSchema, schema);
  return jsonSchema;
}

let jsonSchemaOfRescriptSchema = jsonSchemaOfUnknownSchema;

function fromRescriptSchema(schema) {
  let standardProps = S_CoreMjs.standard(schema)["~standard"];
  let jsonSchema = jsonSchemaOfRescriptSchema(schema);
  let jsonSchemaConverter = {
    input: param => jsonSchema,
    output: param => jsonSchema
  };
  let standardSchema = {
    "~standard": Object.assign(standardProps, {
      jsonSchema: jsonSchemaConverter
    })
  };
  standardSchema.__rescriptSchema = schema;
  return standardSchema;
}

let Schema;

export {
  Schema,
  jsonSchemaOfRescriptSchema,
  fromRescriptSchema,
}
/* S-RescriptSchema Not a pure module */
