// Generated by ReScript, PLEASE EDIT WITH CARE

import * as McpSamplingContent from "./McpSamplingContent.mjs";

function text(role, text$1) {
  return {
    role: role,
    content: McpSamplingContent.text(text$1)
  };
}

function content(message) {
  if (Array.isArray(message.content)) {
    return {
      NAME: "multiple",
      VAL: message.content
    };
  } else {
    return {
      NAME: "single",
      VAL: message.content
    };
  }
}

function makeSingle(prim0, prim1, prim2) {
  return {
    role: prim0,
    content: prim1
  };
}

function makeMany(prim0, prim1, prim2) {
  return {
    role: prim0,
    content: prim1
  };
}

function role(prim) {
  return prim.role;
}

export {
  makeSingle,
  makeMany,
  text,
  role,
  content,
}
/* No side effect */
