// Generated by ReScript, PLEASE EDIT WITH CARE

import * as Stdlib_JsError from "@rescript/runtime/lib/es6/Stdlib_JsError.js";
import * as Primitive_option from "@rescript/runtime/lib/es6/Primitive_option.js";

function text(text$1) {
  return {
    type: "text",
    text: text$1
  };
}

function image(data, mimeType) {
  return {
    type: "image",
    data: data,
    mimeType: mimeType
  };
}

function audio(data, mimeType) {
  return {
    type: "audio",
    data: data,
    mimeType: mimeType
  };
}

function kind(content) {
  let value = content.type;
  switch (value) {
    case "audio" :
      return "audio";
    case "image" :
      return "image";
    case "text" :
      return "text";
    default:
      return Stdlib_JsError.throwWithMessage("Unsupported MCP sampling content type: " + value);
  }
}

function textValue(prim) {
  return Primitive_option.fromNullable(prim.text);
}

function data(prim) {
  return Primitive_option.fromNullable(prim.data);
}

function mimeType(prim) {
  return Primitive_option.fromNullable(prim.mimeType);
}

export {
  text,
  image,
  audio,
  kind,
  textValue,
  data,
  mimeType,
}
/* No side effect */
