// Generated by ReScript, PLEASE EDIT WITH CARE

import * as Stdlib_JsError from "@rescript/runtime/lib/es6/Stdlib_JsError.js";
import * as S$RescriptSchema from "rescript-schema/src/S.mjs";
import * as McpJsonValueInterop from "./McpJsonValueInterop.mjs";

function unsupportedStructuredContent(kind) {
  return Stdlib_JsError.throwWithMessage("Structured content must convert to an object, got " + kind);
}

function objectFromValueOrThrow(schema, value) {
  let raw = S$RescriptSchema.reverseConvertOrThrow(value, schema.__rescriptSchema);
  let match = typeof raw;
  if (match === "symbol") {
    return Stdlib_JsError.throwWithMessage("Structured content must convert to an object, got symbol");
  } else if (match === "boolean") {
    return Stdlib_JsError.throwWithMessage("Structured content must convert to an object, got boolean");
  } else if (match === "string") {
    return Stdlib_JsError.throwWithMessage("Structured content must convert to an object, got string");
  } else if (match === "function") {
    return Stdlib_JsError.throwWithMessage("Structured content must convert to an object, got function");
  } else if (match === "object") {
    if (raw == null) {
      return Stdlib_JsError.throwWithMessage("Structured content must convert to an object, got null");
    } else if (Array.isArray(raw)) {
      return Stdlib_JsError.throwWithMessage("Structured content must convert to an object, got array");
    } else {
      return raw;
    }
  } else if (match === "undefined") {
    return Stdlib_JsError.throwWithMessage("Structured content must convert to an object, got undefined");
  } else if (match === "number") {
    return Stdlib_JsError.throwWithMessage("Structured content must convert to an object, got number");
  } else {
    return Stdlib_JsError.throwWithMessage("Structured content must convert to an object, got bigint");
  }
}

function valueFromObjectOrThrow(schema, raw) {
  return S$RescriptSchema.parseOrThrow(McpJsonValueInterop.dictToUnknown(raw), schema.__rescriptSchema);
}

let Schema;

export {
  Schema,
  unsupportedStructuredContent,
  objectFromValueOrThrow,
  valueFromObjectOrThrow,
}
/* S-RescriptSchema Not a pure module */
