// Generated by ReScript, PLEASE EDIT WITH CARE

import * as Stdlib_Option from "@rescript/runtime/lib/es6/Stdlib_Option.js";
import * as Stdlib_JsError from "@rescript/runtime/lib/es6/Stdlib_JsError.js";
import * as Primitive_option from "@rescript/runtime/lib/es6/Primitive_option.js";
import * as McpJsonValueInterop from "./McpJsonValueInterop.mjs";

function make(properties, required, param) {
  let properties$1 = Stdlib_Option.map(properties, McpJsonValueInterop.dictToUnknown);
  let tmp = {
    type: "object"
  };
  if (properties$1 !== undefined) {
    tmp.properties = Primitive_option.valFromOption(properties$1);
  }
  if (required !== undefined) {
    tmp.required = Primitive_option.valFromOption(required);
  }
  return tmp;
}

function kind(schema) {
  let value = schema.type;
  if (value === "object") {
    return "object";
  } else {
    return Stdlib_JsError.throwWithMessage("Unsupported MCP tool schema type: " + value);
  }
}

function properties(schema) {
  return Stdlib_Option.map(Primitive_option.fromNullable(schema.properties), McpJsonValueInterop.dictFromUnknownExn);
}

function required(prim) {
  return Primitive_option.fromNullable(prim.required);
}

export {
  make,
  kind,
  properties,
  required,
}
/* No side effect */
