// Generated by ReScript, PLEASE EDIT WITH CARE

import * as Vitest from "rescript-vitest/src/Vitest.mjs";
import * as McpClient from "../src/client/McpClient.mjs";
import * as TestSupport from "./TestSupport.mjs";
import * as McpJsonValue from "../src/protocol/McpJsonValue.mjs";
import * as Stdlib_Option from "@rescript/runtime/lib/es6/Stdlib_Option.js";
import * as McpTestBindings from "./support/McpTestBindings.mjs";
import * as S$RescriptSchema from "rescript-schema/src/S.mjs";
import * as McpCallToolParams from "../src/protocol/McpCallToolParams.mjs";
import * as McpCallToolResult from "../src/protocol/McpCallToolResult.mjs";
import * as McpStandardSchema from "../src/protocol/McpStandardSchema.mjs";
import * as McpGetPromptParams from "../src/protocol/McpGetPromptParams.mjs";
import * as McpResourceRequestParams from "../src/protocol/McpResourceRequestParams.mjs";

let echoOutputSchema = S$RescriptSchema.schema(s => ({
  echoed: s.m(S$RescriptSchema.string)
}));

let echoOutputStandardSchema = McpStandardSchema.fromRescriptSchema(echoOutputSchema);

Vitest.describe("authoring roundtrip", undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, () => Vitest.testAsync("authors tools, prompts, and resources in ReScript and uses them through the client bindings", undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, async t => {
  let client = McpTestBindings.makeClientWithOptions("stdio-authoring-client", "1.0.0");
  let transport = McpTestBindings.makeStdioClientTransport(TestSupport.execPath, [TestSupport.fixturePath("StdioAuthoringServer.mjs")], TestSupport.cwd);
  await McpTestBindings.connectClientWithTimeout(client, transport, 5000);
  t.expect(McpTestBindings.listedTools(await McpClient.listTools(client))).toEqual([[
      "echo",
      "Echo"
    ]]);
  t.expect(McpTestBindings.listedPrompts(await McpClient.listPrompts(client))).toEqual([[
      "review",
      "Review"
    ]]);
  t.expect(McpTestBindings.listedResources(await McpClient.listResources(client))).toEqual([[
      "config://app",
      "config"
    ]]);
  let toolResult = await McpClient.callTool(client, McpCallToolParams.make("echo", Object.fromEntries([[
      "message",
      McpJsonValue.string("hello")
    ]]), undefined, undefined, undefined), echoOutputStandardSchema);
  t.expect([
    McpTestBindings.toolResultTexts(toolResult),
    Stdlib_Option.map(McpCallToolResult.structuredContent(toolResult), output => output.echoed)
  ]).toEqual([
    ["echo:hello"],
    "hello"
  ]);
  let promptResult = await McpClient.getPrompt(client, McpGetPromptParams.make("review", Object.fromEntries([[
      "topic",
      "bindings"
    ]]), undefined, undefined));
  t.expect([
    McpTestBindings.getPromptResultDescription(promptResult),
    McpTestBindings.promptResultRoles(promptResult),
    McpTestBindings.promptResultTexts(promptResult)
  ]).toEqual([
    "Review prompt",
    ["user"],
    ["Review bindings"]
  ]);
  let resourceResult = await McpClient.readResource(client, McpResourceRequestParams.make("config://app", undefined, undefined));
  t.expect([
    McpTestBindings.readResourceUris(resourceResult),
    McpTestBindings.readResourceTexts(resourceResult)
  ]).toEqual([
    ["config://app"],
    ["{\"ok\":true}"]
  ]);
  return await TestSupport.settle([
    TestSupport.closeIgnore(McpTestBindings.closeClient(client)),
    TestSupport.closeIgnore(McpTestBindings.transportClose(transport))
  ]);
}));

let S;

export {
  S,
  echoOutputSchema,
  echoOutputStandardSchema,
}
/* echoOutputSchema Not a pure module */
