// Generated by ReScript, PLEASE EDIT WITH CARE

import * as Vitest from "rescript-vitest/src/Vitest.mjs";
import * as McpTool from "../src/server/McpTool.mjs";
import * as McpClient from "../src/client/McpClient.mjs";
import * as McpMethod from "../src/protocol/McpMethod.mjs";
import * as McpPrompt from "../src/server/McpPrompt.mjs";
import * as McpServer from "../src/server/McpServer.mjs";
import * as Belt_Array from "@rescript/runtime/lib/es6/Belt_Array.js";
import * as McpResource from "../src/server/McpResource.mjs";
import * as TestSupport from "./TestSupport.mjs";
import * as McpJsonValue from "../src/protocol/McpJsonValue.mjs";
import * as Stdlib_Option from "@rescript/runtime/lib/es6/Stdlib_Option.js";
import * as McpEmptyResult from "../src/protocol/McpEmptyResult.mjs";
import * as McpContentBlock from "../src/protocol/McpContentBlock.mjs";
import * as McpElicitResult from "../src/protocol/McpElicitResult.mjs";
import * as McpTestBindings from "./support/McpTestBindings.mjs";
import * as McpClientOptions from "../src/client/McpClientOptions.mjs";
import * as McpPromptMessage from "../src/protocol/McpPromptMessage.mjs";
import * as McpServerContext from "../src/server/McpServerContext.mjs";
import * as McpServerOptions from "../src/server/McpServerOptions.mjs";
import * as Primitive_option from "@rescript/runtime/lib/es6/Primitive_option.js";
import * as S$RescriptSchema from "rescript-schema/src/S.mjs";
import * as McpCallToolParams from "../src/protocol/McpCallToolParams.mjs";
import * as McpCallToolResult from "../src/protocol/McpCallToolResult.mjs";
import * as McpRequestOptions from "../src/shared/McpRequestOptions.mjs";
import * as McpStandardSchema from "../src/protocol/McpStandardSchema.mjs";
import * as McpGetPromptParams from "../src/protocol/McpGetPromptParams.mjs";
import * as McpGetPromptResult from "../src/protocol/McpGetPromptResult.mjs";
import * as McpSamplingContent from "../src/protocol/McpSamplingContent.mjs";
import * as McpSamplingMessage from "../src/protocol/McpSamplingMessage.mjs";
import * as McpResourceContents from "../src/protocol/McpResourceContents.mjs";
import * as McpResourceTemplate from "../src/server/McpResourceTemplate.mjs";
import * as McpReadResourceResult from "../src/protocol/McpReadResourceResult.mjs";
import * as McpCreateMessageParams from "../src/protocol/McpCreateMessageParams.mjs";
import * as McpCreateMessageResult from "../src/protocol/McpCreateMessageResult.mjs";
import * as McpLoggingMessageParams from "../src/protocol/McpLoggingMessageParams.mjs";
import * as McpResourceRequestParams from "../src/protocol/McpResourceRequestParams.mjs";
import * as McpElicitRequestFormParams from "../src/protocol/McpElicitRequestFormParams.mjs";

let echoArgsSchema = S$RescriptSchema.schema(s => ({
  message: s.m(S$RescriptSchema.string)
}));

let echoOutputSchema = S$RescriptSchema.schema(s => ({
  sampled: s.m(S$RescriptSchema.string),
  code: s.m(S$RescriptSchema.string),
  root: s.m(S$RescriptSchema.string),
  httpRequestMissing: s.m(S$RescriptSchema.string)
}));

let promptArgsSchema = S$RescriptSchema.schema(s => ({
  topic: s.m(S$RescriptSchema.string)
}));

let codeFormSchema = S$RescriptSchema.schema(s => ({
  code: s.m(S$RescriptSchema.string)
}));

function notificationStringField(notification, fieldName) {
  return Stdlib_Option.map(notification.params[fieldName], prim => prim);
}

function variableId(variables) {
  let match = variables["id"];
  if (match !== undefined) {
    if (typeof match === "string") {
      return match;
    } else {
      return Stdlib_Option.getOr(match[0], "missing");
    }
  } else {
    return "missing";
  }
}

Vitest.describe("authoring lifecycle roundtrip", undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, () => Vitest.testAsync("high-level authoring handles register updates, resource templates, and server context request APIs", undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, async t => {
  let clientCapabilities = Object.fromEntries([
    [
      "sampling",
      Object.fromEntries([])
    ],
    [
      "elicitation",
      Object.fromEntries([[
          "form",
          Object.fromEntries([])
        ]])
    ],
    [
      "roots",
      Object.fromEntries([])
    ]
  ]);
  let serverCapabilities = Object.fromEntries([[
      "logging",
      Object.fromEntries([])
    ]]);
  let client = McpClient.makeWithOptions(McpTestBindings.makeImplementation("loopback-authoring-client", "1.0.0"), McpClientOptions.make(clientCapabilities, undefined, undefined, undefined, undefined, undefined, undefined, undefined));
  let server = McpServer.makeWithOptions(McpTestBindings.makeImplementation("loopback-authoring-server", "1.0.0"), McpServerOptions.make(serverCapabilities, "loopback authoring server", undefined, undefined, undefined, undefined, undefined, undefined));
  let pair = McpTestBindings.makeLoopbackTransportPair("authoring-loopback");
  let serverTransport = pair.server;
  let clientTransport = pair.client;
  let timeoutOptions = McpRequestOptions.make(undefined, undefined, 5000, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined);
  let loggingNotifications = {
    contents: []
  };
  let echoSchema = McpStandardSchema.fromRescriptSchema(echoArgsSchema);
  let echoOutputStandardSchema = McpStandardSchema.fromRescriptSchema(echoOutputSchema);
  let promptSchema = McpStandardSchema.fromRescriptSchema(promptArgsSchema);
  McpTestBindings.setClientRequestHandlerRaw(client, "samplingCreateMessage", async (_request, _ctx) => McpCreateMessageResult.make("sample-model", "assistant", McpSamplingContent.text("sampled-from-client"), undefined, undefined, undefined));
  McpTestBindings.setClientRequestHandlerRaw(client, "elicitationCreate", async (_request, _ctx) => McpElicitResult.make("accept", Object.fromEntries([[
      "code",
      "42"
    ]]), undefined, undefined));
  McpTestBindings.setClientRequestHandlerRaw(client, "rootsList", async (_request, _ctx) => Object.fromEntries([[
      "roots",
      [Object.fromEntries([[
            "uri",
            "file:///workspace"
          ]])]
    ]]));
  McpClient.setNotificationHandlerRaw(client, "message", async notification => {
    loggingNotifications.contents = Belt_Array.concatMany([
      loggingNotifications.contents,
      [Stdlib_Option.getOr(notificationStringField(notification, "level"), "missing-level") + `:` + Stdlib_Option.getOr(notificationStringField(notification, "data"), "missing-data")]
    ]);
  });
  let toolHandle = McpServer.registerTool(server, "echo", McpTool.makeConfig("Echo", undefined, Primitive_option.some(echoSchema), echoOutputStandardSchema, undefined, undefined, undefined), async (args, ctx) => {
    let sampling = await McpServerContext.requestSamplingWithOptions(ctx, McpCreateMessageParams.make([McpSamplingMessage.text("user", "tool request")], 32, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined), timeoutOptions);
    let elicitation = await McpServerContext.elicitFormInputWithOptions(ctx, McpElicitRequestFormParams.make("Provide a code", McpStandardSchema.jsonSchemaOfRescriptSchema(codeFormSchema), undefined, undefined), timeoutOptions);
    let roots = await McpServerContext.sendRelatedRequestRawWithOptions(ctx, "rootsList", Object.fromEntries([]), timeoutOptions);
    let sampledText = Stdlib_Option.getOr(McpSamplingContent.textValue(McpCreateMessageResult.content(sampling)), "missing");
    let code = Stdlib_Option.getOr(Stdlib_Option.flatMap(McpElicitResult.content(elicitation), content => Stdlib_Option.map(content["code"], prim => prim)), "missing");
    let root = Stdlib_Option.getOr(roots.roots.map(root => root.uri)[0], "missing-root");
    await McpServerContext.sendRelatedNotificationRaw(ctx, "message", Object.fromEntries([
      [
        "level",
        "notice"
      ],
      [
        "data",
        "tool-related"
      ]
    ]));
    await McpServerContext.log(ctx, "info", "tool invoked");
    await McpServerContext.logWithLogger(ctx, "info", "tool invoked with logger", "authoring-loopback");
    let match = McpServerContext.httpRequest(ctx);
    return McpCallToolResult.make([McpContentBlock.text(args.message + `|` + sampledText + `|` + code + `|` + root + `|` + McpMethod.requestToString(McpServerContext.requestMethod(ctx)))], {
      sampled: sampledText,
      code: code,
      root: root,
      httpRequestMissing: match !== undefined ? "false" : "true"
    }, undefined, undefined);
  });
  let pingHandle = McpServer.registerToolRaw0(server, "ping", McpTool.makeRawConfig("Ping", undefined, undefined, undefined, undefined, undefined), async _ctx => McpCallToolResult.makeRaw([McpContentBlock.text("pong")], undefined, undefined, undefined));
  let promptHandle = McpServer.registerPrompt(server, "review", McpPrompt.makeConfig("Review", undefined, Primitive_option.some(promptSchema), undefined, undefined), async (args, _ctx) => McpGetPromptResult.make([McpPromptMessage.text("user", "Review " + args.topic)], "Review prompt", undefined));
  let welcomeHandle = McpServer.registerPrompt0(server, "welcome", McpPrompt.makeConfig("Welcome", undefined, undefined, undefined, undefined), async _ctx => McpGetPromptResult.make([McpPromptMessage.text("assistant", "Welcome")], undefined, undefined));
  let resourceHandle = McpServer.registerResource(server, "config", "config://app", McpResource.makeConfig("Config", undefined, "application/json", undefined, undefined, undefined, undefined), async (uri, _ctx) => McpReadResourceResult.make([McpResourceContents.text(uri.href, "{\"ok\":true}", undefined, undefined)]));
  let resourceTemplate = McpResourceTemplate.make("memo://{id}", McpResourceTemplate.makeCallbacks(undefined, Object.fromEntries([[
      "id",
      async (_value, _context) => [
        "alpha",
        "beta"
      ]
    ]]), undefined));
  let resourceTemplateHandle = McpServer.registerResourceTemplate(server, "memo", resourceTemplate, McpResource.makeConfig("Memo", undefined, "text/plain", undefined, undefined, undefined, undefined), async (uri, variables, _ctx) => McpReadResourceResult.make([McpResourceContents.text(uri.href, variableId(variables), undefined, undefined)]));
  await McpServer.connect(server, serverTransport);
  await McpClient.connectWithOptions(client, clientTransport, timeoutOptions);
  t.expect(McpServer.isConnected(server)).toEqual(true);
  t.expect(McpTestBindings.listedTools(await McpClient.listTools(client))).toEqual([
    [
      "echo",
      "Echo"
    ],
    [
      "ping",
      "Ping"
    ]
  ]);
  t.expect(McpTestBindings.listedPrompts(await McpClient.listPrompts(client))).toEqual([
    [
      "review",
      "Review"
    ],
    [
      "welcome",
      "Welcome"
    ]
  ]);
  t.expect(McpTestBindings.listedResources(await McpClient.listResources(client))).toEqual([[
      "config://app",
      "config"
    ]]);
  t.expect(McpTestBindings.listedResourceTemplates(await McpClient.listResourceTemplates(client))).toEqual([[
      "memo://{id}",
      "memo"
    ]]);
  t.expect(McpEmptyResult.meta(await McpClient.ping(client))).toEqual(undefined);
  let initialToolResult = await McpClient.callTool(client, McpCallToolParams.make("echo", Object.fromEntries([[
      "message",
      McpJsonValue.string("hello")
    ]]), undefined, undefined, undefined), echoOutputStandardSchema);
  t.expect([
    McpTestBindings.toolResultTexts(initialToolResult),
    Stdlib_Option.map(McpCallToolResult.structuredContent(initialToolResult), output => output.sampled),
    Stdlib_Option.map(McpCallToolResult.structuredContent(initialToolResult), output => output.code),
    Stdlib_Option.map(McpCallToolResult.structuredContent(initialToolResult), output => output.root),
    Stdlib_Option.map(McpCallToolResult.structuredContent(initialToolResult), output => output.httpRequestMissing)
  ]).toEqual([
    ["hello|sampled-from-client|42|file:///workspace|tools/call"],
    "sampled-from-client",
    "42",
    "file:///workspace",
    "true"
  ]);
  t.expect(loggingNotifications.contents).toEqual([
    "notice:tool-related",
    "info:tool invoked",
    "info:tool invoked with logger"
  ]);
  t.expect(McpTestBindings.toolResultTextsRaw(await McpClient.callToolRaw(client, McpCallToolParams.make("ping", undefined, undefined, undefined, undefined)))).toEqual(["pong"]);
  t.expect(McpTestBindings.promptResultTexts(await McpClient.getPrompt(client, McpGetPromptParams.make("welcome", undefined, undefined, undefined)))).toEqual(["Welcome"]);
  McpTool.update(toolHandle, McpTool.makeUpdates(undefined, "Echo v2", undefined, undefined, echoOutputStandardSchema, undefined, undefined, async (args, _ctx) => McpCallToolResult.make([McpContentBlock.text("updated:" + args.message)], {
    sampled: args.message,
    code: "updated",
    root: "updated",
    httpRequestMissing: "true"
  }, undefined, undefined), undefined, undefined));
  McpTool.updateRaw0(pingHandle, McpTool.makeRawUpdates0(undefined, "Ping v2", undefined, undefined, undefined, async _ctx => McpCallToolResult.makeRaw([McpContentBlock.text("pong-v2")], undefined, undefined, undefined), undefined, undefined));
  McpPrompt.update(promptHandle, McpPrompt.makeUpdates(undefined, "Review v2", undefined, undefined, undefined, async (args, _ctx) => McpGetPromptResult.make([McpPromptMessage.text("assistant", "Updated " + args.topic)], "Updated prompt", undefined), undefined, undefined));
  McpPrompt.update0(welcomeHandle, McpPrompt.makeUpdates0(undefined, "Welcome v2", undefined, undefined, async _ctx => McpGetPromptResult.make([McpPromptMessage.text("assistant", "Welcome v2")], undefined, undefined), undefined, undefined));
  McpResource.update(resourceHandle, McpResource.makeUpdates("settings", undefined, "config://settings", undefined, async (uri, _ctx) => McpReadResourceResult.make([McpResourceContents.text(uri.href, "{\"version\":2}", undefined, undefined)]), undefined, undefined));
  let updatedTemplate = McpResourceTemplate.make("memo://{id}/v2", McpResourceTemplate.makeCallbacks(undefined, undefined, undefined));
  McpResourceTemplate.update(resourceTemplateHandle, McpResourceTemplate.makeUpdates("memo-v2", undefined, Primitive_option.some(updatedTemplate), undefined, async (uri, variables, _ctx) => McpReadResourceResult.make([McpResourceContents.text(uri.href, "updated:" + variableId(variables), undefined, undefined)]), undefined, undefined));
  await McpServer.sendLoggingMessage(server, McpLoggingMessageParams.make("info", "updated", undefined, undefined, undefined));
  await McpServer.sendLoggingMessageWithSessionId(server, McpLoggingMessageParams.make("info", "updated-session", undefined, undefined, undefined), "loopback-session");
  McpServer.sendResourceListChanged(server);
  McpServer.sendToolListChanged(server);
  McpServer.sendPromptListChanged(server);
  t.expect(loggingNotifications.contents).toEqual([
    "notice:tool-related",
    "info:tool invoked",
    "info:tool invoked with logger",
    "info:updated",
    "info:updated-session"
  ]);
  t.expect(McpTestBindings.listedTools(await McpClient.listTools(client))).toEqual([
    [
      "echo",
      "Echo v2"
    ],
    [
      "ping",
      "Ping v2"
    ]
  ]);
  t.expect(McpTestBindings.listedPrompts(await McpClient.listPrompts(client))).toEqual([
    [
      "review",
      "Review v2"
    ],
    [
      "welcome",
      "Welcome v2"
    ]
  ]);
  t.expect(McpTestBindings.listedResources(await McpClient.listResources(client))).toEqual([[
      "config://settings",
      "settings"
    ]]);
  t.expect(McpTestBindings.listedResourceTemplates(await McpClient.listResourceTemplates(client))).toEqual([[
      "memo://{id}/v2",
      "memo-v2"
    ]]);
  t.expect(McpTestBindings.toolResultTexts(await McpClient.callTool(client, McpCallToolParams.make("echo", Object.fromEntries([[
      "message",
      McpJsonValue.string("later")
    ]]), undefined, undefined, undefined), echoOutputStandardSchema))).toEqual(["updated:later"]);
  t.expect(McpTestBindings.toolResultTextsRaw(await McpClient.callToolRaw(client, McpCallToolParams.make("ping", undefined, undefined, undefined, undefined)))).toEqual(["pong-v2"]);
  let updatedPrompt = await McpClient.getPrompt(client, McpGetPromptParams.make("review", Object.fromEntries([[
      "topic",
      "bindings"
    ]]), undefined, undefined));
  t.expect([
    McpTestBindings.getPromptResultDescription(updatedPrompt),
    McpTestBindings.promptResultRoles(updatedPrompt),
    McpTestBindings.promptResultTexts(updatedPrompt)
  ]).toEqual([
    "Updated prompt",
    ["assistant"],
    ["Updated bindings"]
  ]);
  t.expect(McpTestBindings.promptResultTexts(await McpClient.getPrompt(client, McpGetPromptParams.make("welcome", undefined, undefined, undefined)))).toEqual(["Welcome v2"]);
  let updatedResource = await McpClient.readResource(client, McpResourceRequestParams.make("config://settings", undefined, undefined));
  t.expect([
    McpTestBindings.readResourceUris(updatedResource),
    McpTestBindings.readResourceTexts(updatedResource)
  ]).toEqual([
    ["config://settings"],
    ["{\"version\":2}"]
  ]);
  let updatedTemplateResource = await McpClient.readResource(client, McpResourceRequestParams.make("memo://alpha/v2", undefined, undefined));
  t.expect(McpTestBindings.readResourceTexts(updatedTemplateResource)).toEqual(["updated:alpha"]);
  return await TestSupport.settle([
    (async () => McpClient.removeNotificationHandlerRaw(client, "message"))(),
    TestSupport.closeIgnore(McpTestBindings.closeClient(client)),
    TestSupport.closeIgnore(McpTestBindings.closeMcpServer(server)),
    TestSupport.closeIgnore(McpTestBindings.transportClose(serverTransport)),
    TestSupport.closeIgnore(McpTestBindings.transportClose(clientTransport))
  ]);
}));

let S;

let Json;

export {
  S,
  Json,
  echoArgsSchema,
  echoOutputSchema,
  promptArgsSchema,
  codeFormSchema,
  notificationStringField,
  variableId,
}
/* echoArgsSchema Not a pure module */
