// Generated by ReScript, PLEASE EDIT WITH CARE

import * as Vitest from "rescript-vitest/src/Vitest.mjs";
import * as TestSupport from "./TestSupport.mjs";
import * as McpTestBindings from "./support/McpTestBindings.mjs";

Vitest.describe("binding surface", undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, () => Vitest.testAsync("constructs the package modules and exercises no-op lifecycle paths", undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, async t => {
  McpTestBindings.makeLowLevelServer("surface-low-level", "1.0.0");
  let mcpServer = McpTestBindings.makeMcpServerWithInstructions("surface-mcp", "1.0.0", "surface instructions");
  let client = McpTestBindings.makeClientWithOptions("surface-client", "1.0.0");
  let webTransport = McpTestBindings.makeWebStandardTransport();
  let nodeTransport = McpTestBindings.makeNodeStreamableHttpTransport();
  let httpClientTransport = McpTestBindings.makeStreamableHttpClientTransport("http://127.0.0.1:65535/mcp");
  let stdioTransport = McpTestBindings.makeStdioClientTransport(TestSupport.execPath, [TestSupport.fixturePath("StdioPingServer.mjs")], TestSupport.cwd);
  t.expect([
    McpTestBindings.mcpServerIsConnected(mcpServer),
    McpTestBindings.clientServerVersion(client),
    McpTestBindings.clientInstructions(client),
    McpTestBindings.transportSessionId(webTransport),
    McpTestBindings.httpClientProtocolVersion(httpClientTransport),
    McpTestBindings.stdioClientPid(stdioTransport),
    McpTestBindings.stdioClientStderr(stdioTransport)
  ]).toEqual([
    false,
    undefined,
    undefined,
    undefined,
    undefined,
    undefined,
    undefined
  ]);
  await McpTestBindings.transportStart(webTransport);
  await McpTestBindings.transportClose(webTransport);
  await McpTestBindings.transportStart(nodeTransport);
  await McpTestBindings.transportClose(nodeTransport);
  let mcpServerTransport = McpTestBindings.makeWebStandardTransport();
  await McpTestBindings.connectMcpServer(mcpServer, mcpServerTransport);
  t.expect(McpTestBindings.mcpServerIsConnected(mcpServer)).toBe(true);
  return await TestSupport.settle([
    TestSupport.closeIgnore(McpTestBindings.closeMcpServer(mcpServer)),
    TestSupport.closeIgnore(McpTestBindings.transportClose(mcpServerTransport)),
    TestSupport.closeIgnore(McpTestBindings.closeClient(client)),
    TestSupport.closeIgnore(McpTestBindings.transportClose(stdioTransport))
  ]);
}));

/*  Not a pure module */
