// Generated by ReScript, PLEASE EDIT WITH CARE

import * as Vitest from "rescript-vitest/src/Vitest.mjs";
import * as McpTool from "../src/server/McpTool.mjs";
import * as McpTypes from "../src/core/McpTypes.mjs";
import * as McpPrompt from "../src/server/McpPrompt.mjs";
import * as McpAuthInfo from "../src/core/McpAuthInfo.mjs";
import * as McpResource from "../src/server/McpResource.mjs";
import * as TestSupport from "./TestSupport.mjs";
import * as McpTaskStore from "../src/shared/McpTaskStore.mjs";
import * as Stdlib_Option from "@rescript/runtime/lib/es6/Stdlib_Option.js";
import * as Webapi__Fetch from "rescript-webapi/src/Webapi/Webapi__Fetch.mjs";
import * as McpRequestInfo from "../src/core/McpRequestInfo.mjs";
import * as McpTaskContext from "../src/shared/McpTaskContext.mjs";
import * as McpUriTemplate from "../src/shared/McpUriTemplate.mjs";
import * as Stdlib_JsError from "@rescript/runtime/lib/es6/Stdlib_JsError.js";
import * as McpTestBindings from "./support/McpTestBindings.mjs";
import * as McpClientOptions from "../src/client/McpClientOptions.mjs";
import * as McpServerContext from "../src/server/McpServerContext.mjs";
import * as McpServerOptions from "../src/server/McpServerOptions.mjs";
import * as Primitive_object from "@rescript/runtime/lib/es6/Primitive_object.js";
import * as Primitive_option from "@rescript/runtime/lib/es6/Primitive_option.js";
import * as S$RescriptSchema from "rescript-schema/src/S.mjs";
import * as McpRequestOptions from "../src/shared/McpRequestOptions.mjs";
import * as McpStandardSchema from "../src/protocol/McpStandardSchema.mjs";
import * as McpListTasksResult from "../src/protocol/McpListTasksResult.mjs";
import * as McpProtocolOptions from "../src/shared/McpProtocolOptions.mjs";
import * as McpProtocolVersion from "../src/core/McpProtocolVersion.mjs";
import * as McpMessageExtraInfo from "../src/core/McpMessageExtraInfo.mjs";
import * as McpResourceTemplate from "../src/server/McpResourceTemplate.mjs";
import * as McpTaskMessageQueue from "../src/shared/McpTaskMessageQueue.mjs";
import * as McpSSEClientTransport from "../src/transports/McpSSEClientTransport.mjs";
import * as McpTaskCreationParams from "../src/shared/McpTaskCreationParams.mjs";
import * as McpTaskManagerOptions from "../src/shared/McpTaskManagerOptions.mjs";
import * as McpListResourcesResult from "../src/protocol/McpListResourcesResult.mjs";
import * as McpRelatedTaskMetadata from "../src/shared/McpRelatedTaskMetadata.mjs";
import * as McpRequestHandlerExtra from "../src/core/McpRequestHandlerExtra.mjs";
import * as McpLoggingMessageParams from "../src/protocol/McpLoggingMessageParams.mjs";
import * as McpStdioServerTransport from "../src/transports/McpStdioServerTransport.mjs";
import * as McpTransportSendOptions from "../src/shared/McpTransportSendOptions.mjs";
import * as McpResourceUpdatedParams from "../src/protocol/McpResourceUpdatedParams.mjs";
import * as McpStdioServerParameters from "../src/transports/McpStdioServerParameters.mjs";
import * as McpSSEClientTransportOptions from "../src/transports/McpSSEClientTransportOptions.mjs";
import * as McpStreamableHttpClientTransport from "../src/transports/McpStreamableHttpClientTransport.mjs";
import * as McpStreamableHttpReconnectionOptions from "../src/transports/McpStreamableHttpReconnectionOptions.mjs";
import * as McpStreamableHttpClientTransportOptions from "../src/transports/McpStreamableHttpClientTransportOptions.mjs";
import * as McpNodeStreamableHttpServerTransportOptions from "../src/transports/McpNodeStreamableHttpServerTransportOptions.mjs";
import * as McpWebStandardStreamableHttpHandleRequestOptions from "../src/transports/McpWebStandardStreamableHttpHandleRequestOptions.mjs";
import * as McpWebStandardStreamableHttpServerTransportOptions from "../src/transports/McpWebStandardStreamableHttpServerTransportOptions.mjs";

function stringField(value, field) {
  return Stdlib_Option.map(value[field], prim => prim);
}

function boolField(value, field) {
  return Stdlib_Option.map(value[field], prim => prim);
}

function intField(value, field) {
  return Stdlib_Option.map(value[field], prim => prim);
}

function floatField(value, field) {
  return Stdlib_Option.map(value[field], prim => prim);
}

Vitest.describe("binding object surface", undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, () => {
  Vitest.testAsync("constructs public option and config objects through the package entrypoints", undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, async t => {
    let annotations = Object.fromEntries([[
        "audience",
        "public"
      ]]);
    let meta = Object.fromEntries([[
        "_owner",
        "binding-test"
      ]]);
    let capabilities = Object.fromEntries([[
        "roots",
        "enabled"
      ]]);
    let taskStore = McpTaskStore.makeInMemory();
    let taskQueue = McpTaskMessageQueue.makeInMemory();
    let tasks = McpTaskManagerOptions.make(Primitive_option.some(taskStore), Primitive_option.some(taskQueue), 1000, 8, undefined);
    let taskParams = McpTaskCreationParams.make(5000, 250, undefined);
    let relatedTask = McpRelatedTaskMetadata.make("task-42", undefined);
    let env = Object.fromEntries([[
        "PATH",
        "/usr/bin"
      ]]);
    let relatedRequestId = "request-42";
    let validator = "validator";
    let authProvider = "authProvider";
    let fetch = "fetch";
    let eventStore = "eventStore";
    let requestInit = Webapi__Fetch.RequestInit.make("Post", undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined);
    let stringSchema = McpStandardSchema.fromRescriptSchema(S$RescriptSchema.string);
    let intSchema = McpStandardSchema.fromRescriptSchema(S$RescriptSchema.int);
    let toolConfig = McpTool.makeConfig("Echo", "Echoes text", Primitive_option.some(stringSchema), stringSchema, annotations, meta, undefined);
    let promptConfig = McpPrompt.makeConfig("Summarize", "Summarizes input", Primitive_option.some(stringSchema), meta, undefined);
    let resourceConfig = McpResource.makeConfig("Guide", "Binding guide", "text/plain", 64.0, annotations, meta, undefined);
    let protocolOptions = McpProtocolOptions.make([McpTypes.latestProtocolVersion], true, ["notifications/message"], Primitive_option.some(tasks), undefined);
    let requestOptions = McpRequestOptions.make(param => {}, "signal", 1000, true, 2000, Primitive_option.some(taskParams), Primitive_option.some(relatedTask), Primitive_option.some(relatedRequestId), "resume-1", param => {}, undefined);
    let transportSendOptions = McpTransportSendOptions.make(Primitive_option.some(relatedRequestId), "resume-1", param => {}, undefined);
    let loggingMessageParams = McpLoggingMessageParams.make("info", "log-data", "binding-test", meta, undefined);
    let resourceUpdatedParams = McpResourceUpdatedParams.make("config://app", meta, undefined);
    let serverOptions = McpServerOptions.make(capabilities, "Server instructions", Primitive_option.some(validator), [McpTypes.latestProtocolVersion], true, ["notifications/resources/list_changed"], Primitive_option.some(tasks), undefined);
    let clientOptions = McpClientOptions.make(capabilities, Primitive_option.some(validator), "listChanged", [McpTypes.latestProtocolVersion], true, ["notifications/tools/list_changed"], Primitive_option.some(tasks), undefined);
    let reconnectionOptions = McpStreamableHttpReconnectionOptions.make(5000, 250, 2.0, 3);
    let streamableHttpClientOptions = McpStreamableHttpClientTransportOptions.make(Primitive_option.some(authProvider), Primitive_option.some(requestInit), Primitive_option.some(fetch), Primitive_option.some(reconnectionOptions), "scheduler", "session-1", McpTypes.latestProtocolVersion, undefined);
    let sseClientOptions = McpSSEClientTransportOptions.make(Primitive_option.some(authProvider), undefined, Primitive_option.some(requestInit), Primitive_option.some(fetch), undefined);
    let webTransportOptions = McpWebStandardStreamableHttpServerTransportOptions.make(() => "session-1", param => {}, param => {}, true, Primitive_option.some(eventStore), ["127.0.0.1"], ["http://example.test"], true, 250, [McpTypes.latestProtocolVersion], undefined);
    McpNodeStreamableHttpServerTransportOptions.make(() => "session-1", param => {}, param => {}, true, Primitive_option.some(eventStore), ["127.0.0.1"], ["http://example.test"], true, 250, [McpTypes.latestProtocolVersion], undefined);
    McpWebStandardStreamableHttpHandleRequestOptions.make(Primitive_option.some(Object.fromEntries([[
        "jsonrpc",
        "2.0"
      ]])), Primitive_option.some(McpAuthInfo.make("secret", "client-1", ["read"], undefined, undefined, undefined)), undefined);
    let stdioServerParameters = McpStdioServerParameters.make("node", ["server.mjs"], env, "pipe", TestSupport.cwd);
    let httpClientTransport = McpStreamableHttpClientTransport.makeWithOptions(new URL("http://127.0.0.1:65535/mcp"), streamableHttpClientOptions);
    let sseClientTransport = McpSSEClientTransport.makeWithOptions(new URL("http://127.0.0.1:65535/sse"), sseClientOptions);
    McpStdioServerTransport.makeWithStreams(TestSupport.process.stdin, TestSupport.process.stdout);
    let uriTemplate = McpUriTemplate.make("memo://{id}");
    let queryTemplate = McpUriTemplate.make("memo://{id}{?tag}");
    let resourceTemplate = McpResourceTemplate.makeWithUriTemplate(uriTemplate, McpResourceTemplate.makeCallbacks(_ctx => Promise.resolve(McpListResourcesResult.make([McpListResourcesResult.makeResource("memo://alpha", "memo-alpha", undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined)], undefined, undefined, undefined)), Object.fromEntries([[
        "id",
        (_value, _context) => Promise.resolve([
          "alpha",
          "beta"
        ])
      ]]), undefined));
    McpStreamableHttpClientTransport.setProtocolVersion(httpClientTransport, McpTypes.latestProtocolVersion);
    McpSSEClientTransport.setProtocolVersion(sseClientTransport, McpTypes.latestProtocolVersion);
    let callback = McpResourceTemplate.completeCallback(resourceTemplate, "id");
    let resourceTemplateCompletions = callback !== undefined ? await callback("a", undefined) : [];
    let callback$1 = McpResourceTemplate.listCallback(resourceTemplate);
    let listedTemplateResources = callback$1 !== undefined ? await callback$1({
        mcpReq: {
          id: 0,
          method: "resources/list",
          signal: new AbortController().signal
        }
      }) : McpListResourcesResult.make([], undefined, undefined, undefined);
    let variables = McpUriTemplate.match(uriTemplate, "memo://alpha");
    let matchedTemplateId;
    if (variables !== undefined) {
      let match = variables["id"];
      matchedTemplateId = typeof match === "string" ? match : undefined;
    } else {
      matchedTemplateId = undefined;
    }
    let expandedTemplateUri = McpUriTemplate.expand(uriTemplate, Object.fromEntries([[
        "id",
        "alpha"
      ]]));
    let expandedQueryTemplateUri = McpUriTemplate.expand(queryTemplate, Object.fromEntries([
      [
        "id",
        "alpha"
      ],
      [
        "tag",
        [
          "x",
          "y"
        ]
      ]
    ]));
    return t.expect([
      stringField(toolConfig, "title"),
      stringField(promptConfig, "title"),
      stringField(resourceConfig, "mimeType"),
      floatField(resourceConfig, "size"),
      stringField(serverOptions, "instructions"),
      boolField(serverOptions, "enforceStrictCapabilities"),
      boolField(clientOptions, "enforceStrictCapabilities"),
      intField(requestOptions, "timeout"),
      stringField(transportSendOptions, "resumptionToken"),
      McpLoggingMessageParams.level(loggingMessageParams),
      McpLoggingMessageParams.data(loggingMessageParams),
      McpLoggingMessageParams.logger(loggingMessageParams),
      Stdlib_Option.flatMap(McpLoggingMessageParams.meta(loggingMessageParams), meta => Stdlib_Option.map(meta["_owner"], prim => prim)),
      McpResourceUpdatedParams.uri(resourceUpdatedParams),
      Stdlib_Option.flatMap(McpResourceUpdatedParams.meta(resourceUpdatedParams), meta => Stdlib_Option.map(meta["_owner"], prim => prim)),
      boolField(protocolOptions, "enforceStrictCapabilities"),
      stringField(streamableHttpClientOptions, "sessionId"),
      stringField(streamableHttpClientOptions, "protocolVersion"),
      boolField(webTransportOptions, "enableJsonResponse"),
      intField(webTransportOptions, "retryInterval"),
      stringField(stdioServerParameters, "command"),
      intField(requestOptions, "maxTotalTimeout"),
      requestOptions["task"] !== undefined,
      Stdlib_Option.flatMap(requestOptions["relatedTask"], value => Stdlib_Option.map(value["taskId"], prim => prim)),
      McpStreamableHttpClientTransport.protocolVersion(httpClientTransport),
      McpUriTemplate.variableNames(uriTemplate),
      expandedTemplateUri,
      matchedTemplateId,
      expandedQueryTemplateUri,
      McpUriTemplate.toString(McpResourceTemplate.uriTemplate(resourceTemplate)),
      McpTestBindings.listedResources(listedTemplateResources),
      resourceTemplateCompletions,
      intSchema["~standard"] !== undefined
    ]).toEqual([
      "Echo",
      "Summarize",
      "text/plain",
      64.0,
      "Server instructions",
      true,
      true,
      1000,
      "resume-1",
      "info",
      "log-data",
      "binding-test",
      "binding-test",
      "config://app",
      "binding-test",
      true,
      "session-1",
      McpProtocolVersion.toString(McpTypes.latestProtocolVersion),
      true,
      250,
      "node",
      2000,
      true,
      "task-42",
      McpTypes.latestProtocolVersion,
      ["id"],
      "memo://alpha",
      "alpha",
      "memo://alpha?tag=x,y",
      "memo://{id}",
      [[
          "memo://alpha",
          "memo-alpha"
        ]],
      [
        "alpha",
        "beta"
      ],
      true
    ]);
  });
  Vitest.test("reads public context objects and dispatches registered binding controls", undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, t => {
    let closeCount = {
      contents: 0
    };
    let standaloneCloseCount = {
      contents: 0
    };
    let request = new Request("https://example.test/request");
    let abortController = new AbortController();
    let requestInfo = McpRequestInfo.make(Object.fromEntries([[
        "accept",
        "application/json"
      ]]), Primitive_option.some(new URL("https://example.test/request")), undefined);
    let authInfo = McpAuthInfo.make("secret", "client-1", [
      "read",
      "write"
    ], 12345.0, Primitive_option.some(new URL("https://example.test/resource")), Object.fromEntries([[
        "tenant",
        "acme"
      ]]));
    let messageExtra = McpMessageExtraInfo.make(Primitive_option.some(request), Primitive_option.some(authInfo), () => {
      closeCount.contents = closeCount.contents + 1 | 0;
    }, () => {
      standaloneCloseCount.contents = standaloneCloseCount.contents + 1 | 0;
    }, undefined);
    let requestHandlerExtra = {
      authInfo: authInfo,
      sessionId: "session-1",
      requestId: 7,
      taskId: "task-1",
      requestInfo: requestInfo,
      closeSSEStream: () => {
        closeCount.contents = closeCount.contents + 1 | 0;
      },
      closeStandaloneSSEStream: () => {
        standaloneCloseCount.contents = standaloneCloseCount.contents + 1 | 0;
      }
    };
    let requestTaskStore = {
      createTask: _params => Promise.resolve(Stdlib_JsError.throwWithMessage("unused")),
      getTask: _taskId => Promise.resolve(Stdlib_JsError.throwWithMessage("unused")),
      storeTaskResult: (_taskId, _status, _result) => Promise.resolve(),
      getTaskResult: _taskId => Promise.resolve("unused"),
      updateTaskStatus: (_taskId, _status, _statusMessage) => Promise.resolve(),
      listTasks: _cursor => Promise.resolve(McpListTasksResult.make([], undefined, undefined))
    };
    let serverContext = {
      sessionId: "session-1",
      mcpReq: {
        id: 7,
        method: "tools/call",
        _meta: Object.fromEntries([[
            "origin",
            "binding-test"
          ]]),
        signal: abortController.signal
      },
      http: {
        authInfo: authInfo,
        req: request,
        closeSSE: () => {
          closeCount.contents = closeCount.contents + 1 | 0;
        },
        closeStandaloneSSE: () => {
          standaloneCloseCount.contents = standaloneCloseCount.contents + 1 | 0;
        }
      },
      task: {
        id: "task-1",
        store: requestTaskStore,
        requestedTtl: 60000
      }
    };
    let toolCounts = {
      contents: [
        0,
        0,
        0,
        0
      ]
    };
    let promptCounts = {
      contents: [
        0,
        0,
        0,
        0
      ]
    };
    let resourceCounts = {
      contents: [
        0,
        0,
        0,
        0
      ]
    };
    let resourceTemplateCounts = {
      contents: [
        0,
        0,
        0,
        0
      ]
    };
    let toolRegistered = {
      enable: () => {
        let match = toolCounts.contents;
        toolCounts.contents = [
          match[0] + 1 | 0,
          match[1],
          match[2],
          match[3]
        ];
      },
      disable: () => {
        let match = toolCounts.contents;
        toolCounts.contents = [
          match[0],
          match[1] + 1 | 0,
          match[2],
          match[3]
        ];
      },
      update: param => {
        let match = toolCounts.contents;
        toolCounts.contents = [
          match[0],
          match[1],
          match[2] + 1 | 0,
          match[3]
        ];
      },
      remove: () => {
        let match = toolCounts.contents;
        toolCounts.contents = [
          match[0],
          match[1],
          match[2],
          match[3] + 1 | 0
        ];
      }
    };
    let promptRegistered = {
      enable: () => {
        let match = promptCounts.contents;
        promptCounts.contents = [
          match[0] + 1 | 0,
          match[1],
          match[2],
          match[3]
        ];
      },
      disable: () => {
        let match = promptCounts.contents;
        promptCounts.contents = [
          match[0],
          match[1] + 1 | 0,
          match[2],
          match[3]
        ];
      },
      update: param => {
        let match = promptCounts.contents;
        promptCounts.contents = [
          match[0],
          match[1],
          match[2] + 1 | 0,
          match[3]
        ];
      },
      remove: () => {
        let match = promptCounts.contents;
        promptCounts.contents = [
          match[0],
          match[1],
          match[2],
          match[3] + 1 | 0
        ];
      }
    };
    let resourceRegistered = {
      enable: () => {
        let match = resourceCounts.contents;
        resourceCounts.contents = [
          match[0] + 1 | 0,
          match[1],
          match[2],
          match[3]
        ];
      },
      disable: () => {
        let match = resourceCounts.contents;
        resourceCounts.contents = [
          match[0],
          match[1] + 1 | 0,
          match[2],
          match[3]
        ];
      },
      update: param => {
        let match = resourceCounts.contents;
        resourceCounts.contents = [
          match[0],
          match[1],
          match[2] + 1 | 0,
          match[3]
        ];
      },
      remove: () => {
        let match = resourceCounts.contents;
        resourceCounts.contents = [
          match[0],
          match[1],
          match[2],
          match[3] + 1 | 0
        ];
      }
    };
    let resourceTemplateRegistered = {
      enable: () => {
        let match = resourceTemplateCounts.contents;
        resourceTemplateCounts.contents = [
          match[0] + 1 | 0,
          match[1],
          match[2],
          match[3]
        ];
      },
      disable: () => {
        let match = resourceTemplateCounts.contents;
        resourceTemplateCounts.contents = [
          match[0],
          match[1] + 1 | 0,
          match[2],
          match[3]
        ];
      },
      update: param => {
        let match = resourceTemplateCounts.contents;
        resourceTemplateCounts.contents = [
          match[0],
          match[1],
          match[2] + 1 | 0,
          match[3]
        ];
      },
      remove: () => {
        let match = resourceTemplateCounts.contents;
        resourceTemplateCounts.contents = [
          match[0],
          match[1],
          match[2],
          match[3] + 1 | 0
        ];
      }
    };
    let close = McpMessageExtraInfo.closeSSEStream(messageExtra);
    if (close !== undefined) {
      close();
    }
    let close$1 = McpRequestHandlerExtra.closeStandaloneSSEStream(requestHandlerExtra);
    if (close$1 !== undefined) {
      close$1();
    }
    McpTool.enable(toolRegistered);
    McpTool.disable(toolRegistered);
    McpTool.update(toolRegistered, McpTool.makeUpdates(undefined, "Updated echo", undefined, undefined, McpStandardSchema.fromRescriptSchema(S$RescriptSchema.string), undefined, undefined, undefined, undefined, undefined));
    McpTool.remove(toolRegistered);
    McpPrompt.enable(promptRegistered);
    McpPrompt.disable(promptRegistered);
    McpPrompt.update(promptRegistered, McpPrompt.makeUpdates(undefined, "Updated prompt", undefined, undefined, undefined, undefined, undefined, undefined));
    McpPrompt.remove(promptRegistered);
    McpResource.enable(resourceRegistered);
    McpResource.disable(resourceRegistered);
    McpResource.update(resourceRegistered, McpResource.makeUpdates(undefined, "Updated resource", undefined, undefined, undefined, undefined, undefined));
    McpResource.remove(resourceRegistered);
    McpResourceTemplate.enable(resourceTemplateRegistered);
    McpResourceTemplate.disable(resourceTemplateRegistered);
    McpResourceTemplate.update(resourceTemplateRegistered, McpResourceTemplate.makeUpdates(undefined, "Updated template", undefined, undefined, undefined, true, undefined));
    McpResourceTemplate.remove(resourceTemplateRegistered);
    let close$2 = McpServerContext.closeSSE(serverContext);
    if (close$2 !== undefined) {
      close$2();
    }
    let close$3 = McpServerContext.closeStandaloneSSE(serverContext);
    if (close$3 !== undefined) {
      close$3();
    }
    t.expect([
      stringField(authInfo, "token"),
      stringField(authInfo, "clientId"),
      floatField(authInfo, "expiresAt"),
      Stdlib_Option.map(McpRequestInfo.headers(requestInfo)["accept"], prim => prim),
      Stdlib_Option.map(McpRequestInfo.url(requestInfo), prim => prim.href),
      Primitive_object.equal(McpMessageExtraInfo.request(messageExtra), Primitive_option.some(request)),
      Primitive_object.equal(McpMessageExtraInfo.authInfo(messageExtra), Primitive_option.some(authInfo)),
      McpRequestHandlerExtra.sessionId(requestHandlerExtra),
      McpRequestHandlerExtra.requestId(requestHandlerExtra),
      McpRequestHandlerExtra.taskId(requestHandlerExtra),
      McpServerContext.sessionId(serverContext),
      Stdlib_Option.flatMap(McpServerContext.task(serverContext), McpTaskContext.id),
      Stdlib_Option.flatMap(McpServerContext.task(serverContext), McpTaskContext.requestedTtl),
      McpServerContext.requestId(serverContext),
      McpServerContext.requestMethod(serverContext),
      Stdlib_Option.flatMap(McpServerContext.requestMeta(serverContext), meta => Stdlib_Option.map(meta["origin"], prim => prim)),
      Primitive_object.equal(McpServerContext.requestSignal(serverContext), abortController.signal),
      Primitive_object.equal(McpServerContext.httpAuthInfo(serverContext), Primitive_option.some(authInfo)),
      Primitive_object.equal(McpServerContext.httpRequest(serverContext), Primitive_option.some(request)),
      closeCount.contents,
      standaloneCloseCount.contents,
      toolCounts.contents,
      promptCounts.contents,
      resourceCounts.contents,
      resourceTemplateCounts.contents
    ]).toEqual([
      "secret",
      "client-1",
      12345.0,
      "application/json",
      "https://example.test/request",
      true,
      true,
      "session-1",
      7,
      "task-1",
      "session-1",
      "task-1",
      60000,
      7,
      "toolsCall",
      "binding-test",
      true,
      true,
      true,
      2,
      2,
      [
        1,
        1,
        1,
        1
      ],
      [
        1,
        1,
        1,
        1
      ],
      [
        1,
        1,
        1,
        1
      ],
      [
        1,
        1,
        1,
        1
      ]
    ]);
  });
});

let S;

let stringValueSchema = S$RescriptSchema.string;

let intValueSchema = S$RescriptSchema.int;

export {
  S,
  stringValueSchema,
  intValueSchema,
  stringField,
  boolField,
  intField,
  floatField,
}
/*  Not a pure module */
