// Generated by ReScript, PLEASE EDIT WITH CARE

import * as Vitest from "rescript-vitest/src/Vitest.mjs";
import * as McpIcon from "../src/protocol/McpIcon.mjs";
import * as McpClient from "../src/client/McpClient.mjs";
import * as TestSupport from "./TestSupport.mjs";
import * as McpJsonValue from "../src/protocol/McpJsonValue.mjs";
import * as McpToolSchema from "../src/protocol/McpToolSchema.mjs";
import * as Stdlib_Option from "@rescript/runtime/lib/es6/Stdlib_Option.js";
import * as McpAnnotations from "../src/protocol/McpAnnotations.mjs";
import * as McpEmptyResult from "../src/protocol/McpEmptyResult.mjs";
import * as McpContentBlock from "../src/protocol/McpContentBlock.mjs";
import * as McpTestBindings from "./support/McpTestBindings.mjs";
import * as Vitest_Matchers from "rescript-vitest/src/Vitest_Matchers.mjs";
import * as McpPromptMessage from "../src/protocol/McpPromptMessage.mjs";
import * as Primitive_option from "@rescript/runtime/lib/es6/Primitive_option.js";
import * as S$RescriptSchema from "rescript-schema/src/S.mjs";
import * as McpCallToolParams from "../src/protocol/McpCallToolParams.mjs";
import * as McpCallToolResult from "../src/protocol/McpCallToolResult.mjs";
import * as McpCompleteParams from "../src/protocol/McpCompleteParams.mjs";
import * as McpCompleteResult from "../src/protocol/McpCompleteResult.mjs";
import * as McpLowLevelServer from "../src/server/McpLowLevelServer.mjs";
import * as McpRequestOptions from "../src/shared/McpRequestOptions.mjs";
import * as McpStandardSchema from "../src/protocol/McpStandardSchema.mjs";
import * as McpGetPromptParams from "../src/protocol/McpGetPromptParams.mjs";
import * as McpGetPromptResult from "../src/protocol/McpGetPromptResult.mjs";
import * as McpListRootsParams from "../src/protocol/McpListRootsParams.mjs";
import * as McpListRootsResult from "../src/protocol/McpListRootsResult.mjs";
import * as McpListToolsResult from "../src/protocol/McpListToolsResult.mjs";
import * as McpPaginatedParams from "../src/protocol/McpPaginatedParams.mjs";
import * as McpResourceContents from "../src/protocol/McpResourceContents.mjs";
import * as McpListPromptsResult from "../src/protocol/McpListPromptsResult.mjs";
import * as McpReadResourceResult from "../src/protocol/McpReadResourceResult.mjs";
import * as McpListResourcesResult from "../src/protocol/McpListResourcesResult.mjs";
import * as McpResourceRequestParams from "../src/protocol/McpResourceRequestParams.mjs";
import * as McpListResourceTemplatesResult from "../src/protocol/McpListResourceTemplatesResult.mjs";

let echoOutputSchema = S$RescriptSchema.schema(s => ({
  echoed: s.m(S$RescriptSchema.string)
}));

function promptTopic(request) {
  return Stdlib_Option.getOr(Stdlib_Option.flatMap(Primitive_option.fromNullable(request.params.arguments), args => args["topic"]), "missing");
}

function toolMessage(request) {
  return Stdlib_Option.getOr(Stdlib_Option.flatMap(Primitive_option.fromNullable(request.params.arguments), args => Stdlib_Option.map(args["message"], prim => prim)), "missing");
}

function resolveUnknown(value) {
  return Promise.resolve(value);
}

let echoOutputStandardSchema = McpStandardSchema.fromRescriptSchema(echoOutputSchema);

Vitest.describe("client protocol roundtrip", undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, () => {
  Vitest.testAsync("typed client params and results roundtrip through the installed low-level protocol surface", undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, async t => {
    let server = McpTestBindings.makeLowLevelServer("client-protocol-server", "1.0.0");
    let serverCapabilities = Object.fromEntries([
      [
        "logging",
        Object.fromEntries([])
      ],
      [
        "completions",
        Object.fromEntries([])
      ],
      [
        "prompts",
        Object.fromEntries([])
      ],
      [
        "resources",
        Object.fromEntries([
          [
            "subscribe",
            true
          ],
          [
            "listChanged",
            true
          ]
        ])
      ],
      [
        "tools",
        Object.fromEntries([[
            "listChanged",
            true
          ]])
      ]
    ]);
    McpLowLevelServer.registerCapabilities(server, serverCapabilities);
    McpLowLevelServer.setRequestHandlerRaw(server, "completionComplete", (request, _extra) => Promise.resolve(McpCompleteResult.make(McpCompleteResult.makeCompletion([
      request.params.argument.value,
      request.params.argument.name
    ], 2.0, false, undefined), undefined, undefined)));
    McpLowLevelServer.setRequestHandlerRaw(server, "loggingSetLevel", (_request, _extra) => Promise.resolve(McpEmptyResult.make(undefined, undefined)));
    McpLowLevelServer.setRequestHandlerRaw(server, "promptsGet", (request, _extra) => Promise.resolve(McpGetPromptResult.make([McpPromptMessage.text("assistant", `prompt:` + request.params.name + `:` + promptTopic(request))], `prompt:` + request.params.name, undefined)));
    McpLowLevelServer.setRequestHandlerRaw(server, "promptsList", (request, _extra) => Promise.resolve(McpListPromptsResult.make([McpListPromptsResult.makePrompt("review", Stdlib_Option.getOr(Primitive_option.fromNullable(request.params.cursor), "no-cursor"), "Prompt description", [McpListPromptsResult.makePromptArgument("topic", "Prompt topic", true, undefined)], undefined, [McpIcon.make("prompt.svg", undefined, undefined, "light", undefined)], undefined)], "prompts-next", undefined, undefined)));
    McpLowLevelServer.setRequestHandlerRaw(server, "resourcesList", (request, _extra) => Promise.resolve(McpListResourcesResult.make([McpListResourcesResult.makeResource("config://typed", "typed-resource", Stdlib_Option.getOr(Primitive_option.fromNullable(request.params.cursor), "no-cursor"), "Resource description", "application/json", 32.0, Primitive_option.some(McpAnnotations.make(["assistant"], 0.75, "2026-04-23T00:00:00Z", undefined)), undefined, [McpIcon.make("resource.svg", undefined, undefined, "dark", undefined)], undefined)], "resources-next", undefined, undefined)));
    McpLowLevelServer.setRequestHandlerRaw(server, "resourcesTemplatesList", (request, _extra) => Promise.resolve(McpListResourceTemplatesResult.make([McpListResourceTemplatesResult.makeResourceTemplate("memo://{id}", "memo", Stdlib_Option.getOr(Primitive_option.fromNullable(request.params.cursor), "no-cursor"), "Template description", "text/plain", Primitive_option.some(McpAnnotations.make(["user"], 0.5, "2026-04-23T00:00:00Z", undefined)), undefined, [McpIcon.make("template.svg", undefined, undefined, "light", undefined)], undefined)], "templates-next", undefined, undefined)));
    McpLowLevelServer.setRequestHandlerRaw(server, "resourcesRead", (request, _extra) => Promise.resolve(McpReadResourceResult.make([McpResourceContents.text(request.params.uri, `read:` + request.params.uri, undefined, undefined)])));
    McpLowLevelServer.setRequestHandlerRaw(server, "resourcesSubscribe", (_request, _extra) => Promise.resolve(McpEmptyResult.make(undefined, undefined)));
    McpLowLevelServer.setRequestHandlerRaw(server, "resourcesUnsubscribe", (_request, _extra) => Promise.resolve(McpEmptyResult.make(undefined, undefined)));
    McpLowLevelServer.setRequestHandlerRaw(server, "toolsCall", (request, _extra) => Promise.resolve(McpCallToolResult.makeRaw([McpContentBlock.text(`tool:` + request.params.name + `:` + toolMessage(request))], Object.fromEntries([[
        "echoed",
        McpJsonValue.string(toolMessage(request))
      ]]), undefined, undefined)));
    McpLowLevelServer.setRequestHandlerRaw(server, "toolsList", (request, _extra) => Promise.resolve(McpListToolsResult.make([McpListToolsResult.makeTool("echo", McpToolSchema.make(Object.fromEntries([[
          "message",
          McpJsonValue.object(Object.fromEntries([[
              "type",
              McpJsonValue.string("string")
            ]]))
        ]]), ["message"], undefined), "Tool description", Primitive_option.some(McpToolSchema.make(Object.fromEntries([[
          "echoed",
          McpJsonValue.object(Object.fromEntries([[
              "type",
              McpJsonValue.string("string")
            ]]))
        ]]), ["echoed"], undefined)), Primitive_option.some(McpListToolsResult.makeAnnotations("Tool title", true, false, true, false, undefined)), Primitive_option.some(McpListToolsResult.makeExecution("optional", undefined)), undefined, [McpIcon.make("tool.svg", undefined, undefined, "dark", undefined)], Stdlib_Option.getOr(Primitive_option.fromNullable(request.params.cursor), "no-cursor"), undefined)], "tools-next", undefined, undefined)));
    let client = McpTestBindings.makeClient("client-protocol-client", "1.0.0");
    McpTestBindings.registerClientCapabilities(client, Object.fromEntries([[
        "roots",
        Object.fromEntries([])
      ]]));
    McpTestBindings.setClientRequestHandlerRaw(client, "rootsList", (_request, _ctx) => Promise.resolve(McpListRootsResult.make([McpListRootsResult.makeRoot("file:///workspace", "workspace", undefined, undefined)], undefined, undefined)));
    let pair = McpTestBindings.makeLoopbackTransportPair("client-protocol");
    let serverTransport = pair.server;
    let clientTransport = pair.client;
    let timeoutOptions = McpRequestOptions.make(undefined, undefined, 5000, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined);
    await McpLowLevelServer.connect(server, serverTransport);
    await McpClient.connectWithOptions(client, clientTransport, timeoutOptions);
    let pingResult = await McpClient.pingWithOptions(client, timeoutOptions);
    let completionResult = await McpClient.completeWithOptions(client, McpCompleteParams.makeWithPrompt(McpCompleteParams.promptReference("review"), McpCompleteParams.makeArgument("topic", "bindings", undefined), undefined, undefined, undefined), timeoutOptions);
    let loggingResult = await McpClient.setLoggingLevelWithOptions(client, "warning", timeoutOptions);
    let promptResult = await McpClient.getPromptWithOptions(client, McpGetPromptParams.make("review", Object.fromEntries([[
        "topic",
        "bindings"
      ]]), undefined, undefined), timeoutOptions);
    let promptsResult = await McpClient.listPromptsWithParamsAndOptions(client, McpPaginatedParams.make("prompt-cursor", undefined, undefined), timeoutOptions);
    let resourcesResult = await McpClient.listResourcesWithParamsAndOptions(client, McpPaginatedParams.make("resource-cursor", undefined, undefined), timeoutOptions);
    let resourceTemplatesResult = await McpClient.listResourceTemplatesWithParamsAndOptions(client, McpPaginatedParams.make("template-cursor", undefined, undefined), timeoutOptions);
    let readResult = await McpClient.readResourceWithOptions(client, McpResourceRequestParams.make("config://typed", undefined, undefined), timeoutOptions);
    let subscribeResult = await McpClient.subscribeResource(client, McpResourceRequestParams.make("config://typed", undefined, undefined));
    let unsubscribeResult = await McpClient.unsubscribeResourceWithOptions(client, McpResourceRequestParams.make("config://typed", undefined, undefined), timeoutOptions);
    let toolResult = await McpClient.callToolWithOptions(client, McpCallToolParams.make("echo", Object.fromEntries([[
        "message",
        McpJsonValue.string("hello")
      ]]), undefined, undefined, undefined), echoOutputStandardSchema, timeoutOptions);
    let toolsResult = await McpClient.listToolsWithParamsAndOptions(client, McpPaginatedParams.make("tool-cursor", undefined, undefined), timeoutOptions);
    let rootsResult = await McpLowLevelServer.listRootsWithParamsAndOptions(server, McpListRootsParams.make(undefined, undefined), timeoutOptions);
    let listedPrompt = Stdlib_Option.getOrThrow(McpListPromptsResult.prompts(promptsResult)[0], undefined);
    let listedPromptArgument = Stdlib_Option.getOrThrow(Stdlib_Option.getOrThrow(McpListPromptsResult.promptArguments(listedPrompt), undefined)[0], undefined);
    let listedResource = Stdlib_Option.getOrThrow(McpListResourcesResult.resources(resourcesResult)[0], undefined);
    let listedTemplate = Stdlib_Option.getOrThrow(McpListResourceTemplatesResult.resourceTemplates(resourceTemplatesResult)[0], undefined);
    let listedTool = Stdlib_Option.getOrThrow(McpListToolsResult.tools(toolsResult)[0], undefined);
    let toolAnnotations = Stdlib_Option.getOrThrow(McpListToolsResult.toolAnnotations(listedTool), undefined);
    let toolExecution = Stdlib_Option.getOrThrow(McpListToolsResult.toolExecution(listedTool), undefined);
    let listedRoot = Stdlib_Option.getOrThrow(McpListRootsResult.roots(rootsResult)[0], undefined);
    t.expect([
      McpEmptyResult.meta(pingResult),
      McpCompleteResult.values(McpCompleteResult.completion(completionResult)),
      McpCompleteResult.total(McpCompleteResult.completion(completionResult)),
      McpCompleteResult.hasMore(McpCompleteResult.completion(completionResult)),
      McpEmptyResult.meta(loggingResult),
      McpGetPromptResult.description(promptResult),
      McpTestBindings.promptResultTexts(promptResult),
      McpListPromptsResult.nextCursor(promptsResult),
      McpListPromptsResult.promptTitle(listedPrompt),
      McpListPromptsResult.argumentDescription(listedPromptArgument),
      McpListPromptsResult.argumentRequired(listedPromptArgument),
      McpListResourcesResult.nextCursor(resourcesResult),
      McpListResourcesResult.title(listedResource),
      McpListResourcesResult.mimeType(listedResource),
      McpListResourcesResult.size(listedResource),
      Stdlib_Option.flatMap(McpListResourcesResult.annotations(listedResource), McpAnnotations.priority),
      McpIcon.theme(Stdlib_Option.getOrThrow(Stdlib_Option.getOrThrow(McpListResourcesResult.icons(listedResource), undefined)[0], undefined)),
      McpListResourceTemplatesResult.nextCursor(resourceTemplatesResult),
      McpListResourceTemplatesResult.title(listedTemplate),
      Stdlib_Option.flatMap(McpListResourceTemplatesResult.annotations(listedTemplate), McpAnnotations.audience),
      McpTestBindings.readResourceTexts(readResult),
      McpEmptyResult.meta(subscribeResult),
      McpEmptyResult.meta(unsubscribeResult),
      McpTestBindings.toolResultTexts(toolResult),
      Stdlib_Option.map(McpCallToolResult.structuredContent(toolResult), output => output.echoed),
      McpListToolsResult.nextCursor(toolsResult),
      McpListToolsResult.title(listedTool),
      McpToolSchema.kind(McpListToolsResult.inputSchema(listedTool)),
      McpToolSchema.required(McpListToolsResult.inputSchema(listedTool)),
      Stdlib_Option.map(McpListToolsResult.outputSchema(listedTool), McpToolSchema.required),
      McpListToolsResult.annotationTitle(toolAnnotations),
      McpListToolsResult.readOnlyHint(toolAnnotations),
      McpListToolsResult.idempotentHint(toolAnnotations),
      McpListToolsResult.taskSupport(toolExecution),
      McpIcon.theme(Stdlib_Option.getOrThrow(Stdlib_Option.getOrThrow(McpListToolsResult.icons(listedTool), undefined)[0], undefined)),
      McpListRootsResult.uri(listedRoot),
      McpListRootsResult.name(listedRoot)
    ]).toEqual([
      undefined,
      [
        "bindings",
        "topic"
      ],
      2.0,
      false,
      undefined,
      "prompt:review",
      ["prompt:review:bindings"],
      "prompts-next",
      "prompt-cursor",
      "Prompt topic",
      true,
      "resources-next",
      "resource-cursor",
      "application/json",
      32.0,
      0.75,
      "dark",
      "templates-next",
      "template-cursor",
      ["user"],
      ["read:config://typed"],
      undefined,
      undefined,
      ["tool:echo:hello"],
      "hello",
      "tools-next",
      "tool-cursor",
      "object",
      ["message"],
      Primitive_option.some(["echoed"]),
      "Tool title",
      true,
      true,
      "optional",
      "dark",
      "file:///workspace",
      "workspace"
    ]);
    return await TestSupport.settle([
      TestSupport.closeIgnore(McpTestBindings.closeClient(client)),
      TestSupport.closeIgnore(McpTestBindings.closeLowLevelServer(server)),
      TestSupport.closeIgnore(McpTestBindings.transportClose(serverTransport)),
      TestSupport.closeIgnore(McpTestBindings.transportClose(clientTransport))
    ]);
  });
  Vitest.testAsync("typed client tool decoding rejects structured output that does not match the public schema", undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, async t => {
    let server = McpTestBindings.makeLowLevelServer("client-protocol-mismatch-server", "1.0.0");
    let client = McpTestBindings.makeClient("client-protocol-mismatch-client", "1.0.0");
    let pair = McpTestBindings.makeLoopbackTransportPair("client-protocol-mismatch");
    let serverTransport = pair.server;
    let clientTransport = pair.client;
    let timeoutOptions = McpRequestOptions.make(undefined, undefined, 5000, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined);
    McpLowLevelServer.registerCapabilities(server, Object.fromEntries([[
        "tools",
        Object.fromEntries([])
      ]]));
    McpLowLevelServer.setRequestHandlerRaw(server, "toolsCall", (_request, _extra) => Promise.resolve(McpCallToolResult.makeRaw([McpContentBlock.text("tool:mismatch")], Object.fromEntries([[
        "count",
        McpJsonValue.int(1)
      ]]), undefined, undefined)));
    await McpLowLevelServer.connect(server, serverTransport);
    await McpClient.connectWithOptions(client, clientTransport, timeoutOptions);
    await Vitest_Matchers.$$Promise.toThrow(undefined, t.expect(McpClient.callToolWithOptions(client, McpCallToolParams.make("echo", undefined, undefined, undefined, undefined), echoOutputStandardSchema, timeoutOptions)).rejects);
    return await TestSupport.settle([
      TestSupport.closeIgnore(McpTestBindings.closeClient(client)),
      TestSupport.closeIgnore(McpTestBindings.closeLowLevelServer(server)),
      TestSupport.closeIgnore(McpTestBindings.transportClose(serverTransport)),
      TestSupport.closeIgnore(McpTestBindings.transportClose(clientTransport))
    ]);
  });
});

let Json;

let S;

let getOrThrow = Stdlib_Option.getOrThrow;

export {
  Json,
  S,
  echoOutputSchema,
  promptTopic,
  toolMessage,
  resolveUnknown,
  getOrThrow,
  echoOutputStandardSchema,
}
/* echoOutputSchema Not a pure module */
