// Generated by ReScript, PLEASE EDIT WITH CARE

import * as Vitest from "rescript-vitest/src/Vitest.mjs";
import * as Nodefs from "node:fs";
import * as Process from "process";
import * as Nodepath from "node:path";
import * as Stdlib_JsError from "@rescript/runtime/lib/es6/Stdlib_JsError.js";
import * as Nodechild_process from "node:child_process";

let cwd = Process.cwd();

let bscBinary = Nodepath.join(cwd, "node_modules", ".bin", "bsc");

let runtimePath = Nodepath.join(cwd, "node_modules", "@rescript", "runtime");

let fixtureDir = Nodepath.join(cwd, "tests", "support", "type-shape");

let outputDir = Nodepath.join(cwd, "lib", "type-shape");

let utf8 = "utf8";

function commandOutput(result) {
  return result.stdout.toString(utf8) + result.stderr.toString(utf8);
}

function expectSuccess(t, label, result) {
  t.expect(result.status).toBe(0);
  let match = result.error;
  if (!(match == null)) {
    return Stdlib_JsError.throwWithMessage(label);
  }
}

function fixtureSource(fixtureName) {
  return Nodefs.readFileSync(Nodepath.join(fixtureDir, fixtureName + `.res.txt`)).toString(utf8);
}

function parserArgs(sourcePath, astPath) {
  return [
    "-warn-error",
    "+8",
    "-absname",
    "-bs-ast",
    "-o",
    astPath,
    sourcePath
  ];
}

function compilerArgs(astPath) {
  return [
    "-I",
    "lib/ocaml",
    "-I",
    "node_modules/rescript-schema/lib/ocaml",
    "-I",
    "node_modules/rescript-nodejs/lib/ocaml",
    "-I",
    "node_modules/rescript-webapi/lib/ocaml",
    "-runtime-path",
    runtimePath,
    "-warn-error",
    "+8",
    "-bs-package-name",
    "rescript-mcp",
    "-bs-package-output",
    "esmodule:lib/type-shape:.mjs",
    astPath
  ];
}

function compileFixture(fixtureName) {
  Nodefs.mkdirSync(outputDir, {
    recursive: true
  });
  let sourcePath = Nodepath.join(outputDir, fixtureName + `.res`);
  let astPath = Nodepath.join(outputDir, fixtureName + `.ast`);
  Nodefs.writeFileSync(sourcePath, Buffer.from(fixtureSource(fixtureName)));
  let parseResult = Nodechild_process.spawnSync(bscBinary, parserArgs(sourcePath, astPath), {
    cwd: cwd,
    stdio: "pipe"
  });
  let compileResult = parseResult.status === 0 ? Nodechild_process.spawnSync(bscBinary, compilerArgs(astPath), {
      cwd: cwd,
      stdio: "pipe"
    }) : undefined;
  return [
    parseResult,
    compileResult
  ];
}

Vitest.describe("type-shape coverage", undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, () => {
  Vitest.test("typed public path compiles inside the repo build graph", undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, t => {
    let match = compileFixture("TypedPublicPath");
    let compileResult = match[1];
    expectSuccess(t, "parse typed public path", match[0]);
    if (compileResult !== undefined) {
      return expectSuccess(t, "compile typed public path", compileResult);
    } else {
      return Stdlib_JsError.throwWithMessage("Expected compiler result for typed public path");
    }
  });
  Vitest.test("tool output mismatch is rejected by the typed server path", undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, t => {
    let match = compileFixture("ToolOutputMismatch");
    let compileResult = match[1];
    expectSuccess(t, "parse tool output mismatch", match[0]);
    if (compileResult === undefined) {
      return Stdlib_JsError.throwWithMessage("Expected compiler result for tool output mismatch");
    }
    let output = commandOutput(compileResult);
    t.expect(compileResult.status === 0).toBe(false);
    t.expect(output).toContain("wrongOutput");
    t.expect(output).toContain("echoOutput");
  });
  Vitest.test("task tool output mismatch is rejected by the typed task path", undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, t => {
    let match = compileFixture("TaskToolOutputMismatch");
    let compileResult = match[1];
    expectSuccess(t, "parse task output mismatch", match[0]);
    if (compileResult === undefined) {
      return Stdlib_JsError.throwWithMessage("Expected compiler result for task output mismatch");
    }
    let output = commandOutput(compileResult);
    t.expect(compileResult.status === 0).toBe(false);
    t.expect(output).toContain("wrongOutput");
    t.expect(output).toContain("echoOutput");
  });
});

export {
  cwd,
  bscBinary,
  runtimePath,
  fixtureDir,
  outputDir,
  utf8,
  commandOutput,
  expectSuccess,
  fixtureSource,
  parserArgs,
  compilerArgs,
  compileFixture,
}
/* cwd Not a pure module */
