// Generated by ReScript, PLEASE EDIT WITH CARE

import * as Vitest from "rescript-vitest/src/Vitest.mjs";
import * as McpTask from "../src/shared/McpTask.mjs";
import * as McpClient from "../src/client/McpClient.mjs";
import * as Belt_Array from "@rescript/runtime/lib/es6/Belt_Array.js";
import * as TestSupport from "./TestSupport.mjs";
import * as McpTaskStore from "../src/shared/McpTaskStore.mjs";
import * as Stdlib_Option from "@rescript/runtime/lib/es6/Stdlib_Option.js";
import * as McpTaskContext from "../src/shared/McpTaskContext.mjs";
import * as McpTestBindings from "./support/McpTestBindings.mjs";
import * as McpClientOptions from "../src/client/McpClientOptions.mjs";
import * as McpGetTaskResult from "../src/protocol/McpGetTaskResult.mjs";
import * as Primitive_option from "@rescript/runtime/lib/es6/Primitive_option.js";
import * as McpLowLevelServer from "../src/server/McpLowLevelServer.mjs";
import * as McpRequestOptions from "../src/shared/McpRequestOptions.mjs";
import * as McpResponseStream from "../src/shared/McpResponseStream.mjs";
import * as McpListTasksResult from "../src/protocol/McpListTasksResult.mjs";
import * as McpCancelTaskResult from "../src/protocol/McpCancelTaskResult.mjs";
import * as McpCreateTaskResult from "../src/protocol/McpCreateTaskResult.mjs";
import * as McpRequestTaskStore from "../src/shared/McpRequestTaskStore.mjs";
import * as McpCreateTaskOptions from "../src/shared/McpCreateTaskOptions.mjs";
import * as McpTaskCreationParams from "../src/shared/McpTaskCreationParams.mjs";
import * as McpLowLevelServerExperimentalTasks from "../src/server/McpLowLevelServerExperimentalTasks.mjs";

function samplingText(request) {
  return McpTestBindings.getSome(request.params.messages[0]).content.text;
}

function makeSamplingResult(text) {
  return Object.fromEntries([
    [
      "model",
      "task-model"
    ],
    [
      "role",
      "assistant"
    ],
    [
      "content",
      McpTestBindings.makeTextContent(text)
    ]
  ]);
}

function makeElicitationResult(code) {
  return Object.fromEntries([
    [
      "action",
      "accept"
    ],
    [
      "content",
      Object.fromEntries([[
          "code",
          code
        ]])
    ]
  ]);
}

Vitest.describe("experimental server task roundtrip", undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, () => Vitest.testAsync("low-level server task streams roundtrip through client task handlers", undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, async t => {
  let clientTaskStore = McpTaskStore.makeInMemory();
  let clientCapabilities = Object.fromEntries([
    [
      "sampling",
      Object.fromEntries([])
    ],
    [
      "elicitation",
      Object.fromEntries([[
          "form",
          Object.fromEntries([])
        ]])
    ],
    [
      "tasks",
      Object.fromEntries([
        [
          "taskStore",
          clientTaskStore
        ],
        [
          "defaultTaskPollInterval",
          1
        ],
        [
          "list",
          Object.fromEntries([])
        ],
        [
          "cancel",
          Object.fromEntries([])
        ],
        [
          "requests",
          Object.fromEntries([
            [
              "sampling",
              Object.fromEntries([[
                  "createMessage",
                  Object.fromEntries([])
                ]])
            ],
            [
              "elicitation",
              Object.fromEntries([[
                  "create",
                  Object.fromEntries([])
                ]])
            ]
          ])
        ]
      ])
    ]
  ]);
  let client = McpClient.makeWithOptions(McpTestBindings.makeImplementation("stream-client", "1.0.0"), McpClientOptions.make(clientCapabilities, undefined, undefined, undefined, undefined, undefined, undefined, undefined));
  let server = McpLowLevelServer.make(McpTestBindings.makeImplementation("stream-server", "1.0.0"));
  let pair = McpTestBindings.makeLoopbackTransportPair("stream-task-session");
  let serverTransport = pair.server;
  let clientTransport = pair.client;
  let timeoutOptions = McpRequestOptions.make(undefined, undefined, 5000, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined);
  let taskOptions = McpRequestOptions.make(undefined, undefined, 5000, undefined, undefined, Primitive_option.some(McpTaskCreationParams.make(60000, 1, undefined)), undefined, undefined, undefined, undefined, undefined);
  McpTestBindings.setClientRequestHandlerRaw(client, "samplingCreateMessage", (request, ctx) => {
    let requestedText = samplingText(request);
    let taskContext = McpTestBindings.getSome(Primitive_option.fromNullable(ctx.task));
    let store = McpTaskContext.store(taskContext);
    let run = async () => {
      let task = await McpRequestTaskStore.createTask(store, McpCreateTaskOptions.make(60000, 1, undefined, undefined));
      await McpRequestTaskStore.updateTaskStatus(store, McpTask.taskId(task), "working", "sampling");
      if (requestedText !== "stall") {
        queueMicrotask(() => {
          (async () => await McpRequestTaskStore.storeTaskResultRaw(store, McpTask.taskId(task), "completed", makeSamplingResult(requestedText + "-response")))();
        });
      }
      let workingTask = await McpRequestTaskStore.getTask(store, McpTask.taskId(task));
      return McpCreateTaskResult.make(workingTask, undefined);
    };
    return run();
  });
  McpTestBindings.setClientRequestHandlerRaw(client, "elicitationCreate", (_request, ctx) => {
    let taskContext = McpTestBindings.getSome(Primitive_option.fromNullable(ctx.task));
    let store = McpTaskContext.store(taskContext);
    let run = async () => {
      let task = await McpRequestTaskStore.createTask(store, McpCreateTaskOptions.make(60000, 1, undefined, undefined));
      await McpRequestTaskStore.updateTaskStatus(store, McpTask.taskId(task), "working", "elicitation");
      queueMicrotask(() => {
        (async () => await McpRequestTaskStore.storeTaskResultRaw(store, McpTask.taskId(task), "completed", makeElicitationResult("42")))();
      });
      let workingTask = await McpRequestTaskStore.getTask(store, McpTask.taskId(task));
      return McpCreateTaskResult.make(workingTask, undefined);
    };
    return run();
  });
  await McpLowLevelServer.connect(server, serverTransport);
  await McpClient.connectWithOptions(client, clientTransport, timeoutOptions);
  let genericMessages = await McpResponseStream.toArray(McpLowLevelServerExperimentalTasks.requestStreamRawWithOptions(McpLowLevelServer.experimentalTasks(server), "samplingCreateMessage", McpTestBindings.makeSamplingRequestParams("generic", 16), taskOptions));
  let genericTaskId = McpTestBindings.getSome(Belt_Array.keepMap(genericMessages, message => Stdlib_Option.map(McpResponseStream.task(message), McpTask.taskId))[0]);
  let genericResult = McpTestBindings.getSome(Belt_Array.keepMap(genericMessages, McpResponseStream.result)[0]);
  let genericTask = await McpLowLevelServerExperimentalTasks.getTask(McpLowLevelServer.experimentalTasks(server), genericTaskId);
  let genericTaskResult = await McpLowLevelServerExperimentalTasks.getTaskResultRawWithOptions(McpLowLevelServer.experimentalTasks(server), genericTaskId, timeoutOptions);
  let createMessageMessages = await McpResponseStream.toArray(McpLowLevelServerExperimentalTasks.createMessageStreamRawWithOptions(McpLowLevelServer.experimentalTasks(server), McpTestBindings.makeSamplingRequestParams("direct", 16), taskOptions));
  let createMessageResult = McpTestBindings.getSome(Belt_Array.keepMap(createMessageMessages, McpResponseStream.result)[0]);
  let elicitationMessages = await McpResponseStream.toArray(McpLowLevelServerExperimentalTasks.elicitInputStreamRawWithOptions(McpLowLevelServer.experimentalTasks(server), McpTestBindings.makeCodeElicitationRequestParams("Provide a code"), taskOptions));
  let elicitationResult = McpTestBindings.getSome(Belt_Array.keepMap(elicitationMessages, McpResponseStream.result)[0]);
  let stalledMessagesPromise = McpResponseStream.toArray(McpLowLevelServerExperimentalTasks.createMessageStreamRawWithOptions(McpLowLevelServer.experimentalTasks(server), McpTestBindings.makeSamplingRequestParams("stall", 16), taskOptions));
  await Promise.resolve();
  let listedTasks = await McpLowLevelServerExperimentalTasks.listTasksWithOptions(McpLowLevelServer.experimentalTasks(server), timeoutOptions);
  let stalledTaskId = McpTestBindings.getSome(Belt_Array.keepMap(McpListTasksResult.tasks(listedTasks), task => {
      if (McpTask.status(task) === "working") {
        return McpTask.taskId(task);
      }
    })[0]);
  let cancelledTask = await McpLowLevelServerExperimentalTasks.cancelTaskWithOptions(McpLowLevelServer.experimentalTasks(server), stalledTaskId, timeoutOptions);
  let stalledMessages = await stalledMessagesPromise;
  t.expect([
    Belt_Array.some(genericMessages.map(McpResponseStream.kind), kind => kind === "taskCreated"),
    Belt_Array.some(genericMessages.map(McpResponseStream.kind), kind => kind === "result"),
    genericResult.model,
    genericResult.role,
    genericResult.content.text,
    McpGetTaskResult.status(genericTask),
    genericTaskResult.content.text,
    Belt_Array.some(createMessageMessages.map(McpResponseStream.kind), kind => kind === "taskCreated"),
    createMessageResult.content.text,
    Belt_Array.some(elicitationMessages.map(McpResponseStream.kind), kind => kind === "taskCreated"),
    elicitationResult.action,
    Stdlib_Option.flatMap(Primitive_option.fromNullable(elicitationResult.content), content => Stdlib_Option.map(content["code"], prim => prim)),
    Belt_Array.some(McpListTasksResult.tasks(listedTasks).map(McpTask.taskId), taskId => taskId === genericTaskId),
    Belt_Array.some(stalledMessages.map(McpResponseStream.kind), kind => kind === "taskCreated"),
    McpCancelTaskResult.status(cancelledTask)
  ]).toEqual([
    true,
    true,
    "task-model",
    "assistant",
    "generic-response",
    "completed",
    "generic-response",
    true,
    "direct-response",
    true,
    "accept",
    "42",
    true,
    true,
    "cancelled"
  ]);
  return await TestSupport.settle([
    TestSupport.closeIgnore(McpTestBindings.closeClient(client)),
    TestSupport.closeIgnore(McpTestBindings.closeLowLevelServer(server)),
    TestSupport.closeIgnore(McpTestBindings.transportClose(serverTransport)),
    TestSupport.closeIgnore(McpTestBindings.transportClose(clientTransport))
  ]);
}));

export {
  samplingText,
  makeSamplingResult,
  makeElicitationResult,
}
/*  Not a pure module */
