// Generated by ReScript, PLEASE EDIT WITH CARE

import * as Vitest from "rescript-vitest/src/Vitest.mjs";
import * as McpTask from "../src/shared/McpTask.mjs";
import * as McpClient from "../src/client/McpClient.mjs";
import * as McpServer from "../src/server/McpServer.mjs";
import * as Belt_Array from "@rescript/runtime/lib/es6/Belt_Array.js";
import * as McpTaskTool from "../src/server/McpTaskTool.mjs";
import * as McpTaskStore from "../src/shared/McpTaskStore.mjs";
import * as Stdlib_Option from "@rescript/runtime/lib/es6/Stdlib_Option.js";
import * as McpTaskContext from "../src/shared/McpTaskContext.mjs";
import * as McpContentBlock from "../src/protocol/McpContentBlock.mjs";
import * as McpTestBindings from "./support/McpTestBindings.mjs";
import * as McpGetTaskResult from "../src/protocol/McpGetTaskResult.mjs";
import * as McpServerContext from "../src/server/McpServerContext.mjs";
import * as McpServerOptions from "../src/server/McpServerOptions.mjs";
import * as Primitive_option from "@rescript/runtime/lib/es6/Primitive_option.js";
import * as S$RescriptSchema from "rescript-schema/src/S.mjs";
import * as McpCallToolResult from "../src/protocol/McpCallToolResult.mjs";
import * as McpRequestOptions from "../src/shared/McpRequestOptions.mjs";
import * as McpResponseStream from "../src/shared/McpResponseStream.mjs";
import * as McpStandardSchema from "../src/protocol/McpStandardSchema.mjs";
import * as McpListTasksResult from "../src/protocol/McpListTasksResult.mjs";
import * as McpCancelTaskResult from "../src/protocol/McpCancelTaskResult.mjs";
import * as McpCreateTaskResult from "../src/protocol/McpCreateTaskResult.mjs";
import * as McpRequestTaskStore from "../src/shared/McpRequestTaskStore.mjs";
import * as McpCreateTaskOptions from "../src/shared/McpCreateTaskOptions.mjs";
import * as McpTaskCreationParams from "../src/shared/McpTaskCreationParams.mjs";
import * as McpClientExperimentalTasks from "../src/client/McpClientExperimentalTasks.mjs";
import * as McpServerExperimentalTasks from "../src/server/McpServerExperimentalTasks.mjs";

let taskArgsSchema = S$RescriptSchema.schema(s => ({
  message: s.m(S$RescriptSchema.string)
}));

let taskOutputSchema = S$RescriptSchema.schema(s => ({
  message: s.m(S$RescriptSchema.string)
}));

let taskSchema = McpStandardSchema.fromRescriptSchema(taskArgsSchema);

let taskOutputStandardSchema = McpStandardSchema.fromRescriptSchema(taskOutputSchema);

let taskOptions = McpTaskCreationParams.make(60000, 1, undefined);

Vitest.describe("experimental task roundtrip", undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, () => Vitest.testAsync("task tool registration and client experimental task APIs roundtrip through the live SDK", undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, async t => {
  let taskStore = McpTaskStore.makeInMemory();
  let serverCapabilities = Object.fromEntries([[
      "tasks",
      Object.fromEntries([
        [
          "taskStore",
          taskStore
        ],
        [
          "defaultTaskPollInterval",
          1
        ],
        [
          "list",
          Object.fromEntries([])
        ],
        [
          "cancel",
          Object.fromEntries([])
        ],
        [
          "requests",
          Object.fromEntries([[
              "tools",
              Object.fromEntries([[
                  "call",
                  Object.fromEntries([])
                ]])
            ]])
        ]
      ])
    ]]);
  let client = McpClient.make(McpTestBindings.makeImplementation("loopback-task-client", "1.0.0"));
  let server = McpServer.makeWithOptions(McpTestBindings.makeImplementation("loopback-task-server", "1.0.0"), McpServerOptions.make(serverCapabilities, undefined, undefined, undefined, undefined, undefined, undefined, undefined));
  let pair = McpTestBindings.makeLoopbackTransportPair("task-loopback");
  let serverTransport = pair.server;
  let clientTransport = pair.client;
  let timeoutOptions = McpRequestOptions.make(undefined, undefined, 5000, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined);
  let taskRequestOptions = McpRequestOptions.make(undefined, undefined, 5000, undefined, undefined, Primitive_option.some(taskOptions), undefined, undefined, undefined, undefined, undefined);
  let completedTaskIds = {
    contents: []
  };
  let typedRetrievedMessage = {
    contents: undefined
  };
  McpServerExperimentalTasks.registerToolTask(McpServer.experimentalTasks(server), "echo-task", McpTaskTool.makeConfig("Echo Task", undefined, Primitive_option.some(taskSchema), taskOutputStandardSchema, undefined, Primitive_option.some(McpTaskTool.makeExecution("required", undefined)), undefined, undefined), McpTaskTool.makeHandler(async (args, ctx) => {
    let taskContext = McpTestBindings.getSome(McpServerContext.task(ctx));
    let store = McpTaskContext.store(taskContext);
    let task = await McpRequestTaskStore.createTask(store, McpCreateTaskOptions.make(60000, 1, undefined, undefined));
    await McpRequestTaskStore.updateTaskStatus(store, McpTask.taskId(task), "working", "working");
    queueMicrotask(() => {
      (async () => {
        let ttlText = Stdlib_Option.getOr(Stdlib_Option.map(McpTaskContext.requestedTtl(taskContext), value => value.toString()), "missing");
        let finalResult = McpCallToolResult.make([McpContentBlock.text(`task:` + args.message + `:` + ttlText)], {
          message: args.message
        }, undefined, undefined);
        await McpRequestTaskStore.storeTaskResult(store, McpTask.taskId(task), "completed", finalResult, taskOutputStandardSchema);
        let typedResult = await McpRequestTaskStore.getTaskResult(store, McpTask.taskId(task), taskOutputStandardSchema);
        typedRetrievedMessage.contents = Stdlib_Option.map(McpCallToolResult.structuredContent(typedResult), output => output.message);
        completedTaskIds.contents = Belt_Array.concatMany([
          [McpTask.taskId(task)],
          completedTaskIds.contents
        ]);
      })();
    });
    let workingTask = await McpRequestTaskStore.getTask(store, McpTask.taskId(task));
    return McpCreateTaskResult.make(workingTask, undefined);
  }, async (_args, ctx) => {
    let taskContext = McpTestBindings.getSome(McpServerContext.task(ctx));
    let taskId = McpTestBindings.getSome(McpTaskContext.id(taskContext));
    return McpGetTaskResult.ofTask(await McpRequestTaskStore.getTask(McpTaskContext.store(taskContext), taskId));
  }, async (_args, ctx) => {
    let taskContext = McpTestBindings.getSome(McpServerContext.task(ctx));
    let taskId = McpTestBindings.getSome(McpTaskContext.id(taskContext));
    return await McpRequestTaskStore.getTaskResult(McpTaskContext.store(taskContext), taskId, taskOutputStandardSchema);
  }, undefined));
  McpServerExperimentalTasks.registerToolTaskRaw0(McpServer.experimentalTasks(server), "stall-task", McpTaskTool.makeRawConfig("Stall Task", undefined, undefined, undefined, Primitive_option.some(McpTaskTool.makeExecution("required", undefined)), undefined, undefined), McpTaskTool.makeRawHandler0(async ctx => {
    let taskContext = McpTestBindings.getSome(McpServerContext.task(ctx));
    let store = McpTaskContext.store(taskContext);
    let task = await McpRequestTaskStore.createTask(store, McpCreateTaskOptions.make(60000, 1, undefined, undefined));
    await McpRequestTaskStore.updateTaskStatus(store, McpTask.taskId(task), "working", "waiting");
    let workingTask = await McpRequestTaskStore.getTask(store, McpTask.taskId(task));
    return McpCreateTaskResult.make(workingTask, undefined);
  }, async ctx => {
    let taskContext = McpTestBindings.getSome(McpServerContext.task(ctx));
    let taskId = McpTestBindings.getSome(McpTaskContext.id(taskContext));
    return McpGetTaskResult.ofTask(await McpRequestTaskStore.getTask(McpTaskContext.store(taskContext), taskId));
  }, _ctx => Promise.resolve(McpCallToolResult.makeRaw([McpContentBlock.text("unreachable")], undefined, undefined, undefined)), undefined));
  await McpServer.connect(server, serverTransport);
  await McpClient.connectWithOptions(client, clientTransport, timeoutOptions);
  await McpClient.listTools(client);
  let stream = McpClientExperimentalTasks.callToolStreamRawWithOptions(McpClient.experimentalTasks(client), Object.fromEntries([
    [
      "name",
      "echo-task"
    ],
    [
      "arguments",
      Object.fromEntries([[
          "message",
          "hello"
        ]])
    ]
  ]), taskRequestOptions);
  let messages = await McpResponseStream.toArray(stream);
  let taskId = McpTestBindings.getSome(Belt_Array.keepMap(messages, message => Stdlib_Option.map(McpResponseStream.task(message), McpTask.taskId))[0]);
  let finalResult = McpTestBindings.getSome(Belt_Array.keepMap(messages, McpResponseStream.result)[0]);
  let completedTask = await McpClientExperimentalTasks.getTask(McpClient.experimentalTasks(client), taskId);
  let completedTaskResult = await McpClientExperimentalTasks.getTaskResultRawWithOptions(McpClient.experimentalTasks(client), taskId, timeoutOptions);
  let listedTasks = await McpClientExperimentalTasks.listTasksWithOptions(McpClient.experimentalTasks(client), timeoutOptions);
  let stallMessagesPromise = McpResponseStream.toArray(McpClientExperimentalTasks.callToolStreamRawWithOptions(McpClient.experimentalTasks(client), Object.fromEntries([[
      "name",
      "stall-task"
    ]]), taskRequestOptions));
  await Promise.resolve();
  let stalledTaskId = McpTestBindings.getSome(Belt_Array.keepMap(McpListTasksResult.tasks(await McpClientExperimentalTasks.listTasksWithOptions(McpClient.experimentalTasks(client), timeoutOptions)), task => {
      if (McpTask.status(task) === "working" && McpTask.taskId(task) !== taskId) {
        return McpTask.taskId(task);
      }
    })[0]);
  let cancelledTask = await McpClientExperimentalTasks.cancelTaskWithOptions(McpClient.experimentalTasks(client), stalledTaskId, timeoutOptions);
  let stallMessages = await stallMessagesPromise;
  t.expect([
    Belt_Array.some(messages.map(McpResponseStream.kind), kind => kind === "result"),
    Belt_Array.some(messages.map(McpResponseStream.kind), kind => kind === "taskCreated"),
    McpTestBindings.toolResultTextsUnknown(finalResult),
    McpGetTaskResult.status(completedTask),
    McpTestBindings.toolResultTextsUnknown(completedTaskResult),
    typedRetrievedMessage.contents,
    Belt_Array.some(McpListTasksResult.tasks(listedTasks).map(McpTask.taskId), value => value === taskId),
    Belt_Array.some(completedTaskIds.contents, value => value === taskId),
    Belt_Array.some(stallMessages.map(McpResponseStream.kind), kind => kind === "taskCreated"),
    McpCancelTaskResult.status(cancelledTask)
  ]).toEqual([
    true,
    true,
    ["task:hello:60000"],
    "completed",
    ["task:hello:60000"],
    "hello",
    true,
    true,
    true,
    "cancelled"
  ]);
  await McpClient.close(client);
  return await McpServer.close(server);
}));

let S;

let Json;

export {
  S,
  Json,
  taskArgsSchema,
  taskOutputSchema,
  taskSchema,
  taskOutputStandardSchema,
  taskOptions,
}
/* taskArgsSchema Not a pure module */
