// Generated by ReScript, PLEASE EDIT WITH CARE

import * as Vitest from "rescript-vitest/src/Vitest.mjs";
import * as McpTypes from "../src/core/McpTypes.mjs";
import * as Nodehttp from "node:http";
import * as TestSupport from "./TestSupport.mjs";
import * as McpTestBindings from "./support/McpTestBindings.mjs";
import * as Primitive_option from "@rescript/runtime/lib/es6/Primitive_option.js";

Vitest.describe("streamable http roundtrip", undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, () => Vitest.testAsync("initializes and pings through the bound node and client transports", undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, async t => {
  let server = McpTestBindings.makeLowLevelServerWithInstructions("http-test-server", "1.0.0", "http test server");
  let transport = McpTestBindings.makeNodeStreamableHttpStatefulJsonTransport("http-test-session");
  let client = McpTestBindings.makeClient("http-test-client", "1.0.0");
  await McpTestBindings.connectLowLevelServer(server, transport);
  let httpServer = Nodehttp.createServer((req, res) => {
    (async () => {
      try {
        return await McpTestBindings.nodeHandleRequest(transport, req, res);
      } catch (_error) {
        res.statusCode = 500;
        res.end(Buffer.from("transport error"));
        return;
      }
    })();
  });
  let address = await TestSupport.listenHttpServer(httpServer);
  let clientTransport = McpTestBindings.makeStreamableHttpClientTransport(`http://127.0.0.1:` + address.port.toString() + `/mcp`);
  await McpTestBindings.connectClientWithTimeout(client, clientTransport, 5000);
  await McpTestBindings.pingClientWithTimeout(client, 5000);
  t.expect([
    McpTestBindings.clientServerVersion(client),
    McpTestBindings.clientNegotiatedProtocolVersion(client),
    McpTestBindings.clientInstructions(client),
    McpTestBindings.clientServerCapabilities(client) !== undefined,
    McpTestBindings.httpClientProtocolVersion(clientTransport),
    McpTestBindings.transportSessionId(transport)
  ]).toEqual([
    Primitive_option.some(McpTestBindings.makeImplementation("http-test-server", "1.0.0")),
    McpTypes.latestProtocolVersion,
    "http test server",
    true,
    McpTypes.latestProtocolVersion,
    "http-test-session"
  ]);
  return await TestSupport.settle([
    TestSupport.closeIgnore(McpTestBindings.closeClient(client)),
    TestSupport.closeIgnore(McpTestBindings.closeLowLevelServer(server)),
    TestSupport.closeIgnore(TestSupport.closeHttpServer(httpServer))
  ]);
}));

/*  Not a pure module */
