// Generated by ReScript, PLEASE EDIT WITH CARE

import * as Vitest from "rescript-vitest/src/Vitest.mjs";
import * as McpClient from "../src/client/McpClient.mjs";
import * as Belt_Array from "@rescript/runtime/lib/es6/Belt_Array.js";
import * as TestSupport from "./TestSupport.mjs";
import * as Stdlib_Option from "@rescript/runtime/lib/es6/Stdlib_Option.js";
import * as McpEmptyResult from "../src/protocol/McpEmptyResult.mjs";
import * as McpElicitResult from "../src/protocol/McpElicitResult.mjs";
import * as McpTestBindings from "./support/McpTestBindings.mjs";
import * as S$RescriptSchema from "rescript-schema/src/S.mjs";
import * as McpCompleteParams from "../src/protocol/McpCompleteParams.mjs";
import * as McpCompleteResult from "../src/protocol/McpCompleteResult.mjs";
import * as McpLowLevelServer from "../src/server/McpLowLevelServer.mjs";
import * as McpStandardSchema from "../src/protocol/McpStandardSchema.mjs";
import * as McpListRootsResult from "../src/protocol/McpListRootsResult.mjs";
import * as McpSamplingContent from "../src/protocol/McpSamplingContent.mjs";
import * as McpSamplingMessage from "../src/protocol/McpSamplingMessage.mjs";
import * as McpCreateMessageParams from "../src/protocol/McpCreateMessageParams.mjs";
import * as McpCreateMessageResult from "../src/protocol/McpCreateMessageResult.mjs";
import * as McpLoggingMessageParams from "../src/protocol/McpLoggingMessageParams.mjs";
import * as McpResourceUpdatedParams from "../src/protocol/McpResourceUpdatedParams.mjs";
import * as McpElicitRequestFormParams from "../src/protocol/McpElicitRequestFormParams.mjs";

let codeFormSchema = S$RescriptSchema.schema(s => ({
  code: s.m(S$RescriptSchema.string)
}));

function notificationStringField(notification, fieldName) {
  return Stdlib_Option.map(notification.params[fieldName], prim => prim);
}

Vitest.describe("low-level client callback roundtrip", undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, () => Vitest.testAsync("server sampling, elicitation, and roots requests roundtrip through raw client handlers", undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, async t => {
  let server = McpTestBindings.makeLowLevelServer("callback-server", "1.0.0");
  let serverCapabilities = Object.fromEntries([
    [
      "logging",
      Object.fromEntries([])
    ],
    [
      "completions",
      Object.fromEntries([])
    ],
    [
      "prompts",
      Object.fromEntries([])
    ],
    [
      "resources",
      Object.fromEntries([])
    ]
  ]);
  McpLowLevelServer.registerCapabilities(server, serverCapabilities);
  McpLowLevelServer.setRequestHandlerRaw(server, "completionComplete", async (_request, _extra) => Object.fromEntries([[
      "completion",
      Object.fromEntries([[
          "values",
          [
            "alpha",
            "beta"
          ].map(prim => prim)
        ]])
    ]]));
  let client = McpTestBindings.makeClient("callback-client", "1.0.0");
  let clientCapabilities = Object.fromEntries([
    [
      "sampling",
      Object.fromEntries([])
    ],
    [
      "elicitation",
      Object.fromEntries([[
          "form",
          Object.fromEntries([])
        ]])
    ],
    [
      "roots",
      Object.fromEntries([])
    ]
  ]);
  McpTestBindings.registerClientCapabilities(client, clientCapabilities);
  McpTestBindings.setClientRequestHandlerRaw(client, "samplingCreateMessage", async (_request, _ctx) => McpCreateMessageResult.make("test-model", "assistant", McpSamplingContent.text("sampled text"), undefined, undefined, undefined));
  McpTestBindings.setClientRequestHandlerRaw(client, "elicitationCreate", async (_request, _ctx) => McpElicitResult.make("accept", Object.fromEntries([[
      "code",
      "1234"
    ]]), undefined, undefined));
  McpTestBindings.setClientRequestHandlerRaw(client, "rootsList", async (_request, _ctx) => Object.fromEntries([[
      "roots",
      [Object.fromEntries([
          [
            "uri",
            "file:///workspace"
          ],
          [
            "name",
            "workspace"
          ]
        ])]
    ]]));
  let loggingNotifications = {
    contents: []
  };
  let updatedResources = {
    contents: []
  };
  McpClient.setNotificationHandlerRaw(client, "message", async notification => {
    loggingNotifications.contents = Belt_Array.concatMany([
      loggingNotifications.contents,
      [Stdlib_Option.getOr(notificationStringField(notification, "level"), "missing-level") + `:` + Stdlib_Option.getOr(notificationStringField(notification, "data"), "missing-data")]
    ]);
  });
  McpClient.setNotificationHandlerRaw(client, "resourcesUpdated", async notification => {
    updatedResources.contents = Belt_Array.concatMany([
      updatedResources.contents,
      [Stdlib_Option.getOr(notificationStringField(notification, "uri"), "missing-uri")]
    ]);
  });
  let pair = McpTestBindings.makeLoopbackTransportPair("callback-session");
  let serverTransport = pair.server;
  let clientTransport = pair.client;
  await McpTestBindings.connectLowLevelServer(server, serverTransport);
  await McpTestBindings.connectClientWithTimeout(client, clientTransport, 5000);
  await McpLowLevelServer.sendLoggingMessage(server, McpLoggingMessageParams.make("info", "callback-log", undefined, undefined, undefined));
  await McpLowLevelServer.sendLoggingMessageWithSessionId(server, McpLoggingMessageParams.make("notice", "callback-log-session", undefined, undefined, undefined), "callback-session");
  await McpLowLevelServer.sendResourceUpdated(server, McpResourceUpdatedParams.make("memo://alpha", undefined, undefined));
  let pingResult = await McpLowLevelServer.ping(server);
  let completionResult = await McpClient.complete(client, McpCompleteParams.makeWithPrompt(McpCompleteParams.promptReference("review"), McpCompleteParams.makeArgument("topic", "a", undefined), undefined, undefined, undefined));
  let samplingResult = await McpLowLevelServer.createMessage(server, McpCreateMessageParams.make([McpSamplingMessage.text("user", "hello server")], 64, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined));
  let elicitationResult = await McpLowLevelServer.elicitFormInput(server, McpElicitRequestFormParams.make("Provide a code", McpStandardSchema.jsonSchemaOfRescriptSchema(codeFormSchema), undefined, undefined));
  let rootsResult = await McpTestBindings.listRootsRaw(server);
  t.expect([
    McpTestBindings.lowLevelServerCapabilities(server)["logging"] !== undefined,
    McpLowLevelServer.getClientCapabilities(server) !== undefined,
    McpEmptyResult.meta(pingResult),
    McpCompleteResult.values(McpCompleteResult.completion(completionResult)),
    McpCreateMessageResult.model(samplingResult),
    McpCreateMessageResult.role(samplingResult),
    McpSamplingContent.textValue(McpCreateMessageResult.content(samplingResult)),
    McpElicitResult.action(elicitationResult),
    Stdlib_Option.flatMap(McpElicitResult.content(elicitationResult), content => Stdlib_Option.map(content["code"], prim => prim)),
    loggingNotifications.contents,
    updatedResources.contents,
    McpListRootsResult.roots(rootsResult).map(root => [
      McpListRootsResult.uri(root),
      McpListRootsResult.name(root)
    ])
  ]).toEqual([
    true,
    true,
    undefined,
    [
      "alpha",
      "beta"
    ],
    "test-model",
    "assistant",
    "sampled text",
    "accept",
    "1234",
    [
      "info:callback-log",
      "notice:callback-log-session"
    ],
    ["memo://alpha"],
    [[
        "file:///workspace",
        "workspace"
      ]]
  ]);
  return await TestSupport.settle([
    (async () => McpClient.removeNotificationHandlerRaw(client, "message"))(),
    (async () => McpClient.removeNotificationHandlerRaw(client, "resourcesUpdated"))(),
    TestSupport.closeIgnore(McpTestBindings.closeClient(client)),
    TestSupport.closeIgnore(McpTestBindings.closeLowLevelServer(server)),
    TestSupport.closeIgnore(McpTestBindings.transportClose(serverTransport)),
    TestSupport.closeIgnore(McpTestBindings.transportClose(clientTransport))
  ]);
}));

export {
  codeFormSchema,
  notificationStringField,
}
/* codeFormSchema Not a pure module */
