// Generated by ReScript, PLEASE EDIT WITH CARE

import * as Vitest from "rescript-vitest/src/Vitest.mjs";
import * as McpClient from "../src/client/McpClient.mjs";
import * as Belt_Array from "@rescript/runtime/lib/es6/Belt_Array.js";
import * as TestSupport from "./TestSupport.mjs";
import * as Stdlib_Option from "@rescript/runtime/lib/es6/Stdlib_Option.js";
import * as McpEmptyResult from "../src/protocol/McpEmptyResult.mjs";
import * as McpTestBindings from "./support/McpTestBindings.mjs";
import * as Primitive_option from "@rescript/runtime/lib/es6/Primitive_option.js";
import * as McpCompleteParams from "../src/protocol/McpCompleteParams.mjs";
import * as McpCompleteResult from "../src/protocol/McpCompleteResult.mjs";
import * as McpLowLevelServer from "../src/server/McpLowLevelServer.mjs";
import * as McpListRootsResult from "../src/protocol/McpListRootsResult.mjs";
import * as McpLoggingMessageParams from "../src/protocol/McpLoggingMessageParams.mjs";
import * as McpResourceUpdatedParams from "../src/protocol/McpResourceUpdatedParams.mjs";

function notificationStringField(notification, fieldName) {
  return Stdlib_Option.map(notification.params[fieldName], prim => prim);
}

Vitest.describe("low-level client callback roundtrip", undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, () => Vitest.testAsync("server sampling, elicitation, and roots requests roundtrip through raw client handlers", undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, async t => {
  let server = McpTestBindings.makeLowLevelServer("callback-server", "1.0.0");
  let serverCapabilities = Object.fromEntries([
    [
      "logging",
      Object.fromEntries([])
    ],
    [
      "completions",
      Object.fromEntries([])
    ],
    [
      "prompts",
      Object.fromEntries([])
    ],
    [
      "resources",
      Object.fromEntries([])
    ]
  ]);
  McpLowLevelServer.registerCapabilities(server, serverCapabilities);
  McpLowLevelServer.setRequestHandlerRaw(server, "completionComplete", (_request, _extra) => Promise.resolve(Object.fromEntries([[
      "completion",
      Object.fromEntries([[
          "values",
          [
            "alpha",
            "beta"
          ].map(prim => prim)
        ]])
    ]])));
  let client = McpTestBindings.makeClient("callback-client", "1.0.0");
  let clientCapabilities = Object.fromEntries([
    [
      "sampling",
      Object.fromEntries([])
    ],
    [
      "elicitation",
      Object.fromEntries([[
          "form",
          Object.fromEntries([])
        ]])
    ],
    [
      "roots",
      Object.fromEntries([])
    ]
  ]);
  McpTestBindings.registerClientCapabilities(client, clientCapabilities);
  McpTestBindings.setClientRequestHandlerRaw(client, "samplingCreateMessage", (_request, _ctx) => Promise.resolve(Object.fromEntries([
    [
      "model",
      "test-model"
    ],
    [
      "role",
      "assistant"
    ],
    [
      "content",
      McpTestBindings.makeTextContent("sampled text")
    ]
  ])));
  McpTestBindings.setClientRequestHandlerRaw(client, "elicitationCreate", (_request, _ctx) => Promise.resolve(Object.fromEntries([
    [
      "action",
      "accept"
    ],
    [
      "content",
      Object.fromEntries([[
          "code",
          "1234"
        ]])
    ]
  ])));
  McpTestBindings.setClientRequestHandlerRaw(client, "rootsList", (_request, _ctx) => Promise.resolve(Object.fromEntries([[
      "roots",
      [Object.fromEntries([
          [
            "uri",
            "file:///workspace"
          ],
          [
            "name",
            "workspace"
          ]
        ])]
    ]])));
  let loggingNotifications = {
    contents: []
  };
  let updatedResources = {
    contents: []
  };
  McpClient.setNotificationHandlerRaw(client, "message", notification => {
    loggingNotifications.contents = Belt_Array.concatMany([
      loggingNotifications.contents,
      [Stdlib_Option.getOr(notificationStringField(notification, "level"), "missing-level") + `:` + Stdlib_Option.getOr(notificationStringField(notification, "data"), "missing-data")]
    ]);
    return Promise.resolve();
  });
  McpClient.setNotificationHandlerRaw(client, "resourcesUpdated", notification => {
    updatedResources.contents = Belt_Array.concatMany([
      updatedResources.contents,
      [Stdlib_Option.getOr(notificationStringField(notification, "uri"), "missing-uri")]
    ]);
    return Promise.resolve();
  });
  let pair = McpTestBindings.makeLoopbackTransportPair("callback-session");
  let serverTransport = pair.server;
  let clientTransport = pair.client;
  await McpTestBindings.connectLowLevelServer(server, serverTransport);
  await McpTestBindings.connectClientWithTimeout(client, clientTransport, 5000);
  await McpLowLevelServer.sendLoggingMessage(server, McpLoggingMessageParams.make("info", "callback-log", undefined, undefined, undefined));
  await McpLowLevelServer.sendLoggingMessageWithSessionId(server, McpLoggingMessageParams.make("notice", "callback-log-session", undefined, undefined, undefined), "callback-session");
  await McpLowLevelServer.sendResourceUpdated(server, McpResourceUpdatedParams.make("memo://alpha", undefined, undefined));
  let pingResult = await McpLowLevelServer.ping(server);
  let completionResult = await McpClient.complete(client, McpCompleteParams.makeWithPrompt(McpCompleteParams.promptReference("review"), McpCompleteParams.makeArgument("topic", "a", undefined), undefined, undefined, undefined));
  let samplingResult = await McpTestBindings.createSamplingMessageRaw(server, McpTestBindings.makeSamplingRequestParams("hello server", 64));
  let elicitationResult = await McpTestBindings.elicitInputRaw(server, McpTestBindings.makeCodeElicitationRequestParams("Provide a code"));
  let rootsResult = await McpTestBindings.listRootsRaw(server);
  t.expect([
    McpTestBindings.lowLevelServerCapabilities(server)["logging"] !== undefined,
    McpLowLevelServer.getClientCapabilities(server) !== undefined,
    McpEmptyResult.meta(pingResult),
    McpCompleteResult.values(McpCompleteResult.completion(completionResult)),
    samplingResult.model,
    samplingResult.role,
    samplingResult.content.text,
    elicitationResult.action,
    Stdlib_Option.flatMap(Primitive_option.fromNullable(elicitationResult.content), content => Stdlib_Option.map(content["code"], prim => prim)),
    loggingNotifications.contents,
    updatedResources.contents,
    McpListRootsResult.roots(rootsResult).map(root => [
      McpListRootsResult.uri(root),
      McpListRootsResult.name(root)
    ])
  ]).toEqual([
    true,
    true,
    undefined,
    [
      "alpha",
      "beta"
    ],
    "test-model",
    "assistant",
    "sampled text",
    "accept",
    "1234",
    [
      "info:callback-log",
      "notice:callback-log-session"
    ],
    ["memo://alpha"],
    [[
        "file:///workspace",
        "workspace"
      ]]
  ]);
  return await TestSupport.settle([
    Promise.resolve(McpClient.removeNotificationHandlerRaw(client, "message")),
    Promise.resolve(McpClient.removeNotificationHandlerRaw(client, "resourcesUpdated")),
    TestSupport.closeIgnore(McpTestBindings.closeClient(client)),
    TestSupport.closeIgnore(McpTestBindings.closeLowLevelServer(server)),
    TestSupport.closeIgnore(McpTestBindings.transportClose(serverTransport)),
    TestSupport.closeIgnore(McpTestBindings.transportClose(clientTransport))
  ]);
}));

export {
  notificationStringField,
}
/*  Not a pure module */
