// Generated by ReScript, PLEASE EDIT WITH CARE

import * as Vitest from "rescript-vitest/src/Vitest.mjs";
import * as Nodepath from "node:path";
import * as TestSupport from "./TestSupport.mjs";

Vitest.describe("published entrypoints", undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, () => Vitest.test("load under plain node esm resolution", undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, param => {
  TestSupport.importWithNode(Nodepath.join(TestSupport.cwd, "src", "Mcp.mjs"));
  TestSupport.importWithNode(Nodepath.join(TestSupport.cwd, "src", "auth", "McpAuth.mjs"));
  TestSupport.importWithNode(Nodepath.join(TestSupport.cwd, "src", "protocol", "McpProtocol.mjs"));
  TestSupport.importWithNode(Nodepath.join(TestSupport.cwd, "src", "core", "McpCore.mjs"));
  TestSupport.importWithNode(Nodepath.join(TestSupport.cwd, "src", "shared", "McpShared.mjs"));
  TestSupport.importWithNode(Nodepath.join(TestSupport.cwd, "src", "server", "McpServerBindings.mjs"));
  TestSupport.importWithNode(Nodepath.join(TestSupport.cwd, "src", "client", "McpClientBindings.mjs"));
  TestSupport.importWithNode(Nodepath.join(TestSupport.cwd, "src", "transports", "McpTransports.mjs"));
}));

/*  Not a pure module */
