// Generated by ReScript, PLEASE EDIT WITH CARE

import * as Vitest from "rescript-vitest/src/Vitest.mjs";
import * as McpTypes from "../src/core/McpTypes.mjs";
import * as Belt_Array from "@rescript/runtime/lib/es6/Belt_Array.js";
import * as McpJsonValue from "../src/protocol/McpJsonValue.mjs";
import * as McpToolSchema from "../src/protocol/McpToolSchema.mjs";
import * as Stdlib_Option from "@rescript/runtime/lib/es6/Stdlib_Option.js";
import * as McpContentBlock from "../src/protocol/McpContentBlock.mjs";
import * as McpPromptMessage from "../src/protocol/McpPromptMessage.mjs";
import * as Primitive_option from "@rescript/runtime/lib/es6/Primitive_option.js";
import * as McpCallToolParams from "../src/protocol/McpCallToolParams.mjs";
import * as McpCallToolResult from "../src/protocol/McpCallToolResult.mjs";
import * as McpGetPromptResult from "../src/protocol/McpGetPromptResult.mjs";
import * as McpProtocolVersion from "../src/core/McpProtocolVersion.mjs";
import * as McpResourceContents from "../src/protocol/McpResourceContents.mjs";
import * as McpReadResourceResult from "../src/protocol/McpReadResourceResult.mjs";

Vitest.describe("protocol surface", undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, () => {
  Vitest.test("content blocks and resource contents preserve discriminated variants", undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, t => {
    let textResource = McpResourceContents.text("resource://text", "hello", undefined, undefined);
    let blobResource = McpResourceContents.blob("resource://blob", "aGVsbG8=", "application/octet-stream", undefined);
    let textBlock = McpContentBlock.text("hello");
    let imageBlock = McpContentBlock.image("aGVsbG8=", "image/png");
    let audioBlock = McpContentBlock.audio("aGVsbG8=", "audio/wav");
    let resourceLinkBlock = McpContentBlock.resourceLink("resource://guide", "guide", "Guide", "text/plain", 12.0);
    let resourceBlock = McpContentBlock.resource(textResource);
    t.expect([
      McpTypes.latestProtocolVersion === McpTypes.latestProtocolVersion,
      McpTypes.defaultNegotiatedProtocolVersion === McpTypes.defaultNegotiatedProtocolVersion,
      McpTypes.supportedProtocolVersions,
      McpProtocolVersion.latest,
      McpProtocolVersion.defaultNegotiated,
      McpProtocolVersion.toString(McpTypes.latestProtocolVersion),
      McpProtocolVersion.fromString("2025-11-25"),
      McpResourceContents.kind(textResource),
      McpResourceContents.kind(blobResource),
      McpContentBlock.kind(textBlock),
      McpContentBlock.kind(imageBlock),
      McpContentBlock.kind(audioBlock),
      McpContentBlock.kind(resourceLinkBlock),
      McpContentBlock.kind(resourceBlock),
      McpContentBlock.textValue(textBlock),
      McpContentBlock.mimeType(imageBlock),
      McpContentBlock.uri(resourceLinkBlock),
      Stdlib_Option.map(McpContentBlock.resourceValue(resourceBlock), McpResourceContents.uri)
    ]).toEqual([
      true,
      true,
      McpProtocolVersion.supported,
      McpProtocolVersion.latest,
      McpProtocolVersion.defaultNegotiated,
      "2025-11-25",
      "v2025_11_25",
      "text",
      "blob",
      "text",
      "image",
      "audio",
      "resourceLink",
      "resource",
      "hello",
      "image/png",
      "resource://guide",
      "resource://text"
    ]);
  });
  Vitest.test("prompt and result wrappers preserve content, roles, and descriptions", undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, t => {
    let rootBlock = McpContentBlock.text("root-entrypoint");
    let userMessage = McpPromptMessage.text("user", "Review bindings");
    let toolResult = McpCallToolResult.make([McpContentBlock.text("echo:hello")], {
      echoed: "hello"
    }, undefined, undefined);
    let promptResult = McpGetPromptResult.make([userMessage], "Review prompt", undefined);
    let readResult = McpReadResourceResult.make([McpResourceContents.text("config://app", "{\"ok\":true}", "application/json", undefined)]);
    t.expect([
      Primitive_option.fromNullable(rootBlock.text),
      McpPromptMessage.role(userMessage),
      McpContentBlock.textValue(McpPromptMessage.content(userMessage)),
      Belt_Array.keepMap(McpCallToolResult.content(toolResult), McpContentBlock.textValue),
      Stdlib_Option.map(McpCallToolResult.structuredContent(toolResult), value => value.echoed),
      McpGetPromptResult.description(promptResult),
      McpGetPromptResult.messages(promptResult).map(McpPromptMessage.role),
      Belt_Array.keepMap(McpGetPromptResult.messages(promptResult), message => McpContentBlock.textValue(McpPromptMessage.content(message))),
      McpReadResourceResult.contents(readResult).map(McpResourceContents.uri),
      Belt_Array.keepMap(McpReadResourceResult.contents(readResult), McpResourceContents.textValue)
    ]).toEqual([
      "root-entrypoint",
      "user",
      "Review bindings",
      ["echo:hello"],
      "hello",
      "Review prompt",
      ["user"],
      ["Review bindings"],
      ["config://app"],
      ["{\"ok\":true}"]
    ]);
  });
  Vitest.test("call-tool payloads and tool schemas preserve the JSON value algebra", undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, t => {
    let params = McpCallToolParams.make("echo", Object.fromEntries([
      [
        "message",
        McpJsonValue.string("hello")
      ],
      [
        "count",
        McpJsonValue.int(2)
      ],
      [
        "ok",
        McpJsonValue.bool(true)
      ],
      [
        "tags",
        McpJsonValue.array([
          McpJsonValue.string("a"),
          McpJsonValue.string("b")
        ])
      ]
    ]), undefined, undefined, undefined);
    let result = McpCallToolResult.make([McpContentBlock.text("ok")], {
      nested: {
        name: "binding",
        score: 4.5
      }
    }, undefined, undefined);
    let schema = McpToolSchema.make(Object.fromEntries([[
        "message",
        McpJsonValue.object(Object.fromEntries([
          [
            "type",
            McpJsonValue.string("string")
          ],
          [
            "description",
            McpJsonValue.string("Message text")
          ]
        ]))
      ]]), ["message"], undefined);
    t.expect([
      Stdlib_Option.flatMap(McpCallToolParams.argumentValues(params), dict => Stdlib_Option.flatMap(dict["message"], value => {
        if (typeof value !== "object" || value.TAG !== "String") {
          return;
        } else {
          return value._0;
        }
      })),
      Stdlib_Option.flatMap(McpCallToolParams.argumentValues(params), dict => Stdlib_Option.flatMap(dict["count"], value => {
        if (typeof value !== "object" || value.TAG !== "Int") {
          return;
        } else {
          return value._0;
        }
      })),
      Stdlib_Option.map(McpCallToolResult.structuredContent(result), value => value.nested.name),
      Stdlib_Option.flatMap(McpToolSchema.properties(schema), dict => Stdlib_Option.flatMap(dict["message"], value => {
        if (typeof value !== "object" || value.TAG !== "Object") {
          return;
        } else {
          return Stdlib_Option.flatMap(value._0["type"], value => {
            if (typeof value !== "object" || value.TAG !== "String") {
              return;
            } else {
              return value._0;
            }
          });
        }
      })),
      Stdlib_Option.getOr(JSON.stringify(McpJsonValue.toJSON(McpJsonValue.object(Object.fromEntries([[
          "active",
          McpJsonValue.bool(true)
        ]])))), "")
    ]).toEqual([
      "hello",
      2,
      "binding",
      "string",
      "{\"active\":true}"
    ]);
  });
});

let Json;

export {
  Json,
}
/*  Not a pure module */
