// Generated by ReScript, PLEASE EDIT WITH CARE

import * as Vitest from "rescript-vitest/src/Vitest.mjs";
import * as McpIcon from "../src/protocol/McpIcon.mjs";
import * as McpTask from "../src/shared/McpTask.mjs";
import * as McpTool from "../src/server/McpTool.mjs";
import * as Belt_Array from "@rescript/runtime/lib/es6/Belt_Array.js";
import * as McpTaskTool from "../src/server/McpTaskTool.mjs";
import * as McpJsonValue from "../src/protocol/McpJsonValue.mjs";
import * as McpTransport from "../src/shared/McpTransport.mjs";
import * as McpTaskStatus from "../src/shared/McpTaskStatus.mjs";
import * as Stdlib_Option from "@rescript/runtime/lib/es6/Stdlib_Option.js";
import * as McpContentBlock from "../src/protocol/McpContentBlock.mjs";
import * as McpElicitResult from "../src/protocol/McpElicitResult.mjs";
import * as McpTestBindings from "./support/McpTestBindings.mjs";
import * as McpGetTaskResult from "../src/protocol/McpGetTaskResult.mjs";
import * as McpPromptMessage from "../src/protocol/McpPromptMessage.mjs";
import * as McpServerContext from "../src/server/McpServerContext.mjs";
import * as Primitive_option from "@rescript/runtime/lib/es6/Primitive_option.js";
import * as S$RescriptSchema from "rescript-schema/src/S.mjs";
import * as McpCallToolParams from "../src/protocol/McpCallToolParams.mjs";
import * as McpCallToolResult from "../src/protocol/McpCallToolResult.mjs";
import * as McpCompleteParams from "../src/protocol/McpCompleteParams.mjs";
import * as McpLowLevelServer from "../src/server/McpLowLevelServer.mjs";
import * as McpRequestOptions from "../src/shared/McpRequestOptions.mjs";
import * as McpResponseStream from "../src/shared/McpResponseStream.mjs";
import * as McpStandardSchema from "../src/protocol/McpStandardSchema.mjs";
import * as McpGetPromptParams from "../src/protocol/McpGetPromptParams.mjs";
import * as McpListTasksResult from "../src/protocol/McpListTasksResult.mjs";
import * as McpSamplingContent from "../src/protocol/McpSamplingContent.mjs";
import * as McpSamplingMessage from "../src/protocol/McpSamplingMessage.mjs";
import * as McpCancelTaskResult from "../src/protocol/McpCancelTaskResult.mjs";
import * as McpCreateTaskResult from "../src/protocol/McpCreateTaskResult.mjs";
import * as McpModelPreferences from "../src/protocol/McpModelPreferences.mjs";
import * as McpRequestTaskStore from "../src/shared/McpRequestTaskStore.mjs";
import * as McpResourceContents from "../src/protocol/McpResourceContents.mjs";
import * as McpTaskResultStatus from "../src/shared/McpTaskResultStatus.mjs";
import * as McpCreateTaskOptions from "../src/shared/McpCreateTaskOptions.mjs";
import * as McpCreateMessageParams from "../src/protocol/McpCreateMessageParams.mjs";
import * as McpCreateMessageResult from "../src/protocol/McpCreateMessageResult.mjs";
import * as McpTransportSendOptions from "../src/shared/McpTransportSendOptions.mjs";
import * as McpResourceRequestParams from "../src/protocol/McpResourceRequestParams.mjs";
import * as McpElicitRequestUrlParams from "../src/protocol/McpElicitRequestUrlParams.mjs";
import * as McpClientExperimentalTasks from "../src/client/McpClientExperimentalTasks.mjs";
import * as McpElicitRequestFormParams from "../src/protocol/McpElicitRequestFormParams.mjs";
import * as McpLowLevelServerExperimentalTasks from "../src/server/McpLowLevelServerExperimentalTasks.mjs";

let typedOutputSchema = S$RescriptSchema.schema(s => ({
  message: s.m(S$RescriptSchema.string)
}));

let codeFormSchema = S$RescriptSchema.schema(s => ({
  code: s.m(S$RescriptSchema.string)
}));

let outputSchema = McpStandardSchema.fromRescriptSchema(typedOutputSchema);

let meta = Object.fromEntries([[
    "_owner",
    "coverage"
  ]]);

function encodeCursor(cursor) {
  if (cursor !== undefined) {
    return cursor;
  } else {
    return "<none>";
  }
}

function encodePresence(option) {
  if (option !== undefined) {
    return "<some>";
  } else {
    return "<none>";
  }
}

function rawStructuredMessage(result) {
  return Stdlib_Option.flatMap(McpCallToolResult.structuredContentRaw(result), dict => Stdlib_Option.flatMap(dict["message"], value => {
    if (typeof value !== "object" || value.TAG !== "String") {
      return;
    } else {
      return value._0;
    }
  }));
}

function stringField(value, field) {
  return Stdlib_Option.map(value[field], prim => prim);
}

function samplingContentKindString(content) {
  let match = McpSamplingContent.kind(content);
  if (match === "audio") {
    return "audio";
  } else if (match === "image") {
    return "image";
  } else {
    return "text";
  }
}

function samplingMessageKinds(message) {
  let match = McpSamplingMessage.content(message);
  if (match.NAME === "single") {
    return [samplingContentKindString(match.VAL)];
  } else {
    return match.VAL.map(samplingContentKindString);
  }
}

Vitest.describe("public wrapper coverage", undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, () => {
  Vitest.test("protocol builders preserve public typed fields", undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, t => {
    let workingTask = {
      taskId: "task-1",
      status: "working",
      ttl: 5000,
      createdAt: "2026-04-24T00:00:00Z",
      lastUpdatedAt: "2026-04-24T00:00:10Z",
      pollInterval: 250,
      statusMessage: "running"
    };
    let cancelledTask = {
      taskId: "task-2",
      status: "cancelled",
      createdAt: "2026-04-24T00:01:00Z",
      lastUpdatedAt: "2026-04-24T00:01:10Z"
    };
    let completeArgument = McpCompleteParams.makeArgument("topic", "bindings", undefined);
    let completeContext = McpCompleteParams.makeContext(Object.fromEntries([[
        "extra",
        "context"
      ]]), undefined);
    let completePrompt = McpCompleteParams.makeWithPrompt(McpCompleteParams.promptReference("review"), completeArgument, Primitive_option.some(completeContext), meta, undefined);
    let completeResource = McpCompleteParams.makeWithResource(McpCompleteParams.resourceReference("memo://alpha"), completeArgument, undefined, undefined, undefined);
    let callParams = McpCallToolParams.make("echo", Object.fromEntries([[
        "message",
        McpJsonValue.string("hello")
      ]]), Primitive_option.some(McpCreateTaskOptions.make(60, 5, undefined, undefined)), meta, undefined);
    let promptParams = McpGetPromptParams.make("summary", Object.fromEntries([[
        "topic",
        "bindings"
      ]]), meta, undefined);
    let resourceParams = McpResourceRequestParams.make("memo://alpha", meta, undefined);
    let icon = McpIcon.make("icon.svg", "image/svg+xml", [
      "16x16",
      "32x32"
    ], "dark", undefined);
    let promptMessage = McpPromptMessage.make("assistant", McpContentBlock.text("inspect"));
    let promptText = McpPromptMessage.text("user", "review");
    let textContents = McpResourceContents.text("memo://alpha", "alpha", "text/plain", undefined);
    let blobContents = McpResourceContents.blob("memo://beta", "YmV0YQ==", undefined, undefined);
    let createTaskResult = McpCreateTaskResult.make(workingTask, undefined);
    let getTaskResult = McpGetTaskResult.make("task-1", "working", 5000, "2026-04-24T00:00:00Z", "2026-04-24T00:00:10Z", 250, "running", undefined);
    let getTaskResultFromTask = McpGetTaskResult.ofTask(workingTask);
    let cancelTaskResult = McpCancelTaskResult.make("task-2", "cancelled", undefined, "2026-04-24T00:01:00Z", "2026-04-24T00:01:10Z", undefined, undefined, undefined);
    let cancelTaskResultFromTask = McpCancelTaskResult.ofTask(cancelledTask);
    let listTasksResult = McpListTasksResult.make([
      workingTask,
      cancelledTask
    ], "cursor-2", undefined);
    t.expect([
      McpCompleteParams.argumentName(McpCompleteParams.argumentValue(completePrompt)),
      McpCompleteParams.argumentCurrentValue(McpCompleteParams.argumentValue(completePrompt)),
      Stdlib_Option.flatMap(McpCompleteParams.contextValue(completePrompt), context => Stdlib_Option.flatMap(McpCompleteParams.contextArguments(context), args => args["extra"])),
      Stdlib_Option.flatMap(McpCompleteParams.meta(completePrompt), meta => Stdlib_Option.map(meta["_owner"], prim => prim)),
      Stdlib_Option.flatMap(completePrompt["ref"], ref => Stdlib_Option.map(ref["type"], prim => prim)),
      Stdlib_Option.flatMap(completeResource["ref"], ref => Stdlib_Option.map(ref["uri"], prim => prim)),
      McpCallToolParams.name(callParams),
      Stdlib_Option.flatMap(McpCallToolParams.argumentValues(callParams), args => Stdlib_Option.flatMap(args["message"], value => {
        if (typeof value !== "object" || value.TAG !== "String") {
          return;
        } else {
          return value._0;
        }
      })),
      McpCallToolParams.task(callParams) !== undefined,
      Stdlib_Option.flatMap(McpCallToolParams.meta(callParams), meta => Stdlib_Option.map(meta["_owner"], prim => prim)),
      McpGetPromptParams.name(promptParams),
      Stdlib_Option.flatMap(McpGetPromptParams.argumentValues(promptParams), args => args["topic"]),
      Stdlib_Option.flatMap(McpGetPromptParams.meta(promptParams), meta => Stdlib_Option.map(meta["_owner"], prim => prim)),
      McpResourceRequestParams.uri(resourceParams),
      Stdlib_Option.flatMap(McpResourceRequestParams.meta(resourceParams), meta => Stdlib_Option.map(meta["_owner"], prim => prim)),
      McpIcon.src(icon),
      McpIcon.mimeType(icon),
      Stdlib_Option.map(McpIcon.sizes(icon), prim => prim.length),
      McpIcon.theme(icon),
      McpPromptMessage.role(promptMessage),
      McpContentBlock.textValue(McpPromptMessage.content(promptMessage)),
      McpPromptMessage.role(promptText),
      McpContentBlock.textValue(McpPromptMessage.content(promptText)),
      McpResourceContents.kind(textContents),
      McpResourceContents.textValue(textContents),
      McpResourceContents.kind(blobContents),
      McpResourceContents.blobValue(blobContents),
      McpTask.taskId(McpCreateTaskResult.task(createTaskResult)),
      McpGetTaskResult.status(getTaskResult),
      McpGetTaskResult.ttl(getTaskResult),
      McpGetTaskResult.pollInterval(getTaskResult),
      McpGetTaskResult.statusMessage(getTaskResultFromTask),
      McpCancelTaskResult.status(cancelTaskResult),
      McpCancelTaskResult.status(cancelTaskResultFromTask),
      McpListTasksResult.tasks(listTasksResult).map(McpTask.taskId),
      McpListTasksResult.nextCursor(listTasksResult),
      McpTask.status(workingTask),
      McpTask.statusMessage(workingTask),
      McpTaskStatus.toString("inputRequired"),
      McpTaskStatus.fromString("completed"),
      McpTaskStatus.isTerminal("completed"),
      McpTaskStatus.isTerminal("working"),
      McpTaskResultStatus.toString("failed"),
      McpTaskResultStatus.fromString("completed")
    ]).toEqual([
      "topic",
      "bindings",
      "context",
      "coverage",
      "ref/prompt",
      "memo://alpha",
      "echo",
      "hello",
      true,
      "coverage",
      "summary",
      "bindings",
      "coverage",
      "memo://alpha",
      "coverage",
      "icon.svg",
      "image/svg+xml",
      2,
      "dark",
      "assistant",
      "inspect",
      "user",
      "review",
      "text",
      "alpha",
      "blob",
      "YmV0YQ==",
      "task-1",
      "working",
      5000,
      250,
      "running",
      "cancelled",
      "cancelled",
      [
        "task-1",
        "task-2"
      ],
      "cursor-2",
      "working",
      "running",
      "input_required",
      "completed",
      true,
      false,
      "failed",
      "completed"
    ]);
  });
  Vitest.testAsync("typed tool and task-tool wrappers keep typed output on the public path", undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, async t => {
    let abortController = new AbortController();
    let serverContext = {
      mcpReq: {
        id: 1,
        method: "tools/call",
        signal: abortController.signal
      }
    };
    let workingTask = {
      taskId: "task-typed",
      status: "working",
      createdAt: "2026-04-24T00:02:00Z",
      lastUpdatedAt: "2026-04-24T00:02:10Z"
    };
    let toolConfig = McpTool.makeConfig("Echo", undefined, undefined, outputSchema, undefined, meta, undefined);
    let rawToolConfig = McpTool.makeRawConfig("Raw Echo", undefined, undefined, undefined, meta, undefined);
    let typedUpdates = McpTool.makeUpdates("echo", undefined, undefined, undefined, outputSchema, undefined, meta, async (value, _ctx) => McpCallToolResult.make([McpContentBlock.text(`typed:` + value)], {
      message: value
    }, undefined, undefined), undefined, undefined);
    let typedUpdates0 = McpTool.makeUpdates0("echo0", undefined, undefined, outputSchema, undefined, undefined, async _ctx => McpCallToolResult.make([McpContentBlock.text("typed:zero")], {
      message: "zero"
    }, undefined, undefined), undefined, undefined);
    let rawUpdates = McpTool.makeRawUpdates("raw", undefined, undefined, undefined, undefined, undefined, async (value, _ctx) => McpCallToolResult.makeRaw([McpContentBlock.text(`raw:` + value)], Object.fromEntries([[
        "message",
        McpJsonValue.string(value)
      ]]), undefined, undefined), undefined, undefined);
    let rawUpdates0 = McpTool.makeRawUpdates0("raw0", undefined, undefined, undefined, undefined, async _ctx => McpCallToolResult.makeRaw([McpContentBlock.text("raw:zero")], Object.fromEntries([[
        "message",
        McpJsonValue.string("zero")
      ]]), undefined, undefined), undefined, undefined);
    let typedUpdate = McpTestBindings.getSome(Primitive_option.fromNullable(typedUpdates.callback));
    let typedUpdate0 = McpTestBindings.getSome(Primitive_option.fromNullable(typedUpdates0.callback));
    let rawUpdate = McpTestBindings.getSome(Primitive_option.fromNullable(rawUpdates.callback));
    let rawUpdate0 = McpTestBindings.getSome(Primitive_option.fromNullable(rawUpdates0.callback));
    let typedUpdateResult = await typedUpdate("hello", serverContext);
    let typedUpdate0Result = await typedUpdate0(serverContext);
    let rawUpdateResult = await rawUpdate("raw-hello", serverContext);
    let rawUpdate0Result = await rawUpdate0(serverContext);
    let toolCounts = {
      contents: [
        0,
        0,
        0,
        0
      ]
    };
    let registered = {
      enable: () => {
        let match = toolCounts.contents;
        toolCounts.contents = [
          match[0] + 1 | 0,
          match[1],
          match[2],
          match[3]
        ];
      },
      disable: () => {
        let match = toolCounts.contents;
        toolCounts.contents = [
          match[0],
          match[1] + 1 | 0,
          match[2],
          match[3]
        ];
      },
      update: param => {
        let match = toolCounts.contents;
        toolCounts.contents = [
          match[0],
          match[1],
          match[2] + 1 | 0,
          match[3]
        ];
      },
      remove: () => {
        let match = toolCounts.contents;
        toolCounts.contents = [
          match[0],
          match[1],
          match[2],
          match[3] + 1 | 0
        ];
      }
    };
    McpTool.enable(registered);
    McpTool.disable(registered);
    McpTool.update(registered, typedUpdates);
    McpTool.updateRaw(registered, rawUpdates);
    McpTool.update0(registered, typedUpdates0);
    McpTool.updateRaw0(registered, rawUpdates0);
    McpTool.remove(registered);
    let execution = McpTaskTool.makeExecution("required", undefined);
    let taskToolConfig = McpTaskTool.makeConfig("Task Echo", undefined, undefined, outputSchema, undefined, Primitive_option.some(execution), meta, undefined);
    let rawTaskToolConfig = McpTaskTool.makeRawConfig("Raw Task Echo", undefined, undefined, undefined, Primitive_option.some(execution), meta, undefined);
    let taskHandler = McpTaskTool.makeHandler(async (_value, _ctx) => McpCreateTaskResult.make(workingTask, undefined), async (_value, _ctx) => McpGetTaskResult.ofTask(workingTask), async (value, _ctx) => McpCallToolResult.make([McpContentBlock.text(`task:` + value)], {
      message: value
    }, undefined, undefined), undefined);
    let rawTaskHandler = McpTaskTool.makeRawHandler(async (_value, _ctx) => McpCreateTaskResult.make(workingTask, undefined), async (_value, _ctx) => McpGetTaskResult.ofTask(workingTask), async (value, _ctx) => McpCallToolResult.makeRaw([McpContentBlock.text(`raw-task:` + value)], Object.fromEntries([[
        "message",
        McpJsonValue.string(value)
      ]]), undefined, undefined), undefined);
    let taskHandler0 = McpTaskTool.makeHandler0(async _ctx => McpCreateTaskResult.make(workingTask, undefined), async _ctx => McpGetTaskResult.ofTask(workingTask), async _ctx => McpCallToolResult.make([McpContentBlock.text("task:zero")], {
      message: "zero-task"
    }, undefined, undefined), undefined);
    let rawTaskHandler0 = McpTaskTool.makeRawHandler0(async _ctx => McpCreateTaskResult.make(workingTask, undefined), async _ctx => McpGetTaskResult.ofTask(workingTask), async _ctx => McpCallToolResult.makeRaw([McpContentBlock.text("raw-task:zero")], Object.fromEntries([[
        "message",
        McpJsonValue.string("zero-raw")
      ]]), undefined, undefined), undefined);
    let createTask = taskHandler.createTask;
    let getTask = taskHandler.getTask;
    let getTaskResult = taskHandler.getTaskResult;
    let getRawTaskResult = rawTaskHandler.getTaskResult;
    let getTaskResult0 = taskHandler0.getTaskResult;
    let getRawTaskResult0 = rawTaskHandler0.getTaskResult;
    let taskCreateResult = await createTask("ignored", serverContext);
    let taskGetResult = await getTask("ignored", serverContext);
    let taskTypedResult = await getTaskResult("typed-task", serverContext);
    let taskRawResult = await getRawTaskResult("raw-task", serverContext);
    let taskTyped0Result = await getTaskResult0(serverContext);
    let taskRaw0Result = await getRawTaskResult0(serverContext);
    return t.expect([
      toolConfig["outputSchema"] !== undefined,
      rawToolConfig["outputSchema"] === undefined,
      rawStructuredMessage(typedUpdateResult),
      rawStructuredMessage(typedUpdate0Result),
      rawStructuredMessage(rawUpdateResult),
      rawStructuredMessage(rawUpdate0Result),
      toolCounts.contents,
      stringField(execution, "taskSupport"),
      taskToolConfig["outputSchema"] !== undefined,
      rawTaskToolConfig["outputSchema"] === undefined,
      McpTask.taskId(McpCreateTaskResult.task(taskCreateResult)),
      McpGetTaskResult.status(taskGetResult),
      Stdlib_Option.map(McpCallToolResult.structuredContent(taskTypedResult), value => value.message),
      rawStructuredMessage(taskRawResult),
      Stdlib_Option.map(McpCallToolResult.structuredContent(taskTyped0Result), value => value.message),
      rawStructuredMessage(taskRaw0Result)
    ]).toEqual([
      true,
      true,
      "hello",
      "zero",
      "raw-hello",
      "zero",
      [
        1,
        1,
        4,
        1
      ],
      "required",
      true,
      true,
      "task-typed",
      "working",
      "typed-task",
      "raw-task",
      "zero-task",
      "zero-raw"
    ]);
  });
  Vitest.test("sampling and elicitation protocol builders preserve typed public fields", undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, t => {
    let hint = McpModelPreferences.makeHint("gpt-4.1", undefined);
    let modelPreferences = McpModelPreferences.make([hint], 0.25, 0.5, 0.75, undefined);
    let singleMessage = McpSamplingMessage.text("user", "hello");
    let manyMessage = McpSamplingMessage.makeMany("assistant", [
      McpSamplingContent.image("aW1hZ2U=", "image/png"),
      McpSamplingContent.audio("YXVkaW8=", "audio/wav")
    ], undefined);
    let createMessageParams = McpCreateMessageParams.make([
      singleMessage,
      manyMessage
    ], 128, Primitive_option.some(modelPreferences), "system", "allServers", 0.2, ["END"], meta, meta, undefined);
    let createMessageResult = McpCreateMessageResult.make("gpt-4.1", "assistant", McpSamplingContent.text("reply"), "endTurn", meta, undefined);
    let formParams = McpElicitRequestFormParams.make("Provide a code", McpStandardSchema.jsonSchemaOfRescriptSchema(codeFormSchema), meta, undefined);
    let urlParams = McpElicitRequestUrlParams.make("Open the verifier", "elic-1", "https://example.com", meta, undefined);
    let elicitationResult = McpElicitResult.make("accept", Object.fromEntries([[
        "code",
        "1234"
      ]]), meta, undefined);
    t.expect([
      Stdlib_Option.map(McpModelPreferences.hints(modelPreferences), prim => prim.length),
      McpModelPreferences.costPriority(modelPreferences),
      McpModelPreferences.speedPriority(modelPreferences),
      McpModelPreferences.intelligencePriority(modelPreferences),
      McpModelPreferences.hintName(hint),
      McpCreateMessageParams.messages(createMessageParams).map(message => [
        McpSamplingMessage.role(message),
        samplingMessageKinds(message)
      ]),
      McpCreateMessageParams.maxTokens(createMessageParams),
      Stdlib_Option.flatMap(McpCreateMessageParams.modelPreferences(createMessageParams), preferences => Stdlib_Option.flatMap(McpModelPreferences.hints(preferences), hints => Stdlib_Option.flatMap(hints[0], McpModelPreferences.hintName))),
      McpCreateMessageParams.systemPrompt(createMessageParams),
      McpCreateMessageParams.includeContext(createMessageParams),
      McpCreateMessageParams.temperature(createMessageParams),
      McpCreateMessageParams.stopSequences(createMessageParams),
      Stdlib_Option.flatMap(McpCreateMessageParams.metadata(createMessageParams), metadata => Stdlib_Option.map(metadata["_owner"], prim => prim)),
      Stdlib_Option.flatMap(McpCreateMessageParams.meta(createMessageParams), metadata => Stdlib_Option.map(metadata["_owner"], prim => prim)),
      McpCreateMessageResult.model(createMessageResult),
      McpCreateMessageResult.role(createMessageResult),
      McpSamplingContent.kind(McpCreateMessageResult.content(createMessageResult)),
      McpSamplingContent.textValue(McpCreateMessageResult.content(createMessageResult)),
      McpCreateMessageResult.stopReason(createMessageResult),
      Stdlib_Option.flatMap(McpCreateMessageResult.meta(createMessageResult), metadata => Stdlib_Option.map(metadata["_owner"], prim => prim)),
      McpElicitRequestFormParams.message(formParams),
      Stdlib_Option.map(McpElicitRequestFormParams.requestedSchema(formParams)["type"], prim => prim),
      Stdlib_Option.flatMap(McpElicitRequestFormParams.meta(formParams), metadata => Stdlib_Option.map(metadata["_owner"], prim => prim)),
      McpElicitRequestUrlParams.message(urlParams),
      McpElicitRequestUrlParams.elicitationId(urlParams),
      McpElicitRequestUrlParams.url(urlParams),
      Stdlib_Option.flatMap(McpElicitRequestUrlParams.meta(urlParams), metadata => Stdlib_Option.map(metadata["_owner"], prim => prim)),
      McpElicitResult.action(elicitationResult),
      Stdlib_Option.flatMap(McpElicitResult.content(elicitationResult), content => Stdlib_Option.map(content["code"], prim => prim)),
      Stdlib_Option.flatMap(McpElicitResult.meta(elicitationResult), metadata => Stdlib_Option.map(metadata["_owner"], prim => prim))
    ]).toEqual([
      1,
      0.25,
      0.5,
      0.75,
      "gpt-4.1",
      [
        [
          "user",
          ["text"]
        ],
        [
          "assistant",
          [
            "image",
            "audio"
          ]
        ]
      ],
      128,
      "gpt-4.1",
      "system",
      "allServers",
      0.2,
      ["END"],
      "coverage",
      "coverage",
      "gpt-4.1",
      "assistant",
      "text",
      "reply",
      "endTurn",
      "coverage",
      "Provide a code",
      "object",
      "coverage",
      "Open the verifier",
      "elic-1",
      "https://example.com",
      "coverage",
      "accept",
      "1234",
      "coverage"
    ]);
  });
  Vitest.testAsync("typed sampling and elicitation wrappers dispatch through low-level and context objects", undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, async t => {
    let options = McpRequestOptions.make(undefined, undefined, 750, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined);
    let createCalls = {
      contents: []
    };
    let elicitCalls = {
      contents: []
    };
    let createResult = McpCreateMessageResult.make("fixture-model", "assistant", McpSamplingContent.text("typed reply"), "stopSequence", undefined, undefined);
    let formResult = McpElicitResult.make("accept", Object.fromEntries([[
        "code",
        "alpha"
      ]]), undefined, undefined);
    let urlResult = McpElicitResult.make("decline", undefined, undefined, undefined);
    let createRequest = McpCreateMessageParams.make([McpSamplingMessage.text("user", "hello fixture")], 64, undefined, undefined, "thisServer", undefined, undefined, undefined, meta, undefined);
    let formParams = McpElicitRequestFormParams.make("Need form data", McpStandardSchema.jsonSchemaOfRescriptSchema(codeFormSchema), undefined, undefined);
    let urlParams = McpElicitRequestUrlParams.make("Need URL confirmation", "elic-fixture", "https://example.com/fixture", undefined, undefined);
    let lowLevelServer = {
      createMessage: (params, requestOptions) => {
        createCalls.contents = Belt_Array.concatMany([
          [[
              McpCreateMessageParams.maxTokens(params),
              McpCreateMessageParams.includeContext(params),
              requestOptions !== undefined
            ]],
          createCalls.contents
        ]);
        return (async () => createResult)();
      },
      elicitInput: (params, requestOptions) => {
        let mode = Stdlib_Option.getOr(Stdlib_Option.map(params["mode"], prim => prim), "form");
        elicitCalls.contents = Belt_Array.concatMany([
          [[
              mode,
              requestOptions !== undefined
            ]],
          elicitCalls.contents
        ]);
        return (async () => {
          if (mode === "url") {
            return urlResult;
          } else {
            return formResult;
          }
        })();
      }
    };
    let abortController = new AbortController();
    let context = {
      mcpReq: {
        id: 1,
        method: "tools/call",
        signal: abortController.signal,
        requestSampling: (params, requestOptions) => {
          createCalls.contents = Belt_Array.concatMany([
            [[
                McpCreateMessageParams.maxTokens(params),
                McpCreateMessageParams.includeContext(params),
                requestOptions !== undefined
              ]],
            createCalls.contents
          ]);
          return (async () => createResult)();
        },
        elicitInput: (params, requestOptions) => {
          let mode = Stdlib_Option.getOr(Stdlib_Option.map(params["mode"], prim => prim), "form");
          elicitCalls.contents = Belt_Array.concatMany([
            [[
                mode,
                requestOptions !== undefined
              ]],
            elicitCalls.contents
          ]);
          return (async () => {
            if (mode === "url") {
              return urlResult;
            } else {
              return formResult;
            }
          })();
        }
      }
    };
    let typedCreate = await McpLowLevelServer.createMessage(lowLevelServer, createRequest);
    let typedCreateWithOptions = await McpLowLevelServer.createMessageWithOptions(lowLevelServer, createRequest, options);
    let rawCreate = await McpLowLevelServer.createMessageRaw(lowLevelServer, createRequest);
    let rawCreateWithOptions = await McpLowLevelServer.createMessageRawWithOptions(lowLevelServer, createRequest, options);
    let typedForm = await McpLowLevelServer.elicitFormInput(lowLevelServer, formParams);
    let typedFormWithOptions = await McpLowLevelServer.elicitFormInputWithOptions(lowLevelServer, formParams, options);
    let typedUrl = await McpLowLevelServer.elicitUrlInput(lowLevelServer, urlParams);
    let typedUrlWithOptions = await McpLowLevelServer.elicitUrlInputWithOptions(lowLevelServer, urlParams, options);
    let rawElicit = await McpLowLevelServer.elicitInputRaw(lowLevelServer, formParams);
    let rawElicitWithOptions = await McpLowLevelServer.elicitInputRawWithOptions(lowLevelServer, urlParams, options);
    let contextTypedCreate = await McpServerContext.requestSampling(context, createRequest);
    let contextTypedCreateWithOptions = await McpServerContext.requestSamplingWithOptions(context, createRequest, options);
    let contextRawCreate = await McpServerContext.requestSamplingRaw(context, createRequest);
    let contextRawCreateWithOptions = await McpServerContext.requestSamplingRawWithOptions(context, createRequest, options);
    let contextTypedForm = await McpServerContext.elicitFormInput(context, formParams);
    let contextTypedFormWithOptions = await McpServerContext.elicitFormInputWithOptions(context, formParams, options);
    let contextTypedUrl = await McpServerContext.elicitUrlInput(context, urlParams);
    let contextTypedUrlWithOptions = await McpServerContext.elicitUrlInputWithOptions(context, urlParams, options);
    let contextRawElicit = await McpServerContext.elicitInputRaw(context, formParams);
    let contextRawElicitWithOptions = await McpServerContext.elicitInputRawWithOptions(context, urlParams, options);
    return t.expect([
      McpSamplingContent.textValue(McpCreateMessageResult.content(typedCreate)),
      McpCreateMessageResult.stopReason(typedCreateWithOptions),
      stringField(rawCreate, "model"),
      stringField(rawCreateWithOptions, "model"),
      McpElicitResult.action(typedForm),
      Stdlib_Option.flatMap(McpElicitResult.content(typedFormWithOptions), content => Stdlib_Option.map(content["code"], prim => prim)),
      McpElicitResult.action(typedUrl),
      McpElicitResult.action(typedUrlWithOptions),
      stringField(rawElicit, "action"),
      stringField(rawElicitWithOptions, "action"),
      McpSamplingContent.textValue(McpCreateMessageResult.content(contextTypedCreate)),
      McpCreateMessageResult.stopReason(contextTypedCreateWithOptions),
      stringField(contextRawCreate, "model"),
      stringField(contextRawCreateWithOptions, "model"),
      McpElicitResult.action(contextTypedForm),
      Stdlib_Option.flatMap(McpElicitResult.content(contextTypedFormWithOptions), content => Stdlib_Option.map(content["code"], prim => prim)),
      McpElicitResult.action(contextTypedUrl),
      McpElicitResult.action(contextTypedUrlWithOptions),
      stringField(contextRawElicit, "action"),
      stringField(contextRawElicitWithOptions, "action"),
      createCalls.contents,
      elicitCalls.contents
    ]).toEqual([
      "typed reply",
      "stopSequence",
      "fixture-model",
      "fixture-model",
      "accept",
      "alpha",
      "decline",
      "decline",
      "accept",
      "decline",
      "typed reply",
      "stopSequence",
      "fixture-model",
      "fixture-model",
      "accept",
      "alpha",
      "decline",
      "decline",
      "accept",
      "decline",
      [
        [
          64,
          "thisServer",
          true
        ],
        [
          64,
          "thisServer",
          false
        ],
        [
          64,
          "thisServer",
          true
        ],
        [
          64,
          "thisServer",
          false
        ],
        [
          64,
          "thisServer",
          true
        ],
        [
          64,
          "thisServer",
          false
        ],
        [
          64,
          "thisServer",
          true
        ],
        [
          64,
          "thisServer",
          false
        ]
      ],
      [
        [
          "url",
          true
        ],
        [
          "form",
          false
        ],
        [
          "url",
          true
        ],
        [
          "url",
          false
        ],
        [
          "form",
          true
        ],
        [
          "form",
          false
        ],
        [
          "url",
          true
        ],
        [
          "form",
          false
        ],
        [
          "url",
          true
        ],
        [
          "url",
          false
        ],
        [
          "form",
          true
        ],
        [
          "form",
          false
        ]
      ]
    ]);
  });
  Vitest.testAsync("task-store transport and response-stream wrappers dispatch through runtime objects", undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, async t => {
    let storeTask = {
      taskId: "stored-task",
      status: "working",
      ttl: 1200,
      createdAt: "2026-04-24T00:03:00Z",
      lastUpdatedAt: "2026-04-24T00:03:01Z",
      pollInterval: 20,
      statusMessage: "queued"
    };
    let listResult = McpListTasksResult.make([storeTask], "next-store", undefined);
    let storedStatuses = {
      contents: []
    };
    let storedMessages = {
      contents: []
    };
    let listCursors = {
      contents: []
    };
    let store = {
      createTask: async _params => storeTask,
      getTask: async _taskId => storeTask,
      storeTaskResult: async (_taskId, status, result) => {
        storedStatuses.contents = Belt_Array.concatMany([
          [status],
          storedStatuses.contents
        ]);
        storedMessages.contents = Belt_Array.concatMany([
          [Stdlib_Option.getOr(rawStructuredMessage(result), "missing")],
          storedMessages.contents
        ]);
      },
      getTaskResult: async _taskId => McpCallToolResult.makeRaw([McpContentBlock.text("stored")], Object.fromEntries([[
          "message",
          McpJsonValue.string("stored")
        ]]), undefined, undefined),
      updateTaskStatus: async (_taskId, _status, _statusMessage) => {},
      listTasks: cursor => {
        listCursors.contents = Belt_Array.concatMany([
          [cursor !== undefined ? cursor : "<none>"],
          listCursors.contents
        ]);
        return (async () => listResult)();
      }
    };
    let typedResult = await McpRequestTaskStore.getTaskResult(store, "stored-task", outputSchema);
    let rawStoredResult = await McpRequestTaskStore.getTaskResultRaw(store, "stored-task");
    await McpRequestTaskStore.createTask(store, McpCreateTaskOptions.make(1200, 20, undefined, undefined));
    await McpRequestTaskStore.getTask(store, "stored-task");
    await McpRequestTaskStore.storeTaskResult(store, "stored-task", "completed", McpCallToolResult.make([McpContentBlock.text("typed-store")], {
      message: "typed-store"
    }, undefined, undefined), outputSchema);
    await McpRequestTaskStore.storeTaskResultRaw(store, "stored-task", "failed", McpCallToolResult.makeRaw([McpContentBlock.text("raw-store")], Object.fromEntries([[
        "message",
        McpJsonValue.string("raw-store")
      ]]), undefined, undefined));
    await McpRequestTaskStore.updateTaskStatus(store, "stored-task", "working", "running");
    let listed = await McpRequestTaskStore.listTasks(store);
    let listedWithCursor = await McpRequestTaskStore.listTasksWithCursor(store, "cursor-1");
    let transportCalls = {
      contents: [
        0,
        0
      ]
    };
    let sendKinds = {
      contents: []
    };
    let sendOptions = {
      contents: []
    };
    let transport = {
      start: async () => {
        let match = transportCalls.contents;
        transportCalls.contents = [
          match[0] + 1 | 0,
          match[1]
        ];
      },
      close: async () => {
        let match = transportCalls.contents;
        transportCalls.contents = [
          match[0],
          match[1] + 1 | 0
        ];
      },
      send: async (payload, options) => {
        sendKinds.contents = Belt_Array.concatMany([
          [Stdlib_Option.getOr(Stdlib_Option.map(payload["kind"], prim => prim), "missing")],
          sendKinds.contents
        ]);
        sendOptions.contents = Belt_Array.concatMany([
          [encodePresence(options)],
          sendOptions.contents
        ]);
      },
      sessionId: "transport-session"
    };
    await McpTransport.start(transport);
    await McpTransport.send(transport, Object.fromEntries([[
        "kind",
        "plain"
      ]]));
    await McpTransport.sendWithOptions(transport, Object.fromEntries([[
        "kind",
        "with-options"
      ]]), McpTransportSendOptions.make(undefined, "resume-1", undefined, undefined));
    await McpTransport.close(transport);
    let taskCreatedMessage = {
      type: "taskCreated",
      task: storeTask
    };
    let taskStatusMessage = {
      type: "taskStatus",
      task: storeTask
    };
    let resultMessage = {
      type: "result",
      result: "stream-result"
    };
    let errorMessage = {
      type: "error",
      error: "stream-error"
    };
    return t.expect([
      Stdlib_Option.map(McpCallToolResult.structuredContent(typedResult), value => value.message),
      rawStructuredMessage(rawStoredResult),
      storedStatuses.contents,
      storedMessages.contents,
      McpListTasksResult.nextCursor(listed),
      McpListTasksResult.tasks(listedWithCursor).map(McpTask.taskId),
      listCursors.contents,
      McpTransport.sessionId(transport),
      transportCalls.contents,
      sendKinds.contents,
      sendOptions.contents,
      [
        McpResponseStream.kind(taskCreatedMessage),
        McpResponseStream.kind(taskStatusMessage),
        McpResponseStream.kind(resultMessage),
        McpResponseStream.kind(errorMessage)
      ],
      Stdlib_Option.map(McpResponseStream.task(taskCreatedMessage), McpTask.taskId),
      Stdlib_Option.map(McpResponseStream.result(resultMessage), prim => prim),
      Stdlib_Option.map(McpResponseStream.error(errorMessage), prim => prim)
    ]).toEqual([
      "stored",
      "stored",
      [
        "failed",
        "completed"
      ],
      [
        "raw-store",
        "typed-store"
      ],
      "next-store",
      ["stored-task"],
      [
        "cursor-1",
        "<none>"
      ],
      "transport-session",
      [
        1,
        1
      ],
      [
        "with-options",
        "plain"
      ],
      [
        "<some>",
        "<none>"
      ],
      [
        "taskCreated",
        "taskStatus",
        "result",
        "error"
      ],
      "stored-task",
      "stream-result",
      "stream-error"
    ]);
  });
  Vitest.testAsync("experimental task wrappers dispatch through the installed public task methods", undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, async t => {
    let workingTask = {
      taskId: "exp-task",
      status: "working",
      createdAt: "2026-04-24T00:04:00Z",
      lastUpdatedAt: "2026-04-24T00:04:01Z"
    };
    let cancelledTask = {
      taskId: "exp-cancelled",
      status: "cancelled",
      createdAt: "2026-04-24T00:04:10Z",
      lastUpdatedAt: "2026-04-24T00:04:11Z"
    };
    let listResult = McpListTasksResult.make([workingTask], "exp-next", undefined);
    let clientStream = {
      label: "client-stream"
    };
    let serverStream = {
      label: "server-stream"
    };
    let options = McpRequestOptions.make(undefined, undefined, 1000, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined);
    let clientCallNames = {
      contents: []
    };
    let clientRequestMethods = {
      contents: []
    };
    let clientListCursors = {
      contents: []
    };
    let serverRequestMethods = {
      contents: []
    };
    let serverCreateKinds = {
      contents: []
    };
    let serverElicitKinds = {
      contents: []
    };
    let serverListCursors = {
      contents: []
    };
    let clientTasks = {
      callToolStream: (params, _options) => {
        clientCallNames.contents = Belt_Array.concatMany([
          [Stdlib_Option.getOr(Stdlib_Option.map(params["name"], prim => prim), "missing")],
          clientCallNames.contents
        ]);
        return clientStream;
      },
      requestStream: (request, _options) => {
        clientRequestMethods.contents = Belt_Array.concatMany([
          [request.method],
          clientRequestMethods.contents
        ]);
        return clientStream;
      },
      getTask: (_taskId, _options) => (async () => McpGetTaskResult.ofTask(workingTask))(),
      getTaskResult: (_taskId, _options) => (async () => "client-raw")(),
      listTasks: (cursor, _options) => {
        clientListCursors.contents = Belt_Array.concatMany([
          [cursor !== undefined ? cursor : "<none>"],
          clientListCursors.contents
        ]);
        return (async () => listResult)();
      },
      cancelTask: (_taskId, _options) => (async () => McpCancelTaskResult.ofTask(cancelledTask))()
    };
    let serverTasks = {
      requestStream: (request, _options) => {
        serverRequestMethods.contents = Belt_Array.concatMany([
          [request.method],
          serverRequestMethods.contents
        ]);
        return serverStream;
      },
      createMessageStream: (params, _options) => {
        serverCreateKinds.contents = Belt_Array.concatMany([
          [Stdlib_Option.getOr(Stdlib_Option.map(params["kind"], prim => prim), "missing")],
          serverCreateKinds.contents
        ]);
        return serverStream;
      },
      elicitInputStream: (params, _options) => {
        serverElicitKinds.contents = Belt_Array.concatMany([
          [Stdlib_Option.getOr(Stdlib_Option.map(params["kind"], prim => prim), "missing")],
          serverElicitKinds.contents
        ]);
        return serverStream;
      },
      getTask: (_taskId, _options) => (async () => McpGetTaskResult.ofTask(workingTask))(),
      getTaskResult: (_taskId, _options) => (async () => "server-raw")(),
      listTasks: (cursor, _options) => {
        serverListCursors.contents = Belt_Array.concatMany([
          [cursor !== undefined ? cursor : "<none>"],
          serverListCursors.contents
        ]);
        return (async () => listResult)();
      },
      cancelTask: (_taskId, _options) => (async () => McpCancelTaskResult.ofTask(cancelledTask))()
    };
    McpClientExperimentalTasks.callToolStreamRaw(clientTasks, Object.fromEntries([[
        "name",
        "echo"
      ]]));
    McpClientExperimentalTasks.callToolStreamRawWithOptions(clientTasks, Object.fromEntries([[
        "name",
        "echo"
      ]]), options);
    McpClientExperimentalTasks.requestStreamRaw(clientTasks, "toolsCall", Object.fromEntries([[
        "kind",
        "client"
      ]]));
    McpClientExperimentalTasks.requestStreamRawWithOptions(clientTasks, "rootsList", Object.fromEntries([[
        "kind",
        "client"
      ]]), options);
    let clientTask = await McpClientExperimentalTasks.getTask(clientTasks, "exp-task");
    let clientTaskWithOptions = await McpClientExperimentalTasks.getTaskWithOptions(clientTasks, "exp-task", options);
    let clientRaw = await McpClientExperimentalTasks.getTaskResultRaw(clientTasks, "exp-task");
    let clientRawWithOptions = await McpClientExperimentalTasks.getTaskResultRawWithOptions(clientTasks, "exp-task", options);
    await McpClientExperimentalTasks.listTasks(clientTasks);
    await McpClientExperimentalTasks.listTasksWithCursor(clientTasks, "cursor-client-1");
    await McpClientExperimentalTasks.listTasksWithOptions(clientTasks, options);
    await McpClientExperimentalTasks.listTasksWithCursorAndOptions(clientTasks, "cursor-client-2", options);
    let clientCancelled = await McpClientExperimentalTasks.cancelTask(clientTasks, "exp-cancelled");
    let clientCancelledWithOptions = await McpClientExperimentalTasks.cancelTaskWithOptions(clientTasks, "exp-cancelled", options);
    McpLowLevelServerExperimentalTasks.requestStreamRaw(serverTasks, "samplingCreateMessage", Object.fromEntries([[
        "kind",
        "server"
      ]]));
    McpLowLevelServerExperimentalTasks.requestStreamRawWithOptions(serverTasks, "tasksList", Object.fromEntries([[
        "kind",
        "server"
      ]]), options);
    McpLowLevelServerExperimentalTasks.createMessageStreamRaw(serverTasks, Object.fromEntries([[
        "kind",
        "create"
      ]]));
    McpLowLevelServerExperimentalTasks.createMessageStreamRawWithOptions(serverTasks, Object.fromEntries([[
        "kind",
        "create-with-options"
      ]]), options);
    McpLowLevelServerExperimentalTasks.elicitInputStreamRaw(serverTasks, Object.fromEntries([[
        "kind",
        "elicit"
      ]]));
    McpLowLevelServerExperimentalTasks.elicitInputStreamRawWithOptions(serverTasks, Object.fromEntries([[
        "kind",
        "elicit-with-options"
      ]]), options);
    let serverTask = await McpLowLevelServerExperimentalTasks.getTask(serverTasks, "exp-task");
    let serverTaskWithOptions = await McpLowLevelServerExperimentalTasks.getTaskWithOptions(serverTasks, "exp-task", options);
    let serverRaw = await McpLowLevelServerExperimentalTasks.getTaskResultRaw(serverTasks, "exp-task");
    let serverRawWithOptions = await McpLowLevelServerExperimentalTasks.getTaskResultRawWithOptions(serverTasks, "exp-task", options);
    await McpLowLevelServerExperimentalTasks.listTasks(serverTasks);
    await McpLowLevelServerExperimentalTasks.listTasksWithCursor(serverTasks, "cursor-server-1");
    await McpLowLevelServerExperimentalTasks.listTasksWithOptions(serverTasks, options);
    await McpLowLevelServerExperimentalTasks.listTasksWithCursorAndOptions(serverTasks, "cursor-server-2", options);
    let serverCancelled = await McpLowLevelServerExperimentalTasks.cancelTask(serverTasks, "exp-cancelled");
    let serverCancelledWithOptions = await McpLowLevelServerExperimentalTasks.cancelTaskWithOptions(serverTasks, "exp-cancelled", options);
    return t.expect([
      clientCallNames.contents,
      clientRequestMethods.contents,
      clientListCursors.contents,
      McpGetTaskResult.status(clientTask),
      McpGetTaskResult.status(clientTaskWithOptions),
      clientRaw,
      clientRawWithOptions,
      McpCancelTaskResult.status(clientCancelled),
      McpCancelTaskResult.status(clientCancelledWithOptions),
      serverRequestMethods.contents,
      serverCreateKinds.contents,
      serverElicitKinds.contents,
      serverListCursors.contents,
      McpGetTaskResult.status(serverTask),
      McpGetTaskResult.status(serverTaskWithOptions),
      serverRaw,
      serverRawWithOptions,
      McpCancelTaskResult.status(serverCancelled),
      McpCancelTaskResult.status(serverCancelledWithOptions)
    ]).toEqual([
      [
        "echo",
        "echo"
      ],
      [
        "roots/list",
        "tools/call"
      ],
      [
        "cursor-client-2",
        "<none>",
        "cursor-client-1",
        "<none>"
      ],
      "working",
      "working",
      "client-raw",
      "client-raw",
      "cancelled",
      "cancelled",
      [
        "tasks/list",
        "sampling/createMessage"
      ],
      [
        "create-with-options",
        "create"
      ],
      [
        "elicit-with-options",
        "elicit"
      ],
      [
        "cursor-server-2",
        "<none>",
        "cursor-server-1",
        "<none>"
      ],
      "working",
      "working",
      "server-raw",
      "server-raw",
      "cancelled",
      "cancelled"
    ]);
  });
});

let S;

let Json;

export {
  S,
  Json,
  typedOutputSchema,
  codeFormSchema,
  outputSchema,
  meta,
  encodeCursor,
  encodePresence,
  rawStructuredMessage,
  stringField,
  samplingContentKindString,
  samplingMessageKinds,
}
/* typedOutputSchema Not a pure module */
