// Generated by ReScript, PLEASE EDIT WITH CARE

import * as Vitest from "rescript-vitest/src/Vitest.mjs";
import * as Stdlib_Option from "@rescript/runtime/lib/es6/Stdlib_Option.js";
import * as S$RescriptSchema from "rescript-schema/src/S.mjs";
import * as McpStandardSchema from "../src/protocol/McpStandardSchema.mjs";

let profileSchema = S$RescriptSchema.schema(s => ({
  name: s.m(S$RescriptSchema.string),
  nickname: s.m(S$RescriptSchema.option(S$RescriptSchema.string)),
  rating: s.m(S$RescriptSchema.floatMax(S$RescriptSchema.floatMin(S$RescriptSchema.float, 1.0, undefined), 5.0, undefined))
}));

let wrappedSchema = S$RescriptSchema.schema(s => ({
  topic: s.m(S$RescriptSchema.string),
  count: s.m(S$RescriptSchema.port(S$RescriptSchema.int, undefined))
}));

function expectSchema(expect, schema, expectedText) {
  expect(McpStandardSchema.jsonSchemaOfRescriptSchema(schema)).toEqual(JSON.parse(expectedText));
}

Vitest.describe("standard schema bridge", undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, () => {
  Vitest.test("converts primitive and refined schemas into JSON Schema", undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, t => {
    let expect = value => t.expect(value);
    expectSchema(expect, S$RescriptSchema.unknown, "{}");
    expectSchema(expect, S$RescriptSchema.never, "{\"not\":{}}");
    expectSchema(expect, S$RescriptSchema.bool, "{\"type\":\"boolean\"}");
    expectSchema(expect, S$RescriptSchema.bigint, "{\"type\":\"integer\"}");
    expectSchema(expect, S$RescriptSchema.port(S$RescriptSchema.int, undefined), "{\"type\":\"integer\",\"minimum\":0,\"maximum\":65535}");
    expectSchema(expect, S$RescriptSchema.floatMax(S$RescriptSchema.floatMin(S$RescriptSchema.float, 1.5, undefined), 2.5, undefined), "{\"type\":\"number\",\"minimum\":1.5,\"maximum\":2.5}");
    expectSchema(expect, S$RescriptSchema.describe(S$RescriptSchema.stringMaxLength(S$RescriptSchema.stringMinLength(S$RescriptSchema.string, 2, undefined), 5, undefined), "display name"), "{\"type\":\"string\",\"minLength\":2,\"maxLength\":5,\"description\":\"display name\"}");
    expectSchema(expect, S$RescriptSchema.stringLength(S$RescriptSchema.string, 4, undefined), "{\"type\":\"string\",\"minLength\":4,\"maxLength\":4}");
    expectSchema(expect, S$RescriptSchema.email(S$RescriptSchema.string, undefined), "{\"type\":\"string\",\"format\":\"email\"}");
    expectSchema(expect, S$RescriptSchema.uuid(S$RescriptSchema.string, undefined), "{\"type\":\"string\",\"format\":\"uuid\"}");
    expectSchema(expect, S$RescriptSchema.cuid(S$RescriptSchema.string, undefined), "{\"type\":\"string\",\"pattern\":\"^c[a-z0-9]+$\"}");
    expectSchema(expect, S$RescriptSchema.url(S$RescriptSchema.string, undefined), "{\"type\":\"string\",\"format\":\"uri\"}");
    expectSchema(expect, S$RescriptSchema.datetime(S$RescriptSchema.string, undefined), "{\"type\":\"string\",\"format\":\"date-time\"}");
    expectSchema(expect, S$RescriptSchema.pattern(S$RescriptSchema.string, /^[a-z-]+$/, undefined), "{\"type\":\"string\",\"pattern\":\"^[a-z-]+$\"}");
    expectSchema(expect, S$RescriptSchema.arrayLength(S$RescriptSchema.array(S$RescriptSchema.string), 2, undefined), "{\"type\":\"array\",\"items\":{\"type\":\"string\"},\"minItems\":2,\"maxItems\":2}");
  });
  Vitest.test("converts object, tuple, union, dict, nullable, optional, and literal schemas", undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, t => {
    let expect = value => t.expect(value);
    let strictObjectSchema = S$RescriptSchema.strict(profileSchema);
    let tupleSchema = S$RescriptSchema.tuple(s => [
      s.item(0, S$RescriptSchema.string),
      s.item(1, S$RescriptSchema.int)
    ]);
    let unionSchema = S$RescriptSchema.union([
      S$RescriptSchema.string,
      S$RescriptSchema.email(S$RescriptSchema.string, undefined),
      S$RescriptSchema.url(S$RescriptSchema.string, undefined)
    ]);
    expectSchema(expect, profileSchema, "{\"type\":\"object\",\"properties\":{\"name\":{\"type\":\"string\"},\"nickname\":{\"type\":\"string\"},\"rating\":{\"type\":\"number\",\"minimum\":1,\"maximum\":5}},\"required\":[\"name\",\"rating\"]}");
    expectSchema(expect, strictObjectSchema, "{\"type\":\"object\",\"properties\":{\"name\":{\"type\":\"string\"},\"nickname\":{\"type\":\"string\"},\"rating\":{\"type\":\"number\",\"minimum\":1,\"maximum\":5}},\"required\":[\"name\",\"rating\"],\"additionalProperties\":false}");
    expectSchema(expect, tupleSchema, "{\"type\":\"array\",\"items\":[{\"type\":\"string\"},{\"type\":\"integer\"}],\"minItems\":2,\"maxItems\":2}");
    expectSchema(expect, unionSchema, "{\"anyOf\":[{\"type\":\"string\"},{\"type\":\"string\",\"format\":\"email\"},{\"type\":\"string\",\"format\":\"uri\"}]}");
    expectSchema(expect, S$RescriptSchema.dict(S$RescriptSchema.string), "{\"type\":\"object\",\"additionalProperties\":{\"type\":\"string\"}}");
    expectSchema(expect, S$RescriptSchema.option(S$RescriptSchema.string), "{\"type\":\"string\"}");
    expectSchema(expect, S$RescriptSchema.nullable(S$RescriptSchema.string), "{\"anyOf\":[{\"type\":\"string\"},{\"type\":\"null\"}]}");
    expectSchema(expect, S$RescriptSchema.literal("fixed"), "{\"type\":\"string\",\"const\":\"fixed\"}");
    expectSchema(expect, S$RescriptSchema.literal(3.5), "{\"type\":\"number\",\"const\":3.5}");
    expectSchema(expect, S$RescriptSchema.literal(true), "{\"type\":\"boolean\",\"const\":true}");
    expectSchema(expect, S$RescriptSchema.literal(null), "{\"type\":\"null\",\"const\":null}");
  });
  Vitest.test("adds JSON Schema converters onto the Standard Schema wrapper", undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, t => {
    let expectedText = Stdlib_Option.getOr(JSON.stringify(McpStandardSchema.jsonSchemaOfRescriptSchema(wrappedSchema)), "");
    let standard = McpStandardSchema.fromRescriptSchema(wrappedSchema);
    let props = standard["~standard"];
    t.expect([
      props.vendor,
      props.version,
      Stdlib_Option.getOr(JSON.stringify(props.jsonSchema.input()), ""),
      Stdlib_Option.getOr(JSON.stringify(props.jsonSchema.output()), "")
    ]).toEqual([
      "rescript-schema",
      1,
      expectedText,
      expectedText
    ]);
  });
});

let S;

export {
  S,
  profileSchema,
  wrappedSchema,
  expectSchema,
}
/* profileSchema Not a pure module */
