// Generated by ReScript, PLEASE EDIT WITH CARE

import * as Vitest from "rescript-vitest/src/Vitest.mjs";
import * as TestSupport from "./TestSupport.mjs";
import * as Stdlib_Option from "@rescript/runtime/lib/es6/Stdlib_Option.js";
import * as McpTestBindings from "./support/McpTestBindings.mjs";
import * as Primitive_option from "@rescript/runtime/lib/es6/Primitive_option.js";

Vitest.describe("stdio roundtrip", undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, () => Vitest.testAsync("initializes and pings through the bound stdio client transport", undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, async t => {
  let client = McpTestBindings.makeClientWithOptions("stdio-test-client", "1.0.0");
  let transport = McpTestBindings.makeStdioClientTransport(TestSupport.execPath, [TestSupport.fixturePath("StdioPingServer.mjs")], TestSupport.cwd);
  await McpTestBindings.connectClientWithTimeout(client, transport, 5000);
  t.expect([
    Stdlib_Option.isSome(McpTestBindings.stdioClientPid(transport)),
    McpTestBindings.clientServerVersion(client),
    McpTestBindings.clientInstructions(client),
    Stdlib_Option.isSome(McpTestBindings.clientServerCapabilities(client))
  ]).toEqual([
    true,
    Primitive_option.some(McpTestBindings.makeImplementation("stdio-test-server", "1.0.0")),
    "stdio test server",
    true
  ]);
  await McpTestBindings.pingClientWithTimeout(client, 5000);
  return await TestSupport.settle([
    TestSupport.closeIgnore(McpTestBindings.closeClient(client)),
    TestSupport.closeIgnore(McpTestBindings.transportClose(transport))
  ]);
}));

/*  Not a pure module */
