// Generated by ReScript, PLEASE EDIT WITH CARE

import * as Vitest from "rescript-vitest/src/Vitest.mjs";
import * as McpTask from "../src/shared/McpTask.mjs";
import * as McpTypes from "../src/core/McpTypes.mjs";
import * as Belt_Array from "@rescript/runtime/lib/es6/Belt_Array.js";
import * as McpTaskStore from "../src/shared/McpTaskStore.mjs";
import * as Stdlib_Option from "@rescript/runtime/lib/es6/Stdlib_Option.js";
import * as McpContentBlock from "../src/protocol/McpContentBlock.mjs";
import * as McpTestBindings from "./support/McpTestBindings.mjs";
import * as S$RescriptSchema from "rescript-schema/src/S.mjs";
import * as McpCallToolResult from "../src/protocol/McpCallToolResult.mjs";
import * as McpStandardSchema from "../src/protocol/McpStandardSchema.mjs";
import * as McpListTasksResult from "../src/protocol/McpListTasksResult.mjs";
import * as McpTaskMessageQueue from "../src/shared/McpTaskMessageQueue.mjs";
import * as McpCreateTaskOptions from "../src/shared/McpCreateTaskOptions.mjs";

let storedOutputSchema = S$RescriptSchema.schema(s => ({
  message: s.m(S$RescriptSchema.string)
}));

let storedOutputStandardSchema = McpStandardSchema.fromRescriptSchema(storedOutputSchema);

function queuedMessageKind(message) {
  return McpTestBindings.getSome(Stdlib_Option.map(message["type"], prim => prim));
}

function makeJsonRpcRequest(methodName) {
  return Object.fromEntries([
    [
      "jsonrpc",
      McpTypes.jsonRpcVersion
    ],
    [
      "id",
      17
    ],
    [
      "method",
      methodName
    ],
    [
      "params",
      Object.fromEntries([])
    ]
  ]);
}

function makeQueuedNotification(methodName) {
  return Object.fromEntries([
    [
      "type",
      "notification"
    ],
    [
      "message",
      Object.fromEntries([
        [
          "jsonrpc",
          McpTypes.jsonRpcVersion
        ],
        [
          "method",
          methodName
        ],
        [
          "params",
          Object.fromEntries([])
        ]
      ])
    ]
  ]);
}

Vitest.describe("task storage surface", undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, () => Vitest.testAsync("custom task stores and task message queues dispatch through the bound runtime methods", undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, async t => {
  let baseStore = McpTaskStore.makeInMemory();
  let createCalls = {
    contents: 0
  };
  let getCalls = {
    contents: 0
  };
  let storeResultCalls = {
    contents: 0
  };
  let getResultCalls = {
    contents: 0
  };
  let updateCalls = {
    contents: 0
  };
  let listCalls = {
    contents: 0
  };
  let customStore = McpTaskStore.make((taskParams, requestId, request, sessionId) => {
    createCalls.contents = createCalls.contents + 1 | 0;
    if (sessionId !== undefined) {
      return McpTaskStore.createTaskWithSessionId(baseStore, taskParams, requestId, request, sessionId);
    } else {
      return McpTaskStore.createTask(baseStore, taskParams, requestId, request);
    }
  }, (taskId, sessionId) => {
    getCalls.contents = getCalls.contents + 1 | 0;
    if (sessionId !== undefined) {
      return McpTaskStore.getTaskWithSessionId(baseStore, taskId, sessionId);
    } else {
      return McpTaskStore.getTask(baseStore, taskId);
    }
  }, (taskId, status, result, sessionId) => {
    storeResultCalls.contents = storeResultCalls.contents + 1 | 0;
    if (sessionId !== undefined) {
      return McpTaskStore.storeTaskResultRawWithSessionId(baseStore, taskId, status, result, sessionId);
    } else {
      return McpTaskStore.storeTaskResultRaw(baseStore, taskId, status, result);
    }
  }, (taskId, sessionId) => {
    getResultCalls.contents = getResultCalls.contents + 1 | 0;
    if (sessionId !== undefined) {
      return McpTaskStore.getTaskResultRawWithSessionId(baseStore, taskId, sessionId);
    } else {
      return McpTaskStore.getTaskResultRaw(baseStore, taskId);
    }
  }, (taskId, status, statusMessage, sessionId) => {
    updateCalls.contents = updateCalls.contents + 1 | 0;
    if (sessionId !== undefined) {
      return McpTaskStore.updateTaskStatusWithSessionId(baseStore, taskId, status, statusMessage, sessionId);
    } else {
      return McpTaskStore.updateTaskStatus(baseStore, taskId, status, statusMessage, undefined);
    }
  }, (cursor, sessionId) => {
    listCalls.contents = listCalls.contents + 1 | 0;
    if (cursor !== undefined) {
      if (sessionId !== undefined) {
        return McpTaskStore.listTasksWithCursorAndSessionId(baseStore, cursor, sessionId);
      } else {
        return McpTaskStore.listTasksWithCursor(baseStore, cursor);
      }
    } else if (sessionId !== undefined) {
      return McpTaskStore.listTasksWithSessionId(baseStore, sessionId);
    } else {
      return McpTaskStore.listTasks(baseStore);
    }
  }, undefined);
  let createdTask = await McpTaskStore.createTask(customStore, McpCreateTaskOptions.make(5000, 50, undefined, undefined), 1, makeJsonRpcRequest("tools/call"));
  let missingTask = await McpTaskStore.getTask(customStore, "missing-task");
  let sessionTask = await McpTaskStore.createTaskWithSessionId(customStore, McpCreateTaskOptions.make(5000, 25, undefined, undefined), 2, makeJsonRpcRequest("sampling/createMessage"), "session-a");
  await McpTaskStore.updateTaskStatus(customStore, McpTask.taskId(createdTask), "working", "running", undefined);
  await McpTaskStore.storeTaskResult(customStore, McpTask.taskId(createdTask), "completed", McpCallToolResult.make([McpContentBlock.text("stored result")], {
    message: "stored result"
  }, undefined, undefined), storedOutputStandardSchema);
  await McpTaskStore.updateTaskStatusWithSessionId(customStore, McpTask.taskId(sessionTask), "working", "session-running", "session-a");
  await McpTaskStore.storeTaskResultRawWithSessionId(customStore, McpTask.taskId(sessionTask), "failed", Object.fromEntries([[
      "error",
      "session-failed"
    ]]), "session-a");
  let fetchedTask = await McpTaskStore.getTask(customStore, McpTask.taskId(createdTask));
  let fetchedTaskResult = await McpTaskStore.getTaskResult(customStore, McpTask.taskId(createdTask), storedOutputStandardSchema);
  let sameSessionTask = await McpTaskStore.getTaskWithSessionId(customStore, McpTask.taskId(sessionTask), "session-a");
  let wrongSessionTask = await McpTaskStore.getTaskWithSessionId(customStore, McpTask.taskId(sessionTask), "session-b");
  let sessionResult = await McpTaskStore.getTaskResultRawWithSessionId(customStore, McpTask.taskId(sessionTask), "session-a");
  let listedTasks = await McpTaskStore.listTasks(customStore);
  let baseQueue = McpTaskMessageQueue.makeInMemory();
  let enqueueCalls = {
    contents: 0
  };
  let dequeueCalls = {
    contents: 0
  };
  let dequeueAllCalls = {
    contents: 0
  };
  let customQueue = McpTaskMessageQueue.make((taskId, message, sessionId, maxSize) => {
    enqueueCalls.contents = enqueueCalls.contents + 1 | 0;
    return McpTaskMessageQueue.enqueue(baseQueue, taskId, message, sessionId, maxSize, undefined);
  }, (taskId, sessionId) => {
    dequeueCalls.contents = dequeueCalls.contents + 1 | 0;
    return McpTaskMessageQueue.dequeue(baseQueue, taskId, sessionId, undefined);
  }, (taskId, sessionId) => {
    dequeueAllCalls.contents = dequeueAllCalls.contents + 1 | 0;
    return McpTaskMessageQueue.dequeueAll(baseQueue, taskId, sessionId, undefined);
  }, undefined);
  await McpTaskMessageQueue.enqueue(customQueue, McpTask.taskId(createdTask), makeQueuedNotification("notifications/message"), undefined, undefined, undefined);
  await McpTaskMessageQueue.enqueue(customQueue, McpTask.taskId(createdTask), makeQueuedNotification("notifications/progress"), "session-a", 2, undefined);
  let firstQueuedMessage = await McpTaskMessageQueue.dequeue(customQueue, McpTask.taskId(createdTask), undefined, undefined);
  let remainingQueuedMessages = await McpTaskMessageQueue.dequeueAll(customQueue, McpTask.taskId(createdTask), "session-a", undefined);
  return t.expect([
    missingTask === undefined,
    McpTask.status(McpTestBindings.getSome(fetchedTask)),
    McpTestBindings.toolResultTexts(fetchedTaskResult),
    Stdlib_Option.map(McpCallToolResult.structuredContent(fetchedTaskResult), output => output.message),
    Stdlib_Option.map(sameSessionTask, McpTask.status),
    wrongSessionTask === undefined,
    Stdlib_Option.map(sessionResult["error"], prim => prim),
    Belt_Array.some(McpListTasksResult.tasks(listedTasks).map(McpTask.taskId), taskId => taskId === McpTask.taskId(createdTask)),
    createCalls.contents,
    getCalls.contents,
    storeResultCalls.contents,
    getResultCalls.contents,
    updateCalls.contents,
    listCalls.contents,
    Stdlib_Option.map(firstQueuedMessage, queuedMessageKind),
    Stdlib_Option.map(firstQueuedMessage, message => message.message.method),
    remainingQueuedMessages.map(queuedMessageKind),
    remainingQueuedMessages.map(message => message.message.method),
    enqueueCalls.contents,
    dequeueCalls.contents,
    dequeueAllCalls.contents
  ]).toEqual([
    true,
    "completed",
    ["stored result"],
    "stored result",
    "failed",
    true,
    "session-failed",
    true,
    2,
    4,
    2,
    2,
    2,
    1,
    "notification",
    "notifications/message",
    ["notification"],
    ["notifications/progress"],
    2,
    1,
    1
  ]);
}));

let S;

export {
  S,
  storedOutputSchema,
  storedOutputStandardSchema,
  queuedMessageKind,
  makeJsonRpcRequest,
  makeQueuedNotification,
}
/* storedOutputSchema Not a pure module */
