// Generated by ReScript, PLEASE EDIT WITH CARE

import * as Process from "process";
import * as Nodepath from "node:path";
import * as Stdlib_Option from "@rescript/runtime/lib/es6/Stdlib_Option.js";
import * as Stdlib_Promise from "@rescript/runtime/lib/es6/Stdlib_Promise.js";
import * as Nodechild_process from "node:child_process";

let process = Process;

let cwd = process.cwd();

let execPath = process.execPath;

function fixturePath(name) {
  return Nodepath.join(cwd, "tests", "fixtures", name);
}

function importWithNode(path) {
  let quotedPath = Stdlib_Option.getOr(JSON.stringify(path), "\"\"");
  Nodechild_process.execFileSync(execPath, [
    "--input-type=module",
    "-e",
    `await import(` + quotedPath + `);`
  ]);
}

function listenHttpServer(server) {
  return new Promise((resolve, _reject) => {
    server.listen(0, "127.0.0.1", () => resolve(server.address()));
  });
}

function closeHttpServer(server) {
  return new Promise((resolve, reject) => {
    server.close(error => {
      if (error == null) {
        return resolve();
      } else {
        return reject({
          RE_EXN_ID: "Failure",
          _1: "server close error"
        });
      }
    });
  });
}

function closeIgnore(promise) {
  return Stdlib_Promise.$$catch(promise.then(param => Promise.resolve()), param => Promise.resolve());
}

function settle(promises) {
  return Promise.allSettled(promises).then(param => Promise.resolve());
}

export {
  process,
  cwd,
  execPath,
  fixturePath,
  importWithNode,
  listenHttpServer,
  closeHttpServer,
  closeIgnore,
  settle,
}
/* process Not a pure module */
