// Generated by ReScript, PLEASE EDIT WITH CARE

import * as Vitest from "rescript-vitest/src/Vitest.mjs";
import * as McpTypes from "../src/core/McpTypes.mjs";
import * as TestSupport from "./TestSupport.mjs";
import * as Stdlib_Option from "@rescript/runtime/lib/es6/Stdlib_Option.js";
import * as Webapi__Fetch from "rescript-webapi/src/Webapi/Webapi__Fetch.mjs";
import * as McpTestBindings from "./support/McpTestBindings.mjs";
import * as Primitive_option from "@rescript/runtime/lib/es6/Primitive_option.js";
import * as McpProtocolVersion from "../src/core/McpProtocolVersion.mjs";

function makeJsonRequest(protocolVersion, sessionId, body) {
  let protocolVersion$1 = McpProtocolVersion.toString(protocolVersion);
  let headers = Object.fromEntries([
    [
      "accept",
      "application/json, text/event-stream"
    ],
    [
      "content-type",
      "application/json"
    ],
    [
      "mcp-protocol-version",
      protocolVersion$1
    ]
  ]);
  if (sessionId !== undefined) {
    headers["mcp-session-id"] = sessionId;
  }
  return new Request("http://example.test/mcp", Webapi__Fetch.RequestInit.make("Post", Primitive_option.some(headers), Primitive_option.some(body), undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined));
}

Vitest.describe("web-standard streamable http transport", undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, () => Vitest.testAsync("handles initialize and ping over Request and Response objects", undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, async t => {
  let server = McpTestBindings.makeLowLevelServerWithInstructions("web-test-server", "1.0.0", "web test server");
  let transport = McpTestBindings.makeWebStandardStatefulJsonTransport("web-test-session");
  let authInfo = McpTestBindings.makeAuthInfo("test-token", "test-client", ["read"]);
  await McpTestBindings.connectLowLevelServer(server, transport);
  let initializeResponse = await McpTestBindings.webHandleRequestWithAuthInfo(transport, makeJsonRequest(McpTypes.latestProtocolVersion, undefined, "{\"jsonrpc\":\"2.0\",\"id\":1,\"method\":\"initialize\",\"params\":{\"protocolVersion\":\"" + McpProtocolVersion.toString(McpTypes.latestProtocolVersion) + "\",\"capabilities\":{},\"clientInfo\":{\"name\":\"web-test-client\",\"version\":\"1.0.0\"}}}"), authInfo);
  let initializeBody = await initializeResponse.json();
  let initializeResult = initializeBody.result;
  let negotiatedProtocolVersion = Stdlib_Option.getOr(Stdlib_Option.map(Primitive_option.fromNull(initializeResponse.headers.get("mcp-protocol-version")), McpProtocolVersion.fromString), McpTypes.latestProtocolVersion);
  let sessionId = Stdlib_Option.getOr(Primitive_option.fromNull(initializeResponse.headers.get("mcp-session-id")), "");
  let pingResponse = await McpTestBindings.webHandleRequest(transport, makeJsonRequest(negotiatedProtocolVersion, sessionId, "{\"jsonrpc\":\"2.0\",\"id\":2,\"method\":\"ping\",\"params\":{}}"));
  let pingBody = await pingResponse.json();
  t.expect([
    initializeResponse.status,
    Stdlib_Option.getOr(Primitive_option.fromNull(initializeResponse.headers.get("content-type")), "").includes("application/json"),
    initializeResult.serverInfo,
    sessionId,
    pingResponse.status,
    pingBody.jsonrpc,
    pingBody.id
  ]).toEqual([
    200,
    true,
    McpTestBindings.makeImplementation("web-test-server", "1.0.0"),
    "web-test-session",
    200,
    "2.0",
    2
  ]);
  return await TestSupport.settle([
    TestSupport.closeIgnore(McpTestBindings.closeLowLevelServer(server)),
    TestSupport.closeIgnore(McpTestBindings.transportClose(transport))
  ]);
}));

export {
  makeJsonRequest,
}
/*  Not a pure module */
