// Generated by ReScript, PLEASE EDIT WITH CARE

import * as Primitive_option from "@rescript/runtime/lib/es6/Primitive_option.js";

function make(prim0, prim1, prim2, prim3) {
  let tmp = {};
  if (prim0 !== undefined) {
    tmp.ttl = prim0;
  }
  if (prim1 !== undefined) {
    tmp.pollInterval = prim1;
  }
  if (prim2 !== undefined) {
    tmp.context = Primitive_option.valFromOption(prim2);
  }
  return tmp;
}

export {
  make,
}
/* No side effect */
