// Generated by ReScript, PLEASE EDIT WITH CARE

import * as Primitive_option from "@rescript/runtime/lib/es6/Primitive_option.js";

function make(prim0, prim1, prim2, prim3, prim4, prim5, prim6) {
  let tmp = {};
  if (prim0 !== undefined) {
    tmp.enforceStrictCapabilities = prim0;
  }
  if (prim1 !== undefined) {
    tmp.debouncedNotificationMethods = Primitive_option.valFromOption(prim1);
  }
  if (prim2 !== undefined) {
    tmp.taskStore = Primitive_option.valFromOption(prim2);
  }
  if (prim3 !== undefined) {
    tmp.taskMessageQueue = Primitive_option.valFromOption(prim3);
  }
  if (prim4 !== undefined) {
    tmp.defaultTaskPollInterval = prim4;
  }
  if (prim5 !== undefined) {
    tmp.maxTaskQueueSize = prim5;
  }
  return tmp;
}

export {
  make,
}
/* No side effect */
