// Generated by ReScript, PLEASE EDIT WITH CARE


function make(prim0, prim1) {
  return {
    taskId: prim0
  };
}

function taskId(prim) {
  return prim.taskId;
}

export {
  make,
  taskId,
}
/* No side effect */
