// Generated by ReScript, PLEASE EDIT WITH CARE

import * as Primitive_option from "@rescript/runtime/lib/es6/Primitive_option.js";

function make(prim0, prim1, prim2, prim3, prim4, prim5, prim6, prim7, prim8, prim9, prim10) {
  let tmp = {};
  if (prim0 !== undefined) {
    tmp.onprogress = Primitive_option.valFromOption(prim0);
  }
  if (prim1 !== undefined) {
    tmp.signal = Primitive_option.valFromOption(prim1);
  }
  if (prim2 !== undefined) {
    tmp.timeout = prim2;
  }
  if (prim3 !== undefined) {
    tmp.resetTimeoutOnProgress = prim3;
  }
  if (prim4 !== undefined) {
    tmp.maxTotalTimeout = prim4;
  }
  if (prim5 !== undefined) {
    tmp.task = Primitive_option.valFromOption(prim5);
  }
  if (prim6 !== undefined) {
    tmp.relatedTask = Primitive_option.valFromOption(prim6);
  }
  if (prim7 !== undefined) {
    tmp.relatedRequestId = Primitive_option.valFromOption(prim7);
  }
  if (prim8 !== undefined) {
    tmp.resumptionToken = prim8;
  }
  if (prim9 !== undefined) {
    tmp.onresumptiontoken = Primitive_option.valFromOption(prim9);
  }
  return tmp;
}

export {
  make,
}
/* No side effect */
