// Generated by ReScript, PLEASE EDIT WITH CARE

import * as Stdlib_JsError from "@rescript/runtime/lib/es6/Stdlib_JsError.js";
import * as Primitive_option from "@rescript/runtime/lib/es6/Primitive_option.js";
import * as Server from "@modelcontextprotocol/server";

function kind(message) {
  let other = message.type;
  switch (other) {
    case "error" :
      return "error";
    case "result" :
      return "result";
    case "taskCreated" :
      return "taskCreated";
    case "taskStatus" :
      return "taskStatus";
    default:
      return Stdlib_JsError.throwWithMessage("Unsupported MCP response stream message type: " + other);
  }
}

function toArray(prim) {
  return Server.toArrayAsync(prim);
}

function takeResult(prim) {
  return Server.takeResult(prim);
}

function task(prim) {
  return Primitive_option.fromNullable(prim.task);
}

function result(prim) {
  return Primitive_option.fromNullable(prim.result);
}

function error(prim) {
  return Primitive_option.fromNullable(prim.error);
}

export {
  toArray,
  takeResult,
  kind,
  task,
  result,
  error,
}
/* @modelcontextprotocol/server Not a pure module */
