// Generated by ReScript, PLEASE EDIT WITH CARE

import * as McpTaskStatus from "./McpTaskStatus.mjs";
import * as McpTaskResultStatus from "./McpTaskResultStatus.mjs";
import * as McpCallToolResultInternal from "../protocol/McpCallToolResultInternal.mjs";

function storeTaskResult(store, taskId, status, result, outputSchema) {
  return store.storeTaskResult(taskId, McpTaskResultStatus.toString(status), McpCallToolResultInternal.toRaw(result, outputSchema));
}

function storeTaskResultRaw(store, taskId, status, result) {
  return store.storeTaskResult(taskId, McpTaskResultStatus.toString(status), result);
}

function getTaskResult(store, taskId, outputSchema) {
  return store.getTaskResult(taskId).then(result => Promise.resolve(McpCallToolResultInternal.fromRaw(result, outputSchema)));
}

function updateTaskStatus(store, taskId, status, statusMessage) {
  if (statusMessage !== undefined) {
    return store.updateTaskStatus(taskId, McpTaskStatus.toString(status), statusMessage);
  } else {
    return store.updateTaskStatus(taskId, McpTaskStatus.toString(status));
  }
}

function createTask(prim0, prim1) {
  return prim0.createTask(prim1);
}

function getTask(prim0, prim1) {
  return prim0.getTask(prim1);
}

function getTaskResultRaw(prim0, prim1) {
  return prim0.getTaskResult(prim1);
}

function listTasks(prim) {
  return prim.listTasks();
}

function listTasksWithCursor(prim0, prim1) {
  return prim0.listTasks(prim1);
}

export {
  createTask,
  getTask,
  storeTaskResult,
  storeTaskResultRaw,
  getTaskResult,
  getTaskResultRaw,
  updateTaskStatus,
  listTasks,
  listTasksWithCursor,
}
/* McpTaskStatus Not a pure module */
