// Generated by ReScript, PLEASE EDIT WITH CARE

import * as McpTaskStatus from "./McpTaskStatus.mjs";
import * as McpTaskResultStatus from "./McpTaskResultStatus.mjs";
import * as McpTaskStoreSupportMjs from "./McpTaskStoreSupport.mjs";
import * as McpCallToolResultInternal from "../protocol/McpCallToolResultInternal.mjs";
import * as Server from "@modelcontextprotocol/server";

function make(createTask, getTask, storeTaskResult, getTaskResult, updateTaskStatus, listTasks, param) {
  let prim2 = (taskId, status, result, sessionId) => storeTaskResult(taskId, McpTaskResultStatus.fromString(status), result, sessionId);
  let prim4 = (taskId, status, statusMessage, sessionId) => updateTaskStatus(taskId, McpTaskStatus.fromString(status), statusMessage, sessionId);
  return McpTaskStoreSupportMjs.makeTaskStore(createTask, getTask, prim2, getTaskResult, prim4, listTasks);
}

function createTask(store, taskParams, requestId, request) {
  return store.createTask(taskParams, requestId, request, undefined);
}

function createTaskWithSessionId(store, taskParams, requestId, request, sessionId) {
  return store.createTask(taskParams, requestId, request, sessionId);
}

function getTask(prim0, prim1) {
  return McpTaskStoreSupportMjs.getTask(prim0, prim1);
}

function getTaskWithSessionId(prim0, prim1, prim2) {
  return McpTaskStoreSupportMjs.getTaskWithSessionId(prim0, prim1, prim2);
}

function storeTaskResult(store, taskId, status, result, outputSchema) {
  return store.storeTaskResult(taskId, McpTaskResultStatus.toString(status), McpCallToolResultInternal.toRaw(result, outputSchema), undefined);
}

function storeTaskResultWithSessionId(store, taskId, status, result, outputSchema, sessionId) {
  return store.storeTaskResult(taskId, McpTaskResultStatus.toString(status), McpCallToolResultInternal.toRaw(result, outputSchema), sessionId);
}

function storeTaskResultRaw(store, taskId, status, result) {
  return store.storeTaskResult(taskId, McpTaskResultStatus.toString(status), result, undefined);
}

function storeTaskResultRawWithSessionId(store, taskId, status, result, sessionId) {
  return store.storeTaskResult(taskId, McpTaskResultStatus.toString(status), result, sessionId);
}

function getTaskResult(store, taskId, outputSchema) {
  return store.getTaskResult(taskId).then(result => Promise.resolve(McpCallToolResultInternal.fromRaw(result, outputSchema)));
}

function getTaskResultWithSessionId(store, taskId, outputSchema, sessionId) {
  return store.getTaskResult(taskId, sessionId).then(result => Promise.resolve(McpCallToolResultInternal.fromRaw(result, outputSchema)));
}

function updateTaskStatus(store, taskId, status, statusMessage, param) {
  return store.updateTaskStatus(taskId, McpTaskStatus.toString(status), statusMessage, undefined);
}

function updateTaskStatusWithSessionId(store, taskId, status, statusMessage, sessionId) {
  return store.updateTaskStatus(taskId, McpTaskStatus.toString(status), statusMessage, sessionId);
}

function listTasks(store) {
  return store.listTasks(undefined, undefined);
}

function listTasksWithCursor(store, cursor) {
  return store.listTasks(cursor, undefined);
}

function listTasksWithSessionId(store, sessionId) {
  return store.listTasks(undefined, sessionId);
}

function listTasksWithCursorAndSessionId(store, cursor, sessionId) {
  return store.listTasks(cursor, sessionId);
}

function makeInMemory(prim) {
  return new Server.InMemoryTaskStore();
}

function getTaskResultRaw(prim0, prim1) {
  return prim0.getTaskResult(prim1);
}

function getTaskResultRawWithSessionId(prim0, prim1, prim2) {
  return prim0.getTaskResult(prim1, prim2);
}

export {
  make,
  makeInMemory,
  createTask,
  createTaskWithSessionId,
  getTask,
  getTaskWithSessionId,
  storeTaskResult,
  storeTaskResultWithSessionId,
  storeTaskResultRaw,
  storeTaskResultRawWithSessionId,
  getTaskResult,
  getTaskResultWithSessionId,
  getTaskResultRaw,
  getTaskResultRawWithSessionId,
  updateTaskStatus,
  updateTaskStatusWithSessionId,
  listTasks,
  listTasksWithCursor,
  listTasksWithSessionId,
  listTasksWithCursorAndSessionId,
}
/* McpTaskStatus Not a pure module */
