// Generated by ReScript, PLEASE EDIT WITH CARE


function make(prim0, prim1, prim2) {
  let tmp = {};
  if (prim0 !== undefined) {
    tmp.ttl = prim0;
  }
  if (prim1 !== undefined) {
    tmp.pollInterval = prim1;
  }
  return tmp;
}

export {
  make,
}
/* No side effect */
