// Generated by ReScript, PLEASE EDIT WITH CARE

import * as Stdlib_JsError from "@rescript/runtime/lib/es6/Stdlib_JsError.js";
import * as Server from "@modelcontextprotocol/server";

function toString(status) {
  if (status === "completed") {
    return "completed";
  } else if (status === "failed") {
    return "failed";
  } else if (status === "working") {
    return "working";
  } else if (status === "cancelled") {
    return "cancelled";
  } else {
    return "input_required";
  }
}

function fromString(value) {
  switch (value) {
    case "cancelled" :
      return "cancelled";
    case "completed" :
      return "completed";
    case "failed" :
      return "failed";
    case "input_required" :
      return "inputRequired";
    case "working" :
      return "working";
    default:
      return Stdlib_JsError.throwWithMessage("Unsupported MCP task status: " + value);
  }
}

function isTerminal(status) {
  return Server.isTerminal(toString(status));
}

export {
  toString,
  fromString,
  isTerminal,
}
/* @modelcontextprotocol/server Not a pure module */
