// Generated by ReScript, PLEASE EDIT WITH CARE

import * as Primitive_option from "@rescript/runtime/lib/es6/Primitive_option.js";

function start(prim) {
  return prim.start();
}

function close(prim) {
  return prim.close();
}

function send(prim0, prim1) {
  return prim0.send(prim1);
}

function sendWithOptions(prim0, prim1, prim2) {
  return prim0.send(prim1, prim2);
}

function sessionId(prim) {
  return Primitive_option.fromNullable(prim.sessionId);
}

export {
  start,
  close,
  send,
  sendWithOptions,
  sessionId,
}
/* No side effect */
