// Generated by ReScript, PLEASE EDIT WITH CARE

import * as McpTaskStatus from "./McpTaskStatus.mjs";
import * as Primitive_option from "@rescript/runtime/lib/es6/Primitive_option.js";

function status(task) {
  return McpTaskStatus.fromString(task.status);
}

function taskId(prim) {
  return prim.taskId;
}

function ttl(prim) {
  return Primitive_option.fromNullable(prim.ttl);
}

function createdAt(prim) {
  return prim.createdAt;
}

function lastUpdatedAt(prim) {
  return prim.lastUpdatedAt;
}

function pollInterval(prim) {
  return Primitive_option.fromNullable(prim.pollInterval);
}

function statusMessage(prim) {
  return Primitive_option.fromNullable(prim.statusMessage);
}

export {
  taskId,
  status,
  ttl,
  createdAt,
  lastUpdatedAt,
  pollInterval,
  statusMessage,
}
/* McpTaskStatus Not a pure module */
