// Generated by ReScript, PLEASE EDIT WITH CARE

import * as Server from "@modelcontextprotocol/server";
import * as McpTaskMessageQueueSupportMjs from "./McpTaskMessageQueueSupport.mjs";

function make(prim0, prim1, prim2, prim3) {
  return McpTaskMessageQueueSupportMjs.makeTaskMessageQueue(prim0, prim1, prim2);
}

function enqueue(queue, taskId, message, sessionId, maxSize, param) {
  return queue.enqueue(taskId, message, sessionId, maxSize);
}

function dequeue(queue, taskId, sessionId, param) {
  return queue.dequeue(taskId, sessionId);
}

function dequeueAll(queue, taskId, sessionId, param) {
  return queue.dequeueAll(taskId, sessionId);
}

function makeInMemory(prim) {
  return new Server.InMemoryTaskMessageQueue();
}

export {
  make,
  makeInMemory,
  enqueue,
  dequeue,
  dequeueAll,
}
/* @modelcontextprotocol/server Not a pure module */
