// Generated by ReScript, PLEASE EDIT WITH CARE

import * as Primitive_option from "@rescript/runtime/lib/es6/Primitive_option.js";

function make(prim0, prim1, prim2, prim3, prim4) {
  let tmp = {};
  if (prim0 !== undefined) {
    tmp.taskStore = Primitive_option.valFromOption(prim0);
  }
  if (prim1 !== undefined) {
    tmp.taskMessageQueue = Primitive_option.valFromOption(prim1);
  }
  if (prim2 !== undefined) {
    tmp.defaultTaskPollInterval = prim2;
  }
  if (prim3 !== undefined) {
    tmp.maxTaskQueueSize = prim3;
  }
  return tmp;
}

export {
  make,
}
/* No side effect */
