// Generated by ReScript, PLEASE EDIT WITH CARE

import * as Primitive_option from "@rescript/runtime/lib/es6/Primitive_option.js";

function id(prim) {
  return Primitive_option.fromNullable(prim.id);
}

function store(prim) {
  return prim.store;
}

function requestedTtl(prim) {
  return Primitive_option.fromNullable(prim.requestedTtl);
}

export {
  id,
  store,
  requestedTtl,
}
/* No side effect */
