// Generated by ReScript, PLEASE EDIT WITH CARE

import * as Stdlib_JsError from "@rescript/runtime/lib/es6/Stdlib_JsError.js";

function toString(status) {
  if (status === "failed") {
    return "failed";
  } else {
    return "completed";
  }
}

function fromString(value) {
  switch (value) {
    case "completed" :
      return "completed";
    case "failed" :
      return "failed";
    default:
      return Stdlib_JsError.throwWithMessage("Unsupported MCP task result status: " + value);
  }
}

export {
  toString,
  fromString,
}
/* No side effect */
