// Generated by ReScript, PLEASE EDIT WITH CARE

import * as Primitive_option from "@rescript/runtime/lib/es6/Primitive_option.js";
import * as Server from "@modelcontextprotocol/server";

function matchRaw(prim0, prim1) {
  return Primitive_option.fromNullable(prim0.match(prim1));
}

function isTemplate(prim) {
  return Server["UriTemplate.isTemplate"](prim);
}

function make(prim) {
  return new Server.UriTemplate(prim);
}

function variableNames(prim) {
  return prim.variableNames;
}

function toString(prim) {
  return prim.toString();
}

function expand(prim0, prim1) {
  return prim0.expand(prim1);
}

function match(prim0, prim1) {
  return Primitive_option.fromNullable(prim0.match(prim1));
}

export {
  isTemplate,
  make,
  variableNames,
  toString,
  expand,
  match,
  matchRaw,
}
/* @modelcontextprotocol/server Not a pure module */
