// Generated by ReScript, PLEASE EDIT WITH CARE

import * as McpClient from "../../src/client/McpClient.mjs";
import * as McpServer from "../../src/server/McpServer.mjs";
import * as Belt_Array from "@rescript/runtime/lib/es6/Belt_Array.js";
import * as McpAuthInfo from "../../src/core/McpAuthInfo.mjs";
import * as McpTransport from "../../src/shared/McpTransport.mjs";
import * as Stdlib_Option from "@rescript/runtime/lib/es6/Stdlib_Option.js";
import * as Stdlib_JsError from "@rescript/runtime/lib/es6/Stdlib_JsError.js";
import * as McpContentBlock from "../../src/protocol/McpContentBlock.mjs";
import * as McpClientOptions from "../../src/client/McpClientOptions.mjs";
import * as McpPromptMessage from "../../src/protocol/McpPromptMessage.mjs";
import * as McpServerOptions from "../../src/server/McpServerOptions.mjs";
import * as Primitive_option from "@rescript/runtime/lib/es6/Primitive_option.js";
import * as McpCallToolResult from "../../src/protocol/McpCallToolResult.mjs";
import * as McpImplementation from "../../src/core/McpImplementation.mjs";
import * as McpLowLevelServer from "../../src/server/McpLowLevelServer.mjs";
import * as McpRequestOptions from "../../src/shared/McpRequestOptions.mjs";
import * as McpGetPromptResult from "../../src/protocol/McpGetPromptResult.mjs";
import * as McpListToolsResult from "../../src/protocol/McpListToolsResult.mjs";
import * as McpResourceContents from "../../src/protocol/McpResourceContents.mjs";
import * as McpListPromptsResult from "../../src/protocol/McpListPromptsResult.mjs";
import * as McpReadResourceResult from "../../src/protocol/McpReadResourceResult.mjs";
import * as McpSSEClientTransport from "../../src/transports/McpSSEClientTransport.mjs";
import * as McpListResourcesResult from "../../src/protocol/McpListResourcesResult.mjs";
import * as LoopbackTransportMjs from "./LoopbackTransport.mjs";
import * as McpStdioClientTransport from "../../src/transports/McpStdioClientTransport.mjs";
import * as McpStdioServerTransport from "../../src/transports/McpStdioServerTransport.mjs";
import * as McpStdioServerParameters from "../../src/transports/McpStdioServerParameters.mjs";
import * as McpListResourceTemplatesResult from "../../src/protocol/McpListResourceTemplatesResult.mjs";
import * as McpStreamableHttpClientTransport from "../../src/transports/McpStreamableHttpClientTransport.mjs";
import * as McpNodeStreamableHttpServerTransport from "../../src/transports/McpNodeStreamableHttpServerTransport.mjs";
import * as McpStreamableHttpClientTransportOptions from "../../src/transports/McpStreamableHttpClientTransportOptions.mjs";
import * as McpNodeStreamableHttpServerTransportOptions from "../../src/transports/McpNodeStreamableHttpServerTransportOptions.mjs";
import * as McpWebStandardStreamableHttpServerTransport from "../../src/transports/McpWebStandardStreamableHttpServerTransport.mjs";
import * as McpWebStandardStreamableHttpHandleRequestOptions from "../../src/transports/McpWebStandardStreamableHttpHandleRequestOptions.mjs";
import * as McpWebStandardStreamableHttpServerTransportOptions from "../../src/transports/McpWebStandardStreamableHttpServerTransportOptions.mjs";

function makeLoopbackTransportPair(prim) {
  return LoopbackTransportMjs.makeLoopbackTransportPair(prim);
}

let makeImplementation = McpImplementation.make;

function makeLowLevelServer(name, version) {
  return McpLowLevelServer.make(McpImplementation.make(name, version));
}

function makeLowLevelServerWithInstructions(name, version, instructions) {
  return McpLowLevelServer.makeWithOptions(McpImplementation.make(name, version), McpServerOptions.make(undefined, instructions, undefined, undefined, undefined, undefined, undefined, undefined));
}

function makeMcpServer(name, version) {
  return McpServer.make(McpImplementation.make(name, version));
}

function makeMcpServerWithInstructions(name, version, instructions) {
  return McpServer.makeWithOptions(McpImplementation.make(name, version), McpServerOptions.make(undefined, instructions, undefined, undefined, undefined, undefined, undefined, undefined));
}

function makeClient(name, version) {
  return McpClient.make(McpImplementation.make(name, version));
}

function makeClientWithOptions(name, version) {
  return McpClient.makeWithOptions(McpImplementation.make(name, version), McpClientOptions.make(undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined));
}

let registerClientCapabilities = McpClient.registerCapabilities;

let setClientRequestHandlerRaw = McpClient.setRequestHandlerRaw;

function makeRequestOptionsWithTimeout(timeout) {
  return McpRequestOptions.make(undefined, undefined, timeout, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined);
}

function getSome(option) {
  if (option !== undefined) {
    return Primitive_option.valFromOption(option);
  } else {
    return Stdlib_JsError.throwWithMessage("Expected value to be present");
  }
}

function makeTextContent(text) {
  return Object.fromEntries([
    [
      "type",
      "text"
    ],
    [
      "text",
      text
    ]
  ]);
}

function makeSamplingRequestParams(text, maxTokens) {
  return Object.fromEntries([
    [
      "messages",
      [Object.fromEntries([
          [
            "role",
            "user"
          ],
          [
            "content",
            makeTextContent(text)
          ]
        ])]
    ],
    [
      "maxTokens",
      maxTokens
    ]
  ]);
}

function makeCodeElicitationRequestParams(message) {
  return Object.fromEntries([
    [
      "mode",
      "form"
    ],
    [
      "message",
      message
    ],
    [
      "requestedSchema",
      Object.fromEntries([
        [
          "type",
          "object"
        ],
        [
          "properties",
          Object.fromEntries([[
              "code",
              Object.fromEntries([[
                  "type",
                  "string"
                ]])
            ]])
        ]
      ])
    ]
  ]);
}

function makeWebStandardTransport() {
  return McpWebStandardStreamableHttpServerTransport.make();
}

function makeWebStandardJsonTransport() {
  return McpWebStandardStreamableHttpServerTransport.makeWithOptions(McpWebStandardStreamableHttpServerTransportOptions.make(undefined, undefined, undefined, true, undefined, undefined, undefined, undefined, undefined, undefined, undefined));
}

function makeWebStandardStatefulJsonTransport(sessionId) {
  return McpWebStandardStreamableHttpServerTransport.makeWithOptions(McpWebStandardStreamableHttpServerTransportOptions.make(() => sessionId, undefined, undefined, true, undefined, undefined, undefined, undefined, undefined, undefined, undefined));
}

function makeNodeStreamableHttpTransport() {
  return McpNodeStreamableHttpServerTransport.make();
}

function makeNodeStreamableHttpJsonTransport() {
  return McpNodeStreamableHttpServerTransport.makeWithOptions(McpNodeStreamableHttpServerTransportOptions.make(undefined, undefined, undefined, true, undefined, undefined, undefined, undefined, undefined, undefined, undefined));
}

function makeNodeStreamableHttpStatefulJsonTransport(sessionId) {
  return McpNodeStreamableHttpServerTransport.makeWithOptions(McpNodeStreamableHttpServerTransportOptions.make(() => sessionId, undefined, undefined, true, undefined, undefined, undefined, undefined, undefined, undefined, undefined));
}

function makeStdioServerTransport() {
  return McpStdioServerTransport.make();
}

function makeStdioClientTransport(command, args, cwd) {
  return McpStdioClientTransport.make(McpStdioServerParameters.make(command, args, undefined, undefined, cwd));
}

function makeSSEClientTransport(url) {
  return McpSSEClientTransport.make(new URL(url));
}

function makeSSEClientTransportWithOptions(url, options) {
  return McpSSEClientTransport.makeWithOptions(new URL(url), options);
}

function makeStreamableHttpClientTransport(url) {
  return McpStreamableHttpClientTransport.make(new URL(url));
}

function makeStreamableHttpClientTransportWithSession(url, sessionId) {
  return McpStreamableHttpClientTransport.makeWithOptions(new URL(url), McpStreamableHttpClientTransportOptions.make(undefined, undefined, undefined, undefined, undefined, sessionId, undefined, undefined));
}

let transportStart = McpTransport.start;

let transportClose = McpTransport.close;

let transportSessionId = McpTransport.sessionId;

let connectLowLevelServer = McpLowLevelServer.connect;

let closeLowLevelServer = McpLowLevelServer.close;

let pingLowLevelServer = McpLowLevelServer.ping;

let lowLevelServerCapabilities = McpLowLevelServer.getCapabilities;

let createSamplingMessageRaw = McpLowLevelServer.createMessageRaw;

let elicitInputRaw = McpLowLevelServer.elicitInputRaw;

let listRootsRaw = McpLowLevelServer.listRoots;

let connectMcpServer = McpServer.connect;

let closeMcpServer = McpServer.close;

let mcpServerIsConnected = McpServer.isConnected;

let connectClient = McpClient.connect;

function connectClientWithTimeout(client, transport, timeout) {
  return McpClient.connectWithOptions(client, transport, makeRequestOptionsWithTimeout(timeout));
}

let closeClient = McpClient.close;

let pingClient = McpClient.ping;

function pingClientWithTimeout(client, timeout) {
  return McpClient.pingWithOptions(client, makeRequestOptionsWithTimeout(timeout));
}

let clientServerCapabilities = McpClient.getServerCapabilities;

let clientServerVersion = McpClient.getServerVersion;

let clientNegotiatedProtocolVersion = McpClient.getNegotiatedProtocolVersion;

let clientInstructions = McpClient.getInstructions;

let httpClientTerminateSession = McpStreamableHttpClientTransport.terminateSession;

let httpClientProtocolVersion = McpStreamableHttpClientTransport.protocolVersion;

let nodeHandleRequest = McpNodeStreamableHttpServerTransport.handleRequest;

let nodeHandleRequestWithParsedBody = McpNodeStreamableHttpServerTransport.handleRequestWithParsedBody;

let webHandleRequest = McpWebStandardStreamableHttpServerTransport.handleRequest;

function makeAuthInfo(token, clientId, scopes) {
  return McpAuthInfo.make(token, clientId, scopes, undefined, undefined, undefined);
}

function webHandleRequestWithAuthInfo(transport, request, authInfo) {
  return McpWebStandardStreamableHttpServerTransport.handleRequestWithOptions(transport, request, McpWebStandardStreamableHttpHandleRequestOptions.make(undefined, Primitive_option.some(authInfo), undefined));
}

let stdioClientPid = McpStdioClientTransport.pid;

let stdioClientStderr = McpStdioClientTransport.stderr;

function defaultEnvironment() {
  return McpStdioClientTransport.getDefaultEnvironment();
}

function listedTools(result) {
  return McpListToolsResult.tools(result).map(item => [
    McpListToolsResult.name(item),
    McpListToolsResult.title(item)
  ]);
}

function listedPrompts(result) {
  return McpListPromptsResult.prompts(result).map(item => [
    McpListPromptsResult.promptName(item),
    McpListPromptsResult.promptTitle(item)
  ]);
}

function listedResources(result) {
  return McpListResourcesResult.resources(result).map(item => [
    McpListResourcesResult.uri(item),
    McpListResourcesResult.name(item)
  ]);
}

function listedResourceTemplates(result) {
  return McpListResourceTemplatesResult.resourceTemplates(result).map(item => [
    McpListResourceTemplatesResult.uriTemplate(item),
    McpListResourceTemplatesResult.name(item)
  ]);
}

function toolResultTexts(result) {
  return Belt_Array.keepMap(McpCallToolResult.content(result), McpContentBlock.textValue);
}

function toolResultTextsRaw(result) {
  return Belt_Array.keepMap(McpCallToolResult.contentRaw(result), McpContentBlock.textValue);
}

function toolResultTextsUnknown(result) {
  return Belt_Array.keepMap(result.content, McpContentBlock.textValue);
}

function toolResultStructuredField(result, fieldName) {
  return Stdlib_Option.flatMap(McpCallToolResult.structuredContentRaw(result), dict => Stdlib_Option.flatMap(dict[fieldName], value => {
    if (typeof value !== "object") {
      return "null";
    }
    switch (value.TAG) {
      case "Bool" :
        return value._0 ? "true" : "false";
      case "Int" :
      case "Float" :
        return value._0.toString();
      case "String" :
        return value._0;
      case "Array" :
      case "Object" :
        return;
    }
  }));
}

function promptResultTexts(result) {
  return Belt_Array.keepMap(McpGetPromptResult.messages(result), message => McpContentBlock.textValue(McpPromptMessage.content(message)));
}

function promptResultRoles(result) {
  return McpGetPromptResult.messages(result).map(McpPromptMessage.role);
}

function readResourceTexts(result) {
  return Belt_Array.keepMap(McpReadResourceResult.contents(result), McpResourceContents.textValue);
}

function readResourceUris(result) {
  return McpReadResourceResult.contents(result).map(McpResourceContents.uri);
}

let Json;

let defaultInheritedEnvVars = McpStdioClientTransport.defaultInheritedEnvVars;

let getPromptResultDescription = McpGetPromptResult.description;

export {
  Json,
  makeLoopbackTransportPair,
  makeImplementation,
  makeLowLevelServer,
  makeLowLevelServerWithInstructions,
  makeMcpServer,
  makeMcpServerWithInstructions,
  makeClient,
  makeClientWithOptions,
  registerClientCapabilities,
  setClientRequestHandlerRaw,
  makeRequestOptionsWithTimeout,
  getSome,
  makeTextContent,
  makeSamplingRequestParams,
  makeCodeElicitationRequestParams,
  makeWebStandardTransport,
  makeWebStandardJsonTransport,
  makeWebStandardStatefulJsonTransport,
  makeNodeStreamableHttpTransport,
  makeNodeStreamableHttpJsonTransport,
  makeNodeStreamableHttpStatefulJsonTransport,
  makeStdioServerTransport,
  makeStdioClientTransport,
  makeSSEClientTransport,
  makeSSEClientTransportWithOptions,
  makeStreamableHttpClientTransport,
  makeStreamableHttpClientTransportWithSession,
  transportStart,
  transportClose,
  transportSessionId,
  connectLowLevelServer,
  closeLowLevelServer,
  pingLowLevelServer,
  lowLevelServerCapabilities,
  createSamplingMessageRaw,
  elicitInputRaw,
  listRootsRaw,
  connectMcpServer,
  closeMcpServer,
  mcpServerIsConnected,
  connectClient,
  connectClientWithTimeout,
  closeClient,
  pingClient,
  pingClientWithTimeout,
  clientServerCapabilities,
  clientServerVersion,
  clientNegotiatedProtocolVersion,
  clientInstructions,
  httpClientTerminateSession,
  httpClientProtocolVersion,
  nodeHandleRequest,
  nodeHandleRequestWithParsedBody,
  webHandleRequest,
  makeAuthInfo,
  webHandleRequestWithAuthInfo,
  stdioClientPid,
  stdioClientStderr,
  defaultInheritedEnvVars,
  defaultEnvironment,
  listedTools,
  listedPrompts,
  listedResources,
  listedResourceTemplates,
  toolResultTexts,
  toolResultTextsRaw,
  toolResultTextsUnknown,
  toolResultStructuredField,
  getPromptResultDescription,
  promptResultTexts,
  promptResultRoles,
  readResourceTexts,
  readResourceUris,
}
/* McpClient Not a pure module */
