// Generated by ReScript, PLEASE EDIT WITH CARE

import * as McpImplementation from "../src/core/McpImplementation.mjs";
import * as McpLowLevelServer from "../src/server/McpLowLevelServer.mjs";
import * as McpWebStandardStreamableHttpServerTransport from "../src/transports/McpWebStandardStreamableHttpServerTransport.mjs";
import * as McpWebStandardStreamableHttpServerTransportOptions from "../src/transports/McpWebStandardStreamableHttpServerTransportOptions.mjs";

let implementation = McpImplementation.make("example-server", "0.1.0");

let server = McpLowLevelServer.make(implementation);

let transport = McpWebStandardStreamableHttpServerTransport.makeWithOptions(McpWebStandardStreamableHttpServerTransportOptions.make(undefined, undefined, undefined, true, undefined, undefined, undefined, undefined, undefined, undefined));

let _promise = McpLowLevelServer.connect(server, transport);

export {
  implementation,
  server,
  transport,
  _promise,
}
/* implementation Not a pure module */
