// Generated by ReScript, PLEASE EDIT WITH CARE

import * as McpClient from "../src/client/McpClient.mjs";
import * as McpImplementation from "../src/core/McpImplementation.mjs";
import * as McpStreamableHttpClientTransport from "../src/transports/McpStreamableHttpClientTransport.mjs";

let implementation = McpImplementation.make("example-client", "0.1.0");

let client = McpClient.make(implementation);

let transport = McpStreamableHttpClientTransport.make(new URL("http://127.0.0.1:8788/mcp"));

let _promise = McpClient.connect(client, transport);

export {
  implementation,
  client,
  transport,
  _promise,
}
/* implementation Not a pure module */
