// Generated by ReScript, PLEASE EDIT WITH CARE

import * as Primitive_option from "@rescript/runtime/lib/es6/Primitive_option.js";

function make(prim0, prim1, prim2, prim3, prim4, prim5) {
  let tmp = {
    token: prim0,
    clientId: prim1,
    scopes: prim2
  };
  if (prim3 !== undefined) {
    tmp.expiresAt = prim3;
  }
  if (prim4 !== undefined) {
    tmp.resource = Primitive_option.valFromOption(prim4);
  }
  if (prim5 !== undefined) {
    tmp.extra = Primitive_option.valFromOption(prim5);
  }
  return tmp;
}

export {
  make,
}
/* No side effect */
