// Generated by ReScript, PLEASE EDIT WITH CARE

import * as Primitive_option from "@rescript/runtime/lib/es6/Primitive_option.js";

function make(prim0, prim1, prim2, prim3, prim4) {
  let tmp = {};
  if (prim0 !== undefined) {
    tmp.request = Primitive_option.valFromOption(prim0);
  }
  if (prim1 !== undefined) {
    tmp.authInfo = Primitive_option.valFromOption(prim1);
  }
  if (prim2 !== undefined) {
    tmp.closeSSEStream = Primitive_option.valFromOption(prim2);
  }
  if (prim3 !== undefined) {
    tmp.closeStandaloneSSEStream = Primitive_option.valFromOption(prim3);
  }
  return tmp;
}

function request(prim) {
  return Primitive_option.fromNullable(prim.request);
}

function authInfo(prim) {
  return Primitive_option.fromNullable(prim.authInfo);
}

function closeSSEStream(prim) {
  return Primitive_option.fromNullable(prim.closeSSEStream);
}

function closeStandaloneSSEStream(prim) {
  return Primitive_option.fromNullable(prim.closeStandaloneSSEStream);
}

export {
  make,
  request,
  authInfo,
  closeSSEStream,
  closeStandaloneSSEStream,
}
/* No side effect */
