// Generated by ReScript, PLEASE EDIT WITH CARE

import * as Stdlib_JsError from "@rescript/runtime/lib/es6/Stdlib_JsError.js";

function toString(version) {
  if (version === "v2024_11_05") {
    return "2024-11-05";
  } else if (version === "v2025_03_26") {
    return "2025-03-26";
  } else if (version === "v2025_06_18") {
    return "2025-06-18";
  } else if (version === "v2025_11_25") {
    return "2025-11-25";
  } else {
    return "2024-10-07";
  }
}

function fromString(version) {
  switch (version) {
    case "2024-10-07" :
      return "v2024_10_07";
    case "2024-11-05" :
      return "v2024_11_05";
    case "2025-03-26" :
      return "v2025_03_26";
    case "2025-06-18" :
      return "v2025_06_18";
    case "2025-11-25" :
      return "v2025_11_25";
    default:
      return Stdlib_JsError.throwWithMessage("Unsupported MCP protocol version: " + version);
  }
}

let supported = [
  "v2025_11_25",
  "v2025_06_18",
  "v2025_03_26",
  "v2024_11_05",
  "v2024_10_07"
];

let latest = "v2025_11_25";

let defaultNegotiated = "v2025_03_26";

export {
  toString,
  fromString,
  latest,
  defaultNegotiated,
  supported,
}
/* No side effect */
