// Generated by ReScript, PLEASE EDIT WITH CARE

import * as Primitive_option from "@rescript/runtime/lib/es6/Primitive_option.js";

function make(prim0, prim1, prim2) {
  let tmp = {
    headers: prim0
  };
  if (prim1 !== undefined) {
    tmp.url = Primitive_option.valFromOption(prim1);
  }
  return tmp;
}

function headers(prim) {
  return prim.headers;
}

function url(prim) {
  return Primitive_option.fromNullable(prim.url);
}

export {
  make,
  headers,
  url,
}
/* No side effect */
