// Generated by ReScript, PLEASE EDIT WITH CARE

import * as Primitive_option from "@rescript/runtime/lib/es6/Primitive_option.js";

function authInfo(prim) {
  return Primitive_option.fromNullable(prim.authInfo);
}

function sessionId(prim) {
  return Primitive_option.fromNullable(prim.sessionId);
}

function requestId(prim) {
  return prim.requestId;
}

function taskId(prim) {
  return Primitive_option.fromNullable(prim.taskId);
}

function requestInfo(prim) {
  return Primitive_option.fromNullable(prim.requestInfo);
}

function closeSSEStream(prim) {
  return Primitive_option.fromNullable(prim.closeSSEStream);
}

function closeStandaloneSSEStream(prim) {
  return Primitive_option.fromNullable(prim.closeStandaloneSSEStream);
}

export {
  authInfo,
  sessionId,
  requestId,
  taskId,
  requestInfo,
  closeSSEStream,
  closeStandaloneSSEStream,
}
/* No side effect */
