// Generated by ReScript, PLEASE EDIT WITH CARE

import * as Types from "@modelcontextprotocol/sdk/types";

let latestProtocolVersion = Types.LATEST_PROTOCOL_VERSION;

let defaultNegotiatedProtocolVersion = Types.DEFAULT_NEGOTIATED_PROTOCOL_VERSION;

let supportedProtocolVersions = Types.SUPPORTED_PROTOCOL_VERSIONS;

let relatedTaskMetaKey = Types.RELATED_TASK_META_KEY;

let jsonRpcVersion = Types.JSONRPC_VERSION;

function jsonRpcMessageFromUnknown(prim) {
  return prim;
}

function jsonRpcMessageToUnknown(prim) {
  return prim;
}

function requestIdFromUnknown(prim) {
  return prim;
}

function requestIdToUnknown(prim) {
  return prim;
}

export {
  latestProtocolVersion,
  defaultNegotiatedProtocolVersion,
  supportedProtocolVersions,
  relatedTaskMetaKey,
  jsonRpcVersion,
  jsonRpcMessageFromUnknown,
  jsonRpcMessageToUnknown,
  requestIdFromUnknown,
  requestIdToUnknown,
}
/* latestProtocolVersion Not a pure module */
