// Generated by ReScript, PLEASE EDIT WITH CARE

import * as TypesJs from "@modelcontextprotocol/sdk/types.js";

let latestProtocolVersion = TypesJs.LATEST_PROTOCOL_VERSION;

let defaultNegotiatedProtocolVersion = TypesJs.DEFAULT_NEGOTIATED_PROTOCOL_VERSION;

let supportedProtocolVersions = TypesJs.SUPPORTED_PROTOCOL_VERSIONS;

let relatedTaskMetaKey = TypesJs.RELATED_TASK_META_KEY;

let jsonRpcVersion = TypesJs.JSONRPC_VERSION;

function jsonRpcMessageFromUnknown(prim) {
  return prim;
}

function jsonRpcMessageToUnknown(prim) {
  return prim;
}

function requestIdFromUnknown(prim) {
  return prim;
}

function requestIdToUnknown(prim) {
  return prim;
}

export {
  latestProtocolVersion,
  defaultNegotiatedProtocolVersion,
  supportedProtocolVersions,
  relatedTaskMetaKey,
  jsonRpcVersion,
  jsonRpcMessageFromUnknown,
  jsonRpcMessageToUnknown,
  requestIdFromUnknown,
  requestIdToUnknown,
}
/* latestProtocolVersion Not a pure module */
