// Generated by ReScript, PLEASE EDIT WITH CARE

import * as McpProtocolVersion from "./McpProtocolVersion.mjs";
import * as Server from "@modelcontextprotocol/server";

let latestProtocolVersion = McpProtocolVersion.fromString(Server.LATEST_PROTOCOL_VERSION);

let defaultNegotiatedProtocolVersion = McpProtocolVersion.fromString(Server.DEFAULT_NEGOTIATED_PROTOCOL_VERSION);

let supportedProtocolVersions = Server.SUPPORTED_PROTOCOL_VERSIONS.map(McpProtocolVersion.fromString);

let relatedTaskMetaKey = Server.RELATED_TASK_META_KEY;

let jsonRpcVersion = Server.JSONRPC_VERSION;

export {
  latestProtocolVersion,
  defaultNegotiatedProtocolVersion,
  supportedProtocolVersions,
  relatedTaskMetaKey,
  jsonRpcVersion,
}
/* latestProtocolVersion Not a pure module */
