// Generated by ReScript, PLEASE EDIT WITH CARE

import * as McpServerOptions from "../../src/server/McpServerOptions.mjs";
import * as McpImplementation from "../../src/core/McpImplementation.mjs";
import * as McpLowLevelServer from "../../src/server/McpLowLevelServer.mjs";
import * as McpStdioServerTransport from "../../src/transports/McpStdioServerTransport.mjs";

let _server = McpLowLevelServer.makeWithOptions(McpImplementation.make("stdio-test-server", "1.0.0"), McpServerOptions.make(undefined, "stdio test server", undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined));

let _transport = McpStdioServerTransport.make();

let _connection = McpLowLevelServer.connect(_server, _transport);

export {
  _server,
  _transport,
  _connection,
}
/* _server Not a pure module */
