// Generated by ReScript, PLEASE EDIT WITH CARE

import * as McpTool from "../../src/server/McpTool.mjs";
import * as McpPrompt from "../../src/server/McpPrompt.mjs";
import * as McpServer from "../../src/server/McpServer.mjs";
import * as McpResource from "../../src/server/McpResource.mjs";
import * as McpContentBlock from "../../src/protocol/McpContentBlock.mjs";
import * as McpPromptMessage from "../../src/protocol/McpPromptMessage.mjs";
import * as McpServerOptions from "../../src/server/McpServerOptions.mjs";
import * as Primitive_option from "@rescript/runtime/lib/es6/Primitive_option.js";
import * as S$RescriptSchema from "rescript-schema/src/S.mjs";
import * as McpCallToolResult from "../../src/protocol/McpCallToolResult.mjs";
import * as McpImplementation from "../../src/core/McpImplementation.mjs";
import * as McpStandardSchema from "../../src/protocol/McpStandardSchema.mjs";
import * as McpGetPromptResult from "../../src/protocol/McpGetPromptResult.mjs";
import * as McpResourceContents from "../../src/protocol/McpResourceContents.mjs";
import * as McpReadResourceResult from "../../src/protocol/McpReadResourceResult.mjs";
import * as McpStdioServerTransport from "../../src/transports/McpStdioServerTransport.mjs";

let echoArgsSchema = S$RescriptSchema.schema(s => ({
  message: s.m(S$RescriptSchema.string)
}));

let echoOutputSchema = S$RescriptSchema.schema(s => ({
  echoed: s.m(S$RescriptSchema.string)
}));

let promptArgsSchema = S$RescriptSchema.schema(s => ({
  topic: s.m(S$RescriptSchema.string)
}));

let server = McpServer.makeWithOptions(McpImplementation.make("stdio-authoring-server", "1.0.0"), McpServerOptions.make(undefined, "stdio authoring server", undefined, undefined, undefined, undefined, undefined, undefined));

let _tool = McpServer.registerTool(server, "echo", McpTool.makeConfig("Echo", "Echoes the provided message", Primitive_option.some(McpStandardSchema.fromRescriptSchema(echoArgsSchema)), McpStandardSchema.fromRescriptSchema(echoOutputSchema), undefined, undefined, undefined), async (args, _ctx) => McpCallToolResult.make([McpContentBlock.text("echo:" + args.message)], {
  echoed: args.message
}, undefined, undefined));

let _prompt = McpServer.registerPrompt(server, "review", McpPrompt.makeConfig("Review", "Creates a simple review prompt", Primitive_option.some(McpStandardSchema.fromRescriptSchema(promptArgsSchema)), undefined, undefined), async (args, _ctx) => McpGetPromptResult.make([McpPromptMessage.text("user", "Review " + args.topic)], "Review prompt", undefined));

let _resource = McpServer.registerResource(server, "config", "config://app", McpResource.makeConfig("Config", "Static test config", "application/json", undefined, undefined, undefined, undefined), async (uri, _ctx) => McpReadResourceResult.make([McpResourceContents.text(uri.href, "{\"ok\":true}", "application/json", undefined)]));

let _transport = McpStdioServerTransport.make();

let _connection = McpServer.connect(server, _transport);

let Json;

export {
  Json,
  echoArgsSchema,
  echoOutputSchema,
  promptArgsSchema,
  server,
  _tool,
  _prompt,
  _resource,
  _transport,
  _connection,
}
/* echoArgsSchema Not a pure module */
