// Generated by ReScript, PLEASE EDIT WITH CARE

import * as McpMethod from "../protocol/McpMethod.mjs";
import * as Stdlib_Option from "@rescript/runtime/lib/es6/Stdlib_Option.js";
import * as Primitive_option from "@rescript/runtime/lib/es6/Primitive_option.js";
import * as McpProtocolVersion from "../core/McpProtocolVersion.mjs";
import * as McpCallToolResultInternal from "../protocol/McpCallToolResultInternal.mjs";
import * as Client from "@modelcontextprotocol/client";

function experimentalTasks(client) {
  return client.experimental.tasks;
}

function setRequestHandlerRaw(client, method_, handler) {
  client.setRequestHandler(McpMethod.requestToString(method_), handler);
}

function setNotificationHandlerRaw(client, method_, handler) {
  client.setNotificationHandler(McpMethod.notificationToString(method_), handler);
}

function removeNotificationHandlerRaw(client, method_) {
  client.removeNotificationHandler(McpMethod.notificationToString(method_));
}

function getNegotiatedProtocolVersion(client) {
  return Stdlib_Option.map(Primitive_option.fromNullable(client.getNegotiatedProtocolVersion()), McpProtocolVersion.fromString);
}

function callTool(client, params, outputSchema) {
  return client.callTool(params, outputSchema).then(result => Promise.resolve(McpCallToolResultInternal.fromRaw(result, outputSchema)));
}

function callToolWithOptions(client, params, outputSchema, options) {
  return client.callTool(params, outputSchema, options).then(result => Promise.resolve(McpCallToolResultInternal.fromRaw(result, outputSchema)));
}

function make(prim) {
  return new Client.Client(prim);
}

function makeWithOptions(prim0, prim1) {
  return new Client.Client(prim0, prim1);
}

function registerCapabilities(prim0, prim1) {
  prim0.registerCapabilities(prim1);
}

function connect(prim0, prim1) {
  return prim0.connect(prim1);
}

function connectWithOptions(prim0, prim1, prim2) {
  return prim0.connect(prim1, prim2);
}

function close(prim) {
  return prim.close();
}

function ping(prim) {
  return prim.ping();
}

function pingWithOptions(prim0, prim1) {
  return prim0.ping(prim1);
}

function getServerCapabilities(prim) {
  return Primitive_option.fromNullable(prim.getServerCapabilities());
}

function getServerVersion(prim) {
  return Primitive_option.fromNullable(prim.getServerVersion());
}

function getInstructions(prim) {
  return Primitive_option.fromNullable(prim.getInstructions());
}

function complete(prim0, prim1) {
  return prim0.complete(prim1);
}

function completeWithOptions(prim0, prim1, prim2) {
  return prim0.complete(prim1, prim2);
}

function setLoggingLevel(prim0, prim1) {
  return prim0.setLoggingLevel(prim1);
}

function setLoggingLevelWithOptions(prim0, prim1, prim2) {
  return prim0.setLoggingLevel(prim1, prim2);
}

function getPrompt(prim0, prim1) {
  return prim0.getPrompt(prim1);
}

function getPromptWithOptions(prim0, prim1, prim2) {
  return prim0.getPrompt(prim1, prim2);
}

function listPrompts(prim) {
  return prim.listPrompts();
}

function listPromptsWithParamsAndOptions(prim0, prim1, prim2) {
  return prim0.listPrompts(prim1, prim2);
}

function listResources(prim) {
  return prim.listResources();
}

function listResourcesWithParamsAndOptions(prim0, prim1, prim2) {
  return prim0.listResources(prim1, prim2);
}

function listResourceTemplates(prim) {
  return prim.listResourceTemplates();
}

function listResourceTemplatesWithParamsAndOptions(prim0, prim1, prim2) {
  return prim0.listResourceTemplates(prim1, prim2);
}

function readResource(prim0, prim1) {
  return prim0.readResource(prim1);
}

function readResourceWithOptions(prim0, prim1, prim2) {
  return prim0.readResource(prim1, prim2);
}

function subscribeResource(prim0, prim1) {
  return prim0.subscribeResource(prim1);
}

function subscribeResourceWithOptions(prim0, prim1, prim2) {
  return prim0.subscribeResource(prim1, prim2);
}

function unsubscribeResource(prim0, prim1) {
  return prim0.unsubscribeResource(prim1);
}

function unsubscribeResourceWithOptions(prim0, prim1, prim2) {
  return prim0.unsubscribeResource(prim1, prim2);
}

function callToolRaw(prim0, prim1) {
  return prim0.callTool(prim1);
}

function callToolRawWithOptions(prim0, prim1, prim2) {
  return prim0.callTool(prim1, prim2);
}

function listTools(prim) {
  return prim.listTools();
}

function listToolsWithParamsAndOptions(prim0, prim1, prim2) {
  return prim0.listTools(prim1, prim2);
}

export {
  make,
  makeWithOptions,
  experimentalTasks,
  registerCapabilities,
  setRequestHandlerRaw,
  setNotificationHandlerRaw,
  removeNotificationHandlerRaw,
  connect,
  connectWithOptions,
  close,
  ping,
  pingWithOptions,
  getServerCapabilities,
  getServerVersion,
  getNegotiatedProtocolVersion,
  getInstructions,
  complete,
  completeWithOptions,
  setLoggingLevel,
  setLoggingLevelWithOptions,
  getPrompt,
  getPromptWithOptions,
  listPrompts,
  listPromptsWithParamsAndOptions,
  listResources,
  listResourcesWithParamsAndOptions,
  listResourceTemplates,
  listResourceTemplatesWithParamsAndOptions,
  readResource,
  readResourceWithOptions,
  subscribeResource,
  subscribeResourceWithOptions,
  unsubscribeResource,
  unsubscribeResourceWithOptions,
  callTool,
  callToolWithOptions,
  callToolRaw,
  callToolRawWithOptions,
  listTools,
  listToolsWithParamsAndOptions,
}
/* McpCallToolResultInternal Not a pure module */
