// Generated by ReScript, PLEASE EDIT WITH CARE

import * as Primitive_option from "@rescript/runtime/lib/es6/Primitive_option.js";
import * as Client from "@modelcontextprotocol/sdk/client";

function make(prim) {
  return new Client.Client(prim);
}

function makeWithOptions(prim0, prim1) {
  return new Client.Client(prim0, prim1);
}

function connect(prim0, prim1) {
  return prim0.connect(prim1);
}

function connectWithOptions(prim0, prim1, prim2) {
  return prim0.connect(prim1, prim2);
}

function close(prim) {
  return prim.close();
}

function ping(prim) {
  return prim.ping();
}

function pingWithOptions(prim0, prim1) {
  return prim0.ping(prim1);
}

function getServerCapabilities(prim) {
  return Primitive_option.fromNullable(prim.getServerCapabilities());
}

function getServerVersion(prim) {
  return Primitive_option.fromNullable(prim.getServerVersion());
}

function getInstructions(prim) {
  return Primitive_option.fromNullable(prim.getInstructions());
}

function complete(prim0, prim1) {
  return prim0.complete(prim1);
}

function completeWithOptions(prim0, prim1, prim2) {
  return prim0.complete(prim1, prim2);
}

function setLoggingLevel(prim0, prim1) {
  return prim0.setLoggingLevel(prim1);
}

function setLoggingLevelWithOptions(prim0, prim1, prim2) {
  return prim0.setLoggingLevel(prim1, prim2);
}

function getPrompt(prim0, prim1) {
  return prim0.getPrompt(prim1);
}

function getPromptWithOptions(prim0, prim1, prim2) {
  return prim0.getPrompt(prim1, prim2);
}

function listPrompts(prim) {
  return prim.listPrompts();
}

function listPromptsWithParamsAndOptions(prim0, prim1, prim2) {
  return prim0.listPrompts(prim1, prim2);
}

function listResources(prim) {
  return prim.listResources();
}

function listResourcesWithParamsAndOptions(prim0, prim1, prim2) {
  return prim0.listResources(prim1, prim2);
}

function listResourceTemplates(prim) {
  return prim.listResourceTemplates();
}

function listResourceTemplatesWithParamsAndOptions(prim0, prim1, prim2) {
  return prim0.listResourceTemplates(prim1, prim2);
}

function readResource(prim0, prim1) {
  return prim0.readResource(prim1);
}

function readResourceWithOptions(prim0, prim1, prim2) {
  return prim0.readResource(prim1, prim2);
}

function subscribeResource(prim0, prim1) {
  return prim0.subscribeResource(prim1);
}

function subscribeResourceWithOptions(prim0, prim1, prim2) {
  return prim0.subscribeResource(prim1, prim2);
}

function unsubscribeResource(prim0, prim1) {
  return prim0.unsubscribeResource(prim1);
}

function unsubscribeResourceWithOptions(prim0, prim1, prim2) {
  return prim0.unsubscribeResource(prim1, prim2);
}

function callToolRaw(prim0, prim1) {
  return prim0.callTool(prim1);
}

function callToolRawWithOptions(prim0, prim1, prim2) {
  return prim0.callTool(prim1, prim2);
}

function callToolWithResultSchemaRaw(prim0, prim1, prim2) {
  return prim0.callTool(prim1, prim2);
}

function callToolWithResultSchemaRawAndOptions(prim0, prim1, prim2, prim3) {
  return prim0.callTool(prim1, prim2, prim3);
}

function listTools(prim) {
  return prim.listTools();
}

function listToolsWithParamsAndOptions(prim0, prim1, prim2) {
  return prim0.listTools(prim1, prim2);
}

export {
  make,
  makeWithOptions,
  connect,
  connectWithOptions,
  close,
  ping,
  pingWithOptions,
  getServerCapabilities,
  getServerVersion,
  getInstructions,
  complete,
  completeWithOptions,
  setLoggingLevel,
  setLoggingLevelWithOptions,
  getPrompt,
  getPromptWithOptions,
  listPrompts,
  listPromptsWithParamsAndOptions,
  listResources,
  listResourcesWithParamsAndOptions,
  listResourceTemplates,
  listResourceTemplatesWithParamsAndOptions,
  readResource,
  readResourceWithOptions,
  subscribeResource,
  subscribeResourceWithOptions,
  unsubscribeResource,
  unsubscribeResourceWithOptions,
  callToolRaw,
  callToolRawWithOptions,
  callToolWithResultSchemaRaw,
  callToolWithResultSchemaRawAndOptions,
  listTools,
  listToolsWithParamsAndOptions,
}
/* @modelcontextprotocol/sdk/client Not a pure module */
