// Generated by ReScript, PLEASE EDIT WITH CARE

import * as McpClient from "../../src/client/McpClient.mjs";
import * as McpServer from "../../src/server/McpServer.mjs";
import * as McpAuthInfo from "../../src/core/McpAuthInfo.mjs";
import * as McpTransport from "../../src/shared/McpTransport.mjs";
import * as McpClientOptions from "../../src/client/McpClientOptions.mjs";
import * as McpServerOptions from "../../src/server/McpServerOptions.mjs";
import * as Primitive_option from "@rescript/runtime/lib/es6/Primitive_option.js";
import * as McpImplementation from "../../src/core/McpImplementation.mjs";
import * as McpLowLevelServer from "../../src/server/McpLowLevelServer.mjs";
import * as McpRequestOptions from "../../src/shared/McpRequestOptions.mjs";
import * as McpStdioClientTransport from "../../src/transports/McpStdioClientTransport.mjs";
import * as McpStdioServerTransport from "../../src/transports/McpStdioServerTransport.mjs";
import * as McpStdioServerParameters from "../../src/transports/McpStdioServerParameters.mjs";
import * as McpWebSocketClientTransport from "../../src/transports/McpWebSocketClientTransport.mjs";
import * as McpStreamableHttpClientTransport from "../../src/transports/McpStreamableHttpClientTransport.mjs";
import * as McpNodeStreamableHttpServerTransport from "../../src/transports/McpNodeStreamableHttpServerTransport.mjs";
import * as McpStreamableHttpClientTransportOptions from "../../src/transports/McpStreamableHttpClientTransportOptions.mjs";
import * as McpNodeStreamableHttpServerTransportOptions from "../../src/transports/McpNodeStreamableHttpServerTransportOptions.mjs";
import * as McpWebStandardStreamableHttpServerTransport from "../../src/transports/McpWebStandardStreamableHttpServerTransport.mjs";
import * as McpWebStandardStreamableHttpHandleRequestOptions from "../../src/transports/McpWebStandardStreamableHttpHandleRequestOptions.mjs";
import * as McpWebStandardStreamableHttpServerTransportOptions from "../../src/transports/McpWebStandardStreamableHttpServerTransportOptions.mjs";

let makeImplementation = McpImplementation.make;

function makeLowLevelServer(name, version) {
  return McpLowLevelServer.make(McpImplementation.make(name, version));
}

function makeLowLevelServerWithInstructions(name, version, instructions) {
  return McpLowLevelServer.makeWithOptions(McpImplementation.make(name, version), McpServerOptions.make(undefined, instructions, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined));
}

function makeMcpServer(name, version) {
  return McpServer.make(McpImplementation.make(name, version));
}

function makeMcpServerWithInstructions(name, version, instructions) {
  return McpServer.makeWithOptions(McpImplementation.make(name, version), McpServerOptions.make(undefined, instructions, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined));
}

function makeClient(name, version) {
  return McpClient.make(McpImplementation.make(name, version));
}

function makeClientWithOptions(name, version) {
  return McpClient.makeWithOptions(McpImplementation.make(name, version), McpClientOptions.make(undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined));
}

function makeRequestOptionsWithTimeout(timeout) {
  return McpRequestOptions.make(undefined, undefined, timeout, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined);
}

function makeWebStandardTransport() {
  return McpWebStandardStreamableHttpServerTransport.make();
}

function makeWebStandardJsonTransport() {
  return McpWebStandardStreamableHttpServerTransport.makeWithOptions(McpWebStandardStreamableHttpServerTransportOptions.make(undefined, undefined, undefined, true, undefined, undefined, undefined, undefined, undefined, undefined));
}

function makeWebStandardStatefulJsonTransport(sessionId) {
  return McpWebStandardStreamableHttpServerTransport.makeWithOptions(McpWebStandardStreamableHttpServerTransportOptions.make(() => sessionId, undefined, undefined, true, undefined, undefined, undefined, undefined, undefined, undefined));
}

function makeNodeStreamableHttpTransport() {
  return McpNodeStreamableHttpServerTransport.make();
}

function makeNodeStreamableHttpJsonTransport() {
  return McpNodeStreamableHttpServerTransport.makeWithOptions(McpNodeStreamableHttpServerTransportOptions.make(undefined, undefined, undefined, true, undefined, undefined, undefined, undefined, undefined, undefined));
}

function makeNodeStreamableHttpStatefulJsonTransport(sessionId) {
  return McpNodeStreamableHttpServerTransport.makeWithOptions(McpNodeStreamableHttpServerTransportOptions.make(() => sessionId, undefined, undefined, true, undefined, undefined, undefined, undefined, undefined, undefined));
}

function makeStdioServerTransport() {
  return McpStdioServerTransport.make();
}

function makeStdioClientTransport(command, args, cwd) {
  return McpStdioClientTransport.make(McpStdioServerParameters.make(command, args, undefined, undefined, cwd));
}

function makeStreamableHttpClientTransport(url) {
  return McpStreamableHttpClientTransport.make(new URL(url));
}

function makeStreamableHttpClientTransportWithSession(url, sessionId) {
  return McpStreamableHttpClientTransport.makeWithOptions(new URL(url), McpStreamableHttpClientTransportOptions.make(undefined, undefined, undefined, undefined, sessionId, undefined));
}

function makeWebSocketClientTransport(url) {
  return McpWebSocketClientTransport.make(new URL(url));
}

let transportStart = McpTransport.start;

let transportClose = McpTransport.close;

let transportSessionId = McpTransport.sessionId;

let connectLowLevelServer = McpLowLevelServer.connect;

let closeLowLevelServer = McpLowLevelServer.close;

let pingLowLevelServer = McpLowLevelServer.ping;

let connectMcpServer = McpServer.connect;

let closeMcpServer = McpServer.close;

let mcpServerIsConnected = McpServer.isConnected;

let connectClient = McpClient.connect;

function connectClientWithTimeout(client, transport, timeout) {
  return McpClient.connectWithOptions(client, transport, makeRequestOptionsWithTimeout(timeout));
}

let closeClient = McpClient.close;

let pingClient = McpClient.ping;

function pingClientWithTimeout(client, timeout) {
  return McpClient.pingWithOptions(client, makeRequestOptionsWithTimeout(timeout));
}

let clientServerCapabilities = McpClient.getServerCapabilities;

let clientServerVersion = McpClient.getServerVersion;

let clientInstructions = McpClient.getInstructions;

let httpClientTerminateSession = McpStreamableHttpClientTransport.terminateSession;

let httpClientProtocolVersion = McpStreamableHttpClientTransport.protocolVersion;

let nodeHandleRequest = McpNodeStreamableHttpServerTransport.handleRequest;

let nodeHandleRequestWithParsedBody = McpNodeStreamableHttpServerTransport.handleRequestWithParsedBody;

let webHandleRequest = McpWebStandardStreamableHttpServerTransport.handleRequest;

function makeAuthInfo(token, clientId, scopes) {
  return McpAuthInfo.make(token, clientId, scopes, undefined, undefined, undefined);
}

function webHandleRequestWithAuthInfo(transport, request, authInfo) {
  return McpWebStandardStreamableHttpServerTransport.handleRequestWithOptions(transport, request, McpWebStandardStreamableHttpHandleRequestOptions.make(undefined, Primitive_option.some(authInfo), undefined));
}

let stdioClientPid = McpStdioClientTransport.pid;

let stdioClientStderr = McpStdioClientTransport.stderr;

function defaultEnvironment() {
  return McpStdioClientTransport.getDefaultEnvironment();
}

let defaultInheritedEnvVars = McpStdioClientTransport.defaultInheritedEnvVars;

export {
  makeImplementation,
  makeLowLevelServer,
  makeLowLevelServerWithInstructions,
  makeMcpServer,
  makeMcpServerWithInstructions,
  makeClient,
  makeClientWithOptions,
  makeRequestOptionsWithTimeout,
  makeWebStandardTransport,
  makeWebStandardJsonTransport,
  makeWebStandardStatefulJsonTransport,
  makeNodeStreamableHttpTransport,
  makeNodeStreamableHttpJsonTransport,
  makeNodeStreamableHttpStatefulJsonTransport,
  makeStdioServerTransport,
  makeStdioClientTransport,
  makeStreamableHttpClientTransport,
  makeStreamableHttpClientTransportWithSession,
  makeWebSocketClientTransport,
  transportStart,
  transportClose,
  transportSessionId,
  connectLowLevelServer,
  closeLowLevelServer,
  pingLowLevelServer,
  connectMcpServer,
  closeMcpServer,
  mcpServerIsConnected,
  connectClient,
  connectClientWithTimeout,
  closeClient,
  pingClient,
  pingClientWithTimeout,
  clientServerCapabilities,
  clientServerVersion,
  clientInstructions,
  httpClientTerminateSession,
  httpClientProtocolVersion,
  nodeHandleRequest,
  nodeHandleRequestWithParsedBody,
  webHandleRequest,
  makeAuthInfo,
  webHandleRequestWithAuthInfo,
  stdioClientPid,
  stdioClientStderr,
  defaultInheritedEnvVars,
  defaultEnvironment,
}
/* McpClient Not a pure module */
